project:
  type: book
  output-dir: docs/

book:
  title: "Anomalías 2026-2"
  author: ""
  date: today
  date-format: "DD/MM/YYYY"
  language: es
  chapters:
    - index.qmd
    - libro/intro.qmd
    - part: "Clases"
      chapters:
        - notebooks/001_birthday_problem.ipynb
        - notebooks/002_triangulo_pascal.ipynb
        - notebooks/003_sampling_distribution.ipynb
        - notebooks/004_Central_limit_teorem.ipynb
        - notebooks/005_DistribucionNormal_Seleccion.ipynb
        - notebooks/006_experimentos_nueve.ipynb

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: false
    code-tools: true

execute:
  freeze: auto
