<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>14&nbsp; AR-MA · Laboratorio · La Ventosa, Oaxaca – Anomalías 2026-2</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../notebooks/015_ARMA_Cheatsheet.html" rel="next">
<link href="../notebooks/011_laboratorio_climalab.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-5ccb035bea26c1e21f80f44cf7c27909.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../notebooks/001_birthday_problem.html">Clases</a></li><li class="breadcrumb-item"><a href="../notebooks/014b_LaVentosa.html"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">AR-MA · Laboratorio · La Ventosa, Oaxaca</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Anomalías 2026-2</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prefacio</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../libro/intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introducción</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Clases</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/001_birthday_problem.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">El problema del cumpleaños</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/002_triangulo_pascal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">002_triangulo_pascal.html</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/003_sampling_distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">003_sampling_distribution.html</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/004_Central_limit_teorem.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">004_Central_limit_teorem.html</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/005_DistribucionNormal_Seleccion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">005_DistribucionNormal_Seleccion.html</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/006_experimentos_nueve.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">006_experimentos_nueve.html</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/007_muestreo_teoria.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Semana 4A — Muestreo y Estimación (Teoría)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/008a_muestreo_lab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Semana 4B — Muestreo y Estimación (Laboratorio)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/008b_muestreo_lab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">1. Cargar y conocer la población</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/009_PruebasHipotesis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title"><code>stats.t.ppf(1 - alpha/2, gl)</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/010_teoria_componentes_y_descomposicion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Sesión 1 · Teoría</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/011_laboratorio_climalab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Sesión 1 · Laboratorio</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/014b_LaVentosa.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">AR-MA · Laboratorio · La Ventosa, Oaxaca</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/015_ARMA_Cheatsheet.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">ARMA Cheatsheet · Box-Jenkins de bolsillo</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/016_SARIMA_LaVentosa_src.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">016 · SARIMA · Laboratorio · La Ventosa, Oaxaca</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/017_SARIMA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">SARIMA — del modelo a un ejemplo con viento</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/018_sarima_esolmet.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">018_sarima_esolmet.html</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/019_tdb_teoria_exploracion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">019 · Introducción a SARIMA + exploración de <code>tdb</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/020_tdb_configuracion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">020 · Configurar SARIMA desde el código — <code>tdb</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/021_tdb_outliers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">021 · Detección de outliers con SARIMA — <code>tdb</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/022_temario_sarimax.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Temario · Aprender SARIMAX desde cero (perfil ingeniería)</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#setup" id="toc-setup" class="nav-link active" data-scroll-target="#setup"><span class="header-section-number">14.1</span> Setup</a></li>
  <li><a href="#bloque-1-flujo-de-trabajo-y-conceptos-clave" id="toc-bloque-1-flujo-de-trabajo-y-conceptos-clave" class="nav-link" data-scroll-target="#bloque-1-flujo-de-trabajo-y-conceptos-clave"><span class="header-section-number">15</span> Bloque 1 · Flujo de trabajo y conceptos clave</a>
  <ul class="collapse">
  <li><a href="#arma-en-una-línea-qué-son-p-y-q" id="toc-arma-en-una-línea-qué-son-p-y-q" class="nav-link" data-scroll-target="#arma-en-una-línea-qué-son-p-y-q"><span class="header-section-number">15.1</span> ARMA en una línea — qué son <span class="math inline">\(p\)</span> y <span class="math inline">\(q\)</span></a></li>
  <li><a href="#qué-es-un-choque-blanco-varepsilon_t" id="toc-qué-es-un-choque-blanco-varepsilon_t" class="nav-link" data-scroll-target="#qué-es-un-choque-blanco-varepsilon_t"><span class="header-section-number">15.2</span> Qué es un “choque blanco” <span class="math inline">\(\varepsilon_t\)</span></a>
  <ul class="collapse">
  <li><a href="#ejemplos-físicos-para-el-viento-de-la-ventosa" id="toc-ejemplos-físicos-para-el-viento-de-la-ventosa" class="nav-link" data-scroll-target="#ejemplos-físicos-para-el-viento-de-la-ventosa"><span class="header-section-number">15.2.1</span> Ejemplos físicos — para el viento de La Ventosa</a></li>
  <li><a href="#ejemplos-en-otros-contextos-para-ver-que-es-universal" id="toc-ejemplos-en-otros-contextos-para-ver-que-es-universal" class="nav-link" data-scroll-target="#ejemplos-en-otros-contextos-para-ver-que-es-universal"><span class="header-section-number">15.2.2</span> Ejemplos en otros contextos — para ver que es universal</a></li>
  <li><a href="#el-choque-en-ar-vs-ma-mismo-varepsilon_t-distinto-mecanismo-de-transmisión" id="toc-el-choque-en-ar-vs-ma-mismo-varepsilon_t-distinto-mecanismo-de-transmisión" class="nav-link" data-scroll-target="#el-choque-en-ar-vs-ma-mismo-varepsilon_t-distinto-mecanismo-de-transmisión"><span class="header-section-number">15.2.3</span> El choque en AR vs MA — mismo <span class="math inline">\(\varepsilon_t\)</span>, distinto mecanismo de transmisión</a></li>
  <li><a href="#por-qué-importa-para-arma" id="toc-por-qué-importa-para-arma" class="nav-link" data-scroll-target="#por-qué-importa-para-arma"><span class="header-section-number">15.2.4</span> Por qué importa para ARMA</a></li>
  <li><a href="#de-dónde-sale-cada-cosa-no-confundir-orden-con-coeficientes" id="toc-de-dónde-sale-cada-cosa-no-confundir-orden-con-coeficientes" class="nav-link" data-scroll-target="#de-dónde-sale-cada-cosa-no-confundir-orden-con-coeficientes"><span class="header-section-number">15.2.5</span> De dónde sale cada cosa — no confundir orden con coeficientes</a></li>
  </ul></li>
  <li><a href="#el-ciclo-box-jenkins" id="toc-el-ciclo-box-jenkins" class="nav-link" data-scroll-target="#el-ciclo-box-jenkins"><span class="header-section-number">15.3</span> El ciclo Box-Jenkins</a></li>
  <li><a href="#raíz-unitaria-el-concepto-que-prueba-el-adf" id="toc-raíz-unitaria-el-concepto-que-prueba-el-adf" class="nav-link" data-scroll-target="#raíz-unitaria-el-concepto-que-prueba-el-adf"><span class="header-section-number">15.4</span> Raíz unitaria — el concepto que prueba el ADF</a>
  <ul class="collapse">
  <li><a href="#por-qué-phi-1-rompe-todo" id="toc-por-qué-phi-1-rompe-todo" class="nav-link" data-scroll-target="#por-qué-phi-1-rompe-todo"><span class="header-section-number">15.4.1</span> Por qué <span class="math inline">\(\phi = 1\)</span> rompe todo</a></li>
  <li><a href="#truco-algebraico-lo-que-hace-el-adf-por-dentro" id="toc-truco-algebraico-lo-que-hace-el-adf-por-dentro" class="nav-link" data-scroll-target="#truco-algebraico-lo-que-hace-el-adf-por-dentro"><span class="header-section-number">15.4.2</span> Truco algebraico — lo que hace el ADF por dentro</a></li>
  </ul></li>
  <li><a href="#adf-la-serie-es-estacionaria" id="toc-adf-la-serie-es-estacionaria" class="nav-link" data-scroll-target="#adf-la-serie-es-estacionaria"><span class="header-section-number">15.5</span> ADF — ¿la serie es estacionaria?</a></li>
  <li><a href="#acf-autocorrelación" id="toc-acf-autocorrelación" class="nav-link" data-scroll-target="#acf-autocorrelación"><span class="header-section-number">15.6</span> ACF — autocorrelación</a></li>
  <li><a href="#pacf-autocorrelación-parcial" id="toc-pacf-autocorrelación-parcial" class="nav-link" data-scroll-target="#pacf-autocorrelación-parcial"><span class="header-section-number">15.7</span> PACF — autocorrelación parcial</a></li>
  <li><a href="#ljung-box-los-residuales-son-ruido-blanco" id="toc-ljung-box-los-residuales-son-ruido-blanco" class="nav-link" data-scroll-target="#ljung-box-los-residuales-son-ruido-blanco"><span class="header-section-number">15.8</span> Ljung-Box — ¿los residuales son ruido blanco?</a></li>
  <li><a href="#aic-y-bic-comparar-modelos-cuando-varios-pasan-el-diagnóstico" id="toc-aic-y-bic-comparar-modelos-cuando-varios-pasan-el-diagnóstico" class="nav-link" data-scroll-target="#aic-y-bic-comparar-modelos-cuando-varios-pasan-el-diagnóstico"><span class="header-section-number">15.9</span> AIC y BIC — comparar modelos cuando varios pasan el diagnóstico</a></li>
  <li><a href="#helpers-los-dos-pasos-del-ciclo-codificados" id="toc-helpers-los-dos-pasos-del-ciclo-codificados" class="nav-link" data-scroll-target="#helpers-los-dos-pasos-del-ciclo-codificados"><span class="header-section-number">15.10</span> Helpers — los dos pasos del ciclo, codificados</a></li>
  </ul></li>
  <li><a href="#bloque-2-laboratorio-45-min" id="toc-bloque-2-laboratorio-45-min" class="nav-link" data-scroll-target="#bloque-2-laboratorio-45-min"><span class="header-section-number">16</span> Bloque 2 · Laboratorio (45 min)</a>
  <ul class="collapse">
  <li><a href="#p1-los-datos-la-ventosa-oaxaca-5-min" id="toc-p1-los-datos-la-ventosa-oaxaca-5-min" class="nav-link" data-scroll-target="#p1-los-datos-la-ventosa-oaxaca-5-min"><span class="header-section-number">16.1</span> P1 · Los datos · La Ventosa, Oaxaca · 5 min</a></li>
  <li><a href="#p2-podemos-usar-ar-ma-aquí-10-min" id="toc-p2-podemos-usar-ar-ma-aquí-10-min" class="nav-link" data-scroll-target="#p2-podemos-usar-ar-ma-aquí-10-min"><span class="header-section-number">16.2</span> P2 · ¿Podemos usar AR-MA aquí? · 10 min</a>
  <ul class="collapse">
  <li><a href="#confirmación-visual-acf-y-pacf-de-la-serie-cruda" id="toc-confirmación-visual-acf-y-pacf-de-la-serie-cruda" class="nav-link" data-scroll-target="#confirmación-visual-acf-y-pacf-de-la-serie-cruda"><span class="header-section-number">16.2.1</span> Confirmación visual — ACF y PACF de la serie cruda</a></li>
  </ul></li>
  <li><a href="#p3-identificación-5-min" id="toc-p3-identificación-5-min" class="nav-link" data-scroll-target="#p3-identificación-5-min"><span class="header-section-number">16.3</span> P3 · Identificación · 5 min</a></li>
  <li><a href="#p4-iteración-box-jenkins-15-min" id="toc-p4-iteración-box-jenkins-15-min" class="nav-link" data-scroll-target="#p4-iteración-box-jenkins-15-min"><span class="header-section-number">16.4</span> P4 · Iteración Box-Jenkins · 15 min</a>
  <ul class="collapse">
  <li><a href="#iteración-1-ar1" id="toc-iteración-1-ar1" class="nav-link" data-scroll-target="#iteración-1-ar1"><span class="header-section-number">16.4.1</span> Iteración 1 · AR(1)</a></li>
  <li><a href="#iteración-2-ar2" id="toc-iteración-2-ar2" class="nav-link" data-scroll-target="#iteración-2-ar2"><span class="header-section-number">16.4.2</span> Iteración 2 · AR(2)</a></li>
  <li><a href="#iteración-3-arma2-1" id="toc-iteración-3-arma2-1" class="nav-link" data-scroll-target="#iteración-3-arma2-1"><span class="header-section-number">16.4.3</span> Iteración 3 · ARMA(2, 1)</a></li>
  <li><a href="#lectura-visual-fina-en-qué-fijarte-al-mirar-las-tres-figuras" id="toc-lectura-visual-fina-en-qué-fijarte-al-mirar-las-tres-figuras" class="nav-link" data-scroll-target="#lectura-visual-fina-en-qué-fijarte-al-mirar-las-tres-figuras"><span class="header-section-number">16.4.4</span> Lectura visual fina — ¿en qué fijarte al mirar las tres figuras?</a></li>
  <li><a href="#resumen-comparativo" id="toc-resumen-comparativo" class="nav-link" data-scroll-target="#resumen-comparativo"><span class="header-section-number">16.4.5</span> Resumen comparativo</a></li>
  </ul></li>
  <li><a href="#p5-pronóstico-frontera-y-puente-a-sarima-10-min" id="toc-p5-pronóstico-frontera-y-puente-a-sarima-10-min" class="nav-link" data-scroll-target="#p5-pronóstico-frontera-y-puente-a-sarima-10-min"><span class="header-section-number">16.5</span> P5 · Pronóstico, frontera y puente a SARIMA · 10 min</a>
  <ul class="collapse">
  <li><a href="#pronóstico-a-24-h-validación-walk-forward" id="toc-pronóstico-a-24-h-validación-walk-forward" class="nav-link" data-scroll-target="#pronóstico-a-24-h-validación-walk-forward"><span class="header-section-number">16.5.1</span> Pronóstico a 24 h — validación walk-forward</a></li>
  <li><a href="#la-frontera-qué-pasa-si-no-desestacionalizamos" id="toc-la-frontera-qué-pasa-si-no-desestacionalizamos" class="nav-link" data-scroll-target="#la-frontera-qué-pasa-si-no-desestacionalizamos"><span class="header-section-number">16.5.2</span> La frontera · ¿qué pasa si NO desestacionalizamos?</a></li>
  <li><a href="#y-qué-tan-mal-pronostica-walk-forward-del-ar2-crudo" id="toc-y-qué-tan-mal-pronostica-walk-forward-del-ar2-crudo" class="nav-link" data-scroll-target="#y-qué-tan-mal-pronostica-walk-forward-del-ar2-crudo"><span class="header-section-number">16.5.3</span> ¿Y qué tan mal pronostica? Walk-forward del AR(2) crudo</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#cierre-y-materiales-adicionales" id="toc-cierre-y-materiales-adicionales" class="nav-link" data-scroll-target="#cierre-y-materiales-adicionales"><span class="header-section-number">17</span> Cierre y materiales adicionales</a>
  <ul class="collapse">
  <li><a href="#lo-que-te-llevas" id="toc-lo-que-te-llevas" class="nav-link" data-scroll-target="#lo-que-te-llevas"><span class="header-section-number">17.1</span> Lo que te llevas</a></li>
  <li><a href="#ejercicios-para-entregar" id="toc-ejercicios-para-entregar" class="nav-link" data-scroll-target="#ejercicios-para-entregar"><span class="header-section-number">17.2</span> Ejercicios para entregar</a></li>
  <li><a href="#lecturas" id="toc-lecturas" class="nav-link" data-scroll-target="#lecturas"><span class="header-section-number">17.3</span> Lecturas</a></li>
  <li><a href="#apéndice-descarga-del-csv" id="toc-apéndice-descarga-del-csv" class="nav-link" data-scroll-target="#apéndice-descarga-del-csv"><span class="header-section-number">17.4</span> Apéndice · descarga del CSV</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../notebooks/001_birthday_problem.html">Clases</a></li><li class="breadcrumb-item"><a href="../notebooks/014b_LaVentosa.html"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">AR-MA · Laboratorio · La Ventosa, Oaxaca</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">AR-MA · Laboratorio · La Ventosa, Oaxaca</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><strong>Estadística, Detección de Anomalías e Imputación de Series Temporales</strong> Posgrado en Ingeniería · Área Energía · IER-UNAM</p>
<p>Documento <strong>autocontenido</strong>: el Bloque 1 fija conceptos y el Bloque 2 ejecuta el laboratorio completo (45 min).</p>
<section id="setup" class="level2" data-number="14.1">
<h2 data-number="14.1" class="anchored" data-anchor-id="setup"><span class="header-section-number">14.1</span> Setup</h2>
<div id="8d14f4e7" class="cell" data-execution_count="1">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.tsa.arima.model <span class="im">import</span> ARIMA</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.tsa.stattools <span class="im">import</span> adfuller</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.graphics.tsaplots <span class="im">import</span> plot_acf, plot_pacf</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.stats.diagnostic <span class="im">import</span> acorr_ljungbox</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>plt.rcParams[<span class="st">"figure.figsize"</span>] <span class="op">=</span> (<span class="dv">11</span>, <span class="dv">4</span>)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>plt.rcParams[<span class="st">"axes.grid"</span>] <span class="op">=</span> <span class="va">True</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>plt.rcParams[<span class="st">"grid.alpha"</span>] <span class="op">=</span> <span class="fl">0.3</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">42</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="bloque-1-flujo-de-trabajo-y-conceptos-clave" class="level1" data-number="15">
<h1 data-number="15"><span class="header-section-number">15</span> Bloque 1 · Flujo de trabajo y conceptos clave</h1>
<p>Antes de tocar datos, fijamos: (i) qué son los modelos AR/MA/ARMA y de dónde salen <span class="math inline">\(p\)</span> y <span class="math inline">\(q\)</span>, (ii) el ciclo Box-Jenkins, (iii) las cuatro herramientas estadísticas que usaremos toda la sesión (ADF, ACF, PACF, Ljung-Box).</p>
<section id="arma-en-una-línea-qué-son-p-y-q" class="level2" data-number="15.1">
<h2 data-number="15.1" class="anchored" data-anchor-id="arma-en-una-línea-qué-son-p-y-q"><span class="header-section-number">15.1</span> ARMA en una línea — qué son <span class="math inline">\(p\)</span> y <span class="math inline">\(q\)</span></h2>
<p>Trabajamos con tres modelos lineales sobre series <strong>estacionarias</strong>:</p>
<p><strong>AR(p) — autoregresivo de orden <span class="math inline">\(p\)</span>.</strong> El valor actual es combinación lineal de los <span class="math inline">\(p\)</span> valores pasados <em>observados</em> más un choque blanco:</p>
<p><span class="math display">\[y_t \;=\; c + \phi_1\, y_{t-1} + \phi_2\, y_{t-2} + \cdots + \phi_p\, y_{t-p} + \varepsilon_t,
\qquad \varepsilon_t \sim \text{i.i.d.}\,\mathcal{N}(0, \sigma^2).\]</span></p>
<p><em>Intuición física:</em> <strong>inercia</strong>. La serie recuerda sus propios valores recientes.</p>
<p><strong>MA(q) — media móvil de orden <span class="math inline">\(q\)</span>.</strong> El valor actual es combinación lineal de los <span class="math inline">\(q\)</span> choques <em>pasados</em> más el choque actual:</p>
<p><span class="math display">\[y_t \;=\; \mu + \varepsilon_t + \theta_1\, \varepsilon_{t-1} + \theta_2\, \varepsilon_{t-2} + \cdots + \theta_q\, \varepsilon_{t-q}.\]</span></p>
<p><em>Intuición física:</em> <strong>eco de choques</strong>. La serie reverbera durante <span class="math inline">\(q\)</span> pasos cada perturbación, luego olvida.</p>
<p><strong>ARMA(p, q) — la combinación.</strong> Inercia y eco a la vez:</p>
<p><span class="math display">\[y_t \;=\; c + \sum_{i=1}^{p} \phi_i\, y_{t-i} \;+\; \varepsilon_t + \sum_{j=1}^{q} \theta_j\, \varepsilon_{t-j}.\]</span></p>
<p><strong>De ahí salen <span class="math inline">\(p\)</span> y <span class="math inline">\(q\)</span>:</strong></p>
<ul>
<li><span class="math inline">\(p\)</span> = cuántos <strong>rezagos del pasado observado</strong> entran al modelo.</li>
<li><span class="math inline">\(q\)</span> = cuántos <strong>rezagos de innovaciones</strong> (<span class="math inline">\(\varepsilon\)</span>) entran al modelo.</li>
<li>Las <span class="math inline">\(\varepsilon_t\)</span> son <strong>ruido blanco</strong>: media cero, varianza constante, no correlacionadas.</li>
</ul>
<p>Todo el trabajo del laboratorio es: dada una serie, <strong>decidir <span class="math inline">\((p, q)\)</span></strong> y validar que los residuales del modelo ajustado sean indistinguibles de ese ruido blanco.</p>
</section>
<section id="qué-es-un-choque-blanco-varepsilon_t" class="level2" data-number="15.2">
<h2 data-number="15.2" class="anchored" data-anchor-id="qué-es-un-choque-blanco-varepsilon_t"><span class="header-section-number">15.2</span> Qué es un “choque blanco” <span class="math inline">\(\varepsilon_t\)</span></h2>
<p>Un <strong>choque blanco</strong> (o ruido blanco) es una secuencia de perturbaciones <span class="math inline">\(\varepsilon_t\)</span> con tres propiedades:</p>
<ol type="1">
<li><strong>Media cero:</strong> <span class="math inline">\(E[\varepsilon_t] = 0\)</span>. En promedio no empuja la serie hacia arriba ni hacia abajo.</li>
<li><strong>Varianza constante:</strong> <span class="math inline">\(\text{Var}(\varepsilon_t) = \sigma^2\)</span> (homocedasticidad). Todos los choques tienen la misma “talla típica”.</li>
<li><strong>Sin memoria:</strong> <span class="math inline">\(\text{Cov}(\varepsilon_t, \varepsilon_s) = 0\)</span> si <span class="math inline">\(t \neq s\)</span>. Saber el choque de ayer <strong>no</strong> dice nada del choque de hoy.</li>
</ol>
<p>Es la versión matemática de <strong>sorpresa pura</strong>: información nueva, independiente, sin estructura predecible.</p>
<section id="ejemplos-físicos-para-el-viento-de-la-ventosa" class="level3" data-number="15.2.1">
<h3 data-number="15.2.1" class="anchored" data-anchor-id="ejemplos-físicos-para-el-viento-de-la-ventosa"><span class="header-section-number">15.2.1</span> Ejemplos físicos — para el viento de La Ventosa</h3>
<ul>
<li>Una <strong>nube convectiva</strong> pasa y reduce momentáneamente la insolación → cae el contraste térmico Golfo–Pacífico → el viento baja un escalón impredecible.</li>
<li>Un <strong>eddy turbulento</strong> se desprende de un cerro cercano → ráfaga que no tiene memoria del minuto anterior.</li>
<li>Una <strong>perturbación sinóptica débil en altura</strong> que el modelo de mesoescala no capturó y se siente como un pequeño “empujón” sobre la velocidad medida.</li>
<li><strong>Error de medición</strong> del anemómetro (cuantización, vibraciones del mástil). En la práctica este “choque” se mezcla con los anteriores y es indistinguible.</li>
</ul>
</section>
<section id="ejemplos-en-otros-contextos-para-ver-que-es-universal" class="level3" data-number="15.2.2">
<h3 data-number="15.2.2" class="anchored" data-anchor-id="ejemplos-en-otros-contextos-para-ver-que-es-universal"><span class="header-section-number">15.2.2</span> Ejemplos en otros contextos — para ver que es universal</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 26%">
<col style="width: 73%">
</colgroup>
<thead>
<tr class="header">
<th>Sistema</th>
<th>Choque típico <span class="math inline">\(\varepsilon_t\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Precio de una acción</td>
<td>Tweet inesperado, decisión de la Fed, terremoto en Tokio</td>
</tr>
<tr class="even">
<td>Demanda eléctrica</td>
<td>Partido de fútbol no programado, ola de calor súbita</td>
</tr>
<tr class="odd">
<td>Tráfico vehicular</td>
<td>Accidente puntual, semáforo que falla</td>
</tr>
<tr class="even">
<td>Temperatura ambiente</td>
<td>Apertura de una ventana, nube tapando el sol</td>
</tr>
<tr class="odd">
<td>Señal de radio</td>
<td>Interferencia electromagnética aleatoria</td>
</tr>
<tr class="even">
<td>Población de una especie</td>
<td>Brote epidémico, evento de mortalidad masiva, migración fortuita</td>
</tr>
</tbody>
</table>
<p>El patrón común: <strong>eventos individualmente impredecibles, sin estructura temporal entre ellos, que en conjunto generan la variabilidad “irreducible” del sistema</strong>.</p>
<blockquote class="blockquote">
<p><strong>Lo que NO es ruido blanco.</strong> - El <strong>ciclo diario</strong> del viento: es predecible (sale a la misma hora todos los días). - Una <strong>racha multi-día</strong> asociada a un frente frío: tiene memoria (hoy se parece a ayer). - <strong>Tendencia</strong> de calentamiento: empuja sistemáticamente en una dirección.</p>
<p>Todo eso debe estar capturado por el modelo (climatología, AR, MA, tendencia explícita); lo que sobra son los <span class="math inline">\(\varepsilon_t\)</span>.</p>
</blockquote>
</section>
<section id="el-choque-en-ar-vs-ma-mismo-varepsilon_t-distinto-mecanismo-de-transmisión" class="level3" data-number="15.2.3">
<h3 data-number="15.2.3" class="anchored" data-anchor-id="el-choque-en-ar-vs-ma-mismo-varepsilon_t-distinto-mecanismo-de-transmisión"><span class="header-section-number">15.2.3</span> El choque en AR vs MA — mismo <span class="math inline">\(\varepsilon_t\)</span>, distinto mecanismo de transmisión</h3>
<p>El choque blanco es <strong>matemáticamente el mismo</strong> en ambos modelos. Lo que cambia es cómo el sistema físico lo propaga en el tiempo.</p>
<p><strong>En AR — el choque se inyecta en el <em>estado</em>, que tiene inercia.</strong></p>
<p>El valor actual depende de los valores pasados <em>observables</em>. Cuando llega un choque, modifica el estado, y de ahí la dinámica propia (los <span class="math inline">\(\phi_i\)</span>) lo arrastra y lo olvida geométricamente como <span class="math inline">\(\phi^k\)</span>.</p>
<ul>
<li><em>Analogía:</em> habitación climatizada. Abrir una ventana = <span class="math inline">\(\varepsilon_t\)</span>. La temperatura no se recupera al instante porque la pared y el aire tienen capacidad térmica; el ajuste tiene escala de tiempo <span class="math inline">\(\sim 1/(1-\phi)\)</span>.</li>
<li><em>La Ventosa:</em> una célula convectiva reduce el contraste térmico Golfo–Pacífico. El flujo sinóptico <strong>no cambia abruptamente</strong> porque tiene momentum atmosférico — baja un escalón y se recupera con la escala de tiempo del régimen.</li>
</ul>
<p><strong>En MA — el choque tiene vida útil propia, el sistema no lo propaga.</strong></p>
<p>No hay estado interno que arrastre la perturbación; lo que persiste son los <strong>choques mismos</strong> durante <span class="math inline">\(q\)</span> pasos y luego se acaban. Es la respuesta de un filtro de impulso finito (FIR).</p>
<ul>
<li><em>Analogía:</em> sala con reverberación de <span class="math inline">\(q\)</span> segundos. Un golpe se escucha durante <span class="math inline">\(q\)</span> pasos y desaparece sin dejar al sistema modificado.</li>
<li><em>La Ventosa:</em> los efectos MA suelen representar la <strong>inercia del anemómetro</strong> o el <strong>suavizado del muestreo horario</strong> (un evento sub-horario “ringa” en los datos sin alterar el flujo medio), eddies turbulentos de vida corta, o errores de proceso correlacionados (e.g., una nube mal interpolada por el reanálisis durante 2–3 h).</li>
</ul>
<table class="caption-top table">
<colgroup>
<col style="width: 19%">
<col style="width: 40%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th>Aspecto</th>
<th>AR — choque vive en el <strong>estado</strong></th>
<th>MA — choque vive en <strong>memoria de choques</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mecanismo físico</td>
<td>Sistema con inercia / capacitancia interna</td>
<td>Sin estado propio; eco finito</td>
</tr>
<tr class="even">
<td>Duración del efecto</td>
<td>Infinita pero decreciente como <span class="math inline">\(\phi^k\)</span></td>
<td><strong>Exactamente <span class="math inline">\(q\)</span> pasos</strong></td>
</tr>
<tr class="odd">
<td>Ejemplo cotidiano</td>
<td>Termostato, péndulo amortiguado, RLC</td>
<td>Sala reverberante, filtro FIR digital</td>
</tr>
<tr class="even">
<td>En viento</td>
<td>Inercia sinóptica del flujo</td>
<td>Errores de medida, eddies cortos, suavizado</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p><strong>Síntesis.</strong> AR describe un sistema con <strong>dinámica intrínseca</strong> (ecuación diferencial / capacidad de almacenar energía). MA describe un sistema sin dinámica propia que <strong>filtra ruido reciente</strong>. ARMA admite que en la naturaleza casi nada es puro — coexisten inercia del sistema y eco de las perturbaciones recientes.</p>
</blockquote>
</section>
<section id="por-qué-importa-para-arma" class="level3" data-number="15.2.4">
<h3 data-number="15.2.4" class="anchored" data-anchor-id="por-qué-importa-para-arma"><span class="header-section-number">15.2.4</span> Por qué importa para ARMA</h3>
<p>ARMA modela <strong>inercia</strong> (AR) y <strong>eco de choques</strong> (MA), pero el motor que mueve todo es la cadena <span class="math inline">\(\{\varepsilon_t\}\)</span>. Si los choques tuvieran memoria (no fueran blancos), quedaría estructura que el modelo no capturó.</p>
<p>Por eso el chequeo final de Box-Jenkins —<strong>Ljung-Box sobre los residuales</strong>— verifica que los <span class="math inline">\(\hat{\varepsilon}_t = y_t - \hat{y}_t\)</span> se parezcan a ruido blanco. Son la mejor evidencia empírica que tenemos sobre los <span class="math inline">\(\varepsilon_t\)</span> reales del sistema.</p>
</section>
<section id="de-dónde-sale-cada-cosa-no-confundir-orden-con-coeficientes" class="level3" data-number="15.2.5">
<h3 data-number="15.2.5" class="anchored" data-anchor-id="de-dónde-sale-cada-cosa-no-confundir-orden-con-coeficientes"><span class="header-section-number">15.2.5</span> De dónde sale cada cosa — no confundir orden con coeficientes</h3>
<p>ACF y PACF eligen la <strong>arquitectura</strong> del modelo (cuántos parámetros); los valores numéricos de <span class="math inline">\(\phi_i, \theta_j\)</span> los pone el optimizador después.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 17%">
<col style="width: 54%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th>Cosa</th>
<th>De dónde sale</th>
<th>Qué responde</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(p,\, q\)</span></td>
<td>Inspección visual de <strong>ACF/PACF</strong> (dónde cortan o decaen)</td>
<td>¿Cuántos parámetros?</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\phi_i,\, \theta_j\)</span></td>
<td><strong>Estimación por máxima verosimilitud</strong> dentro de <code>ARIMA(...).fit()</code></td>
<td>¿Qué valor toma cada uno?</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\varepsilon_t\)</span></td>
<td><strong>Residuales</strong> del modelo ajustado: <span class="math inline">\(\hat{\varepsilon}_t = y_t - \hat{y}_t\)</span></td>
<td>¿Qué quedó sin explicar?</td>
</tr>
</tbody>
</table>
<p>El flujo es: ACF/PACF → eliges <span class="math inline">\((p, q)\)</span> → <code>ARIMA(serie, order=(p,0,q)).fit()</code> busca los <span class="math inline">\(\phi_i, \theta_j\)</span> que maximizan la verosimilitud → calculas residuales → Ljung-Box dictamina si son blancos.</p>
<blockquote class="blockquote">
<p><strong>Caso especial.</strong> Para un AR(p) puro hay una igualdad exacta: <span class="math inline">\(\text{PACF}(p) = \phi_p\)</span> (el último coeficiente). Por eso PACF “corta” justo en <span class="math inline">\(p\)</span>. Pero <span class="math inline">\(\phi_1, \dots, \phi_{p-1}\)</span> <strong>no</strong> son los valores de PACF en esos lags — son combinaciones no triviales que resuelve la estimación.</p>
</blockquote>
</section>
</section>
<section id="el-ciclo-box-jenkins" class="level2" data-number="15.3">
<h2 data-number="15.3" class="anchored" data-anchor-id="el-ciclo-box-jenkins"><span class="header-section-number">15.3</span> El ciclo Box-Jenkins</h2>
<p>Cuatro pasos, en loop:</p>
<ol type="1">
<li><strong>Identificar.</strong> ¿La serie es estacionaria? ¿Qué orden <span class="math inline">\((p, q)\)</span> probar? Herramientas: <strong>ADF</strong> + <strong>ACF</strong> + <strong>PACF</strong>.</li>
<li><strong>Estimar.</strong> Ajustar <code>ARIMA(p, d, q)</code> por máxima verosimilitud.</li>
<li><strong>Diagnosticar.</strong> ¿Los residuales son ruido blanco? Herramienta: ACF residual + <strong>Ljung-Box</strong>.</li>
<li><strong>Decidir.</strong> Si los residuales NO son blancos → subir orden y volver a 2. Si lo son → parar y pronosticar.</li>
</ol>
<blockquote class="blockquote">
<p><strong>Tip · cómo leer <span class="math inline">\((p, q)\)</span> del par ACF/PACF.</strong> - <strong>PACF corta en lag <span class="math inline">\(p\)</span> y ACF decae</strong> → empezar con <strong>AR(<span class="math inline">\(p\)</span>)</strong>. - <strong>ACF corta en lag <span class="math inline">\(q\)</span> y PACF decae</strong> → empezar con <strong>MA(<span class="math inline">\(q\)</span>)</strong>. - <strong>Ambas decaen</strong> → mezcla <strong>ARMA</strong>; típicamente <span class="math inline">\((p, q) = (1, 1)\)</span> es buen primer disparo. - “Cortar” = el primer lag claramente dentro de la banda <span class="math inline">\(\pm 1.96/\sqrt{n}\)</span>. - En la práctica, lee los <strong>picos significativos</strong> como cota superior del orden y empieza <strong>bajo</strong> (humilde); subir es barato, sobreajustar duele en el diagnóstico.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Lección.</strong> La identificación visual (ACF/PACF) da un <em>punto de partida</em>, no una respuesta única. La prueba final del modelo es Ljung-Box sobre los residuales.</p>
</blockquote>
</section>
<section id="raíz-unitaria-el-concepto-que-prueba-el-adf" class="level2" data-number="15.4">
<h2 data-number="15.4" class="anchored" data-anchor-id="raíz-unitaria-el-concepto-que-prueba-el-adf"><span class="header-section-number">15.4</span> Raíz unitaria — el concepto que prueba el ADF</h2>
<p>Considera un AR(1): <span class="math inline">\(y_t = \phi\, y_{t-1} + \varepsilon_t\)</span>. El comportamiento depende completamente del valor de <span class="math inline">\(\phi\)</span>:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 29%">
<col style="width: 45%">
<col style="width: 24%">
</colgroup>
<thead>
<tr class="header">
<th><span class="math inline">\(\phi\)</span></th>
<th>Comportamiento</th>
<th>Nombre</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\lvert\phi\rvert &lt; 1\)</span></td>
<td>Estacionario, revierte a la media</td>
<td>Estable</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\phi = 1\)</span></td>
<td>Paseo aleatorio, sin reversión</td>
<td><strong>Raíz unitaria</strong></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\lvert\phi\rvert &gt; 1\)</span></td>
<td>Explosivo, varianza diverge</td>
<td>No estacionario</td>
</tr>
</tbody>
</table>
<p>El nombre viene del <strong>polinomio característico</strong> del AR(p): <span class="math inline">\(1 - \phi_1 z - \cdots - \phi_p z^p = 0\)</span>. Si una raíz vale exactamente <span class="math inline">\(z = 1\)</span> → “raíz unitaria”.</p>
<p><strong>Fórmula general.</strong> Para un AR(p), la condición de estacionariedad se lee del polinomio característico:</p>
<p><span class="math display">\[\phi(z) \;=\; 1 - \phi_1\, z - \phi_2\, z^2 - \cdots - \phi_p\, z^p \;=\; 0.\]</span></p>
<ul>
<li>Todas las raíces <span class="math inline">\(\lvert z_i \rvert &gt; 1\)</span> → <strong>estacionario</strong>.</li>
<li>Alguna <span class="math inline">\(\lvert z_i \rvert = 1\)</span> → <strong>raíz unitaria</strong> (no estacionario).</li>
<li>Alguna <span class="math inline">\(\lvert z_i \rvert &lt; 1\)</span> → <strong>explosivo</strong>.</li>
</ul>
<p><strong>Ejemplo con valores — AR(2) con raíz unitaria.</strong> Considera</p>
<p><span class="math display">\[y_t \;=\; 1.5\, y_{t-1} \;-\; 0.5\, y_{t-2} \;+\; \varepsilon_t.\]</span></p>
<p>Aquí <span class="math inline">\(\phi_1 = 1.5\)</span> y <span class="math inline">\(\phi_2 = -0.5\)</span>, así que el polinomio queda</p>
<p><span class="math display">\[1 - 1.5\, z + 0.5\, z^2 \;=\; 0.\]</span></p>
<p><strong>Despeje.</strong> Factorizamos directamente (o aplicamos la fórmula cuadrática):</p>
<p><span class="math display">\[1 - 1.5\, z + 0.5\, z^2 \;=\; (1 - z)\,(1 - 0.5\, z).\]</span></p>
<p>Las raíces son entonces</p>
<p><span class="math display">\[z_1 = 1 \quad (\text{raíz unitaria}), \qquad z_2 = 2.\]</span></p>
<p>La presencia de <span class="math inline">\(z_1 = 1\)</span> confirma que el proceso <strong>no es estacionario</strong>. De hecho, si tomamos la primera diferencia <span class="math inline">\(\Delta y_t = y_t - y_{t-1}\)</span>, el resultado sí lo es:</p>
<p><span class="math display">\[\Delta y_t \;=\; 0.5\, \Delta y_{t-1} \;+\; \varepsilon_t,\]</span></p>
<p>un AR(1) estable (la otra raíz, <span class="math inline">\(z_2 = 2\)</span>, sobrevive). El AR(2) original equivale a un <strong>ARIMA(1, 1, 0)</strong> sobre la serie cruda — el “1” central es justamente el orden de diferenciación necesario para eliminar la raíz unitaria.</p>
<blockquote class="blockquote">
<p><strong>Conexión con el ADF.</strong> El ADF prueba exactamente esto: si el AR ajustado a tus datos tiene una raíz en <span class="math inline">\(z = 1\)</span>. Cuando rechaza <span class="math inline">\(H_0\)</span>, no hace falta diferenciar. Cuando no rechaza, conviene aplicar <span class="math inline">\(\Delta\)</span> y reintentar sobre la diferencia.</p>
</blockquote>
<section id="por-qué-phi-1-rompe-todo" class="level3" data-number="15.4.1">
<h3 data-number="15.4.1" class="anchored" data-anchor-id="por-qué-phi-1-rompe-todo"><span class="header-section-number">15.4.1</span> Por qué <span class="math inline">\(\phi = 1\)</span> rompe todo</h3>
<p>Si <span class="math inline">\(y_t = y_{t-1} + \varepsilon_t\)</span>, resolviendo recursivamente desde <span class="math inline">\(y_0\)</span>:</p>
<p><span class="math display">\[y_t = y_0 + \sum_{i=1}^{t} \varepsilon_i.\]</span></p>
<ul>
<li><strong>Varianza explota:</strong> <span class="math inline">\(\text{Var}(y_t) = t\sigma^2\)</span> → crece linealmente.</li>
<li><strong>Choques permanentes:</strong> cada <span class="math inline">\(\varepsilon_i\)</span> se queda en el nivel para siempre (entra con coeficiente 1 en la suma).</li>
<li><strong>No hay media a la cual revertir:</strong> <span class="math inline">\(E[y_t \mid y_0] = y_0\)</span>, depende de dónde arrancaste.</li>
</ul>
<p>Si <span class="math inline">\(|\phi| &lt; 1\)</span>, en cambio, los choques decaen como <span class="math inline">\(\phi^k\)</span> → la serie <em>olvida</em> el pasado y oscila alrededor de una media fija.</p>
</section>
<section id="truco-algebraico-lo-que-hace-el-adf-por-dentro" class="level3" data-number="15.4.2">
<h3 data-number="15.4.2" class="anchored" data-anchor-id="truco-algebraico-lo-que-hace-el-adf-por-dentro"><span class="header-section-number">15.4.2</span> Truco algebraico — lo que hace el ADF por dentro</h3>
<p>Resta <span class="math inline">\(y_{t-1}\)</span> en ambos lados de <span class="math inline">\(y_t = \phi\, y_{t-1} + \varepsilon_t\)</span>:</p>
<p><span class="math display">\[\Delta y_t = (\phi - 1)\, y_{t-1} + \varepsilon_t = \gamma\, y_{t-1} + \varepsilon_t,
\qquad \gamma \equiv \phi - 1.\]</span></p>
<p>Entonces:</p>
<ul>
<li><span class="math inline">\(\phi = 1 \iff \gamma = 0\)</span> → <strong>raíz unitaria</strong>.</li>
<li><span class="math inline">\(\phi &lt; 1 \iff \gamma &lt; 0\)</span> → <strong>estacionaria</strong>.</li>
</ul>
<p>El ADF estima <span class="math inline">\(\gamma\)</span> por MCO y prueba <span class="math inline">\(H_0: \gamma = 0\)</span>. Por eso la hipótesis nula es “hay raíz unitaria” — el caso <span class="math inline">\(\gamma = 0\)</span> es la frontera.</p>
<blockquote class="blockquote">
<p><strong>Ejemplos físicos.</strong> - <strong>Con raíz unitaria:</strong> precio de una acción (cada noticia se incorpora al nivel permanentemente), nivel del mar acumulado, posición de una partícula browniana. - <strong>Sin raíz unitaria:</strong> temperatura diaria de una ciudad (revierte a climatología), velocidad del viento en escala sinóptica, oscilaciones cerca de un equilibrio.</p>
<p>En La Ventosa esperamos <strong>no raíz unitaria</strong> — el viento no diverge, fluctúa en un rango acotado por la física. El ADF lo confirmará con <span class="math inline">\(p \approx 0\)</span>.</p>
</blockquote>
</section>
</section>
<section id="adf-la-serie-es-estacionaria" class="level2" data-number="15.5">
<h2 data-number="15.5" class="anchored" data-anchor-id="adf-la-serie-es-estacionaria"><span class="header-section-number">15.5</span> ADF — ¿la serie es estacionaria?</h2>
<p><strong>Augmented Dickey-Fuller.</strong> Versión aumentada del truco anterior: añade intercepto, tendencia y <span class="math inline">\(k\)</span> rezagos de <span class="math inline">\(\Delta y_t\)</span> para manejar series reales. Se ajusta</p>
<p><span class="math display">\[\Delta y_t \;=\; \alpha + \beta\, t + \gamma\, y_{t-1} + \sum_{i=1}^{k} \delta_i\, \Delta y_{t-i} + \varepsilon_t,\]</span></p>
<p>y se contrasta el coeficiente <span class="math inline">\(\gamma\)</span> con el estadístico <span class="math inline">\(\hat{\gamma}/\text{SE}(\hat{\gamma})\)</span> (distribución no-estándar, tabulada por Dickey-Fuller — no es una <span class="math inline">\(t\)</span> de Student porque <span class="math inline">\(y_{t-1}\)</span> es no estacionaria bajo <span class="math inline">\(H_0\)</span>).</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\gamma = 0\)</span> → la serie tiene <strong>raíz unitaria</strong> → <strong>NO estacionaria</strong> (paseo aleatorio).</li>
<li><span class="math inline">\(H_1\)</span>: <span class="math inline">\(\gamma &lt; 0\)</span> → la serie es <strong>estacionaria</strong>.</li>
<li>Regla: <span class="math inline">\(p &lt; 0.05\)</span> → rechazas <span class="math inline">\(H_0\)</span> → asumes estacionariedad.</li>
</ul>
<p>El término <em>augmented</em> viene de los <span class="math inline">\(k\)</span> rezagos <span class="math inline">\(\Delta y_{t-i}\)</span>, que absorben autocorrelación residual; sin ellos sería el test de Dickey-Fuller original. La opción <code>autolag="AIC"</code> que pasamos a <code>adfuller()</code> selecciona <span class="math inline">\(k\)</span> automáticamente.</p>
<p><strong>Cuidado.</strong> ADF certifica una condición <strong>necesaria pero no suficiente</strong> para ARMA: una serie con ciclo <strong>estacional puro</strong> puede pasar el ADF y aún violar los supuestos.</p>
<p>Por <em>estacional puro</em> entendemos una componente <strong>periódica determinista</strong> de período fijo <span class="math inline">\(s\)</span> sobre ruido blanco — es decir, un patrón cíclico que <strong>se repite exactamente igual</strong> cada <span class="math inline">\(s\)</span> pasos, ensuciado solo por choques independientes. Forma general:</p>
<p><span class="math display">\[y_t \;=\; A\, \sin\!\left(\tfrac{2\pi t}{s}\right) + \varepsilon_t, \qquad \varepsilon_t \sim \text{ruido blanco}.\]</span></p>
<p><strong>Ejemplo concreto.</strong> Temperatura horaria de una ciudad en una semana climática estable, generada artificialmente como</p>
<p><span class="math display">\[T_t \;=\; 20 \;+\; 5\, \cos\!\left(\tfrac{2\pi\, t}{24}\right) \;+\; \varepsilon_t,
\qquad \varepsilon_t \sim \mathcal{N}(0,\, 1^2).\]</span></p>
<ul>
<li><strong>Nivel medio:</strong> <span class="math inline">\(20\,°\text{C}\)</span>, constante en el tiempo.</li>
<li><strong>Amplitud diaria:</strong> <span class="math inline">\(5\,°\text{C}\)</span> (máximo al mediodía, mínimo a medianoche).</li>
<li><strong>Período:</strong> <span class="math inline">\(s = 24\)</span> h, exacto.</li>
<li><strong>Ruido:</strong> desviación típica <span class="math inline">\(1\,°\text{C}\)</span>, independiente entre horas.</li>
</ul>
<p>Si corres <code>adfuller(T)</code> sobre esta serie, el ADF rechaza <span class="math inline">\(H_0\)</span> con <span class="math inline">\(p \approx 0\)</span>: <em>“estacionaria”</em>. Y formalmente lo es: la media de largo plazo y la varianza son constantes (no hay raíz unitaria, no hay tendencia).</p>
<p><strong>Pero</strong> si ajustas un ARMA cualquiera a <span class="math inline">\(T_t\)</span> y miras la ACF de los residuales, vas a ver <strong>picos persistentes en lags 24, 48, 72, …</strong> El motivo es estructural:</p>
<ul>
<li>Un coseno tiene autocorrelación que se <strong>repite idéntica</strong> cada <span class="math inline">\(s\)</span> lags, sin decaer.</li>
<li>ARMA solo puede generar correlaciones que <strong>decaen geométricamente</strong>.</li>
<li>Conclusión: ARMA no puede absorber un ciclo determinista; le queda estructura periódica íntegra en los residuales y Ljung-Box la detecta.</li>
</ul>
<p><strong>Cómo se arregla.</strong> Dos caminos:</p>
<ul>
<li><strong>Restar la estacionalidad determinista.</strong> Estimas la “media por hora del día” (climatología horaria <span class="math inline">\(\bar{T}(h)\)</span>) y modelas la anomalía <span class="math inline">\(T_t - \bar{T}(h)\)</span>. <em>Esto es exactamente lo que haremos con el viento en P2.</em></li>
<li><strong>Usar SARIMA <span class="math inline">\((p,d,q)(P,D,Q)_{s}\)</span>.</strong> El componente estacional con período <span class="math inline">\(s = 24\)</span> absorbe el ciclo dentro del modelo, sin necesidad de restar.</li>
</ul>
<p>Por eso, antes de cualquier ARMA, siempre inspeccionamos ACF y climatología: si vemos picos a múltiplos de <span class="math inline">\(s\)</span>, sabemos que hay estacionalidad pendiente.</p>
</section>
<section id="acf-autocorrelación" class="level2" data-number="15.6">
<h2 data-number="15.6" class="anchored" data-anchor-id="acf-autocorrelación"><span class="header-section-number">15.6</span> ACF — autocorrelación</h2>
<p><span class="math inline">\(\text{ACF}(k) = \text{corr}(y_t,\, y_{t-k})\)</span>. Correlación de la serie consigo misma desfasada <span class="math inline">\(k\)</span> pasos. Mezcla efectos directos e indirectos (el lag 2 “ve” al lag 1).</p>
<ul>
<li><strong>AR(p):</strong> ACF decae geométrica o sinusoidalmente — no corta abrupto.</li>
<li><strong>MA(q):</strong> ACF <strong>corta</strong> después del lag <span class="math inline">\(q\)</span>.</li>
<li><strong>Banda de confianza:</strong> <span class="math inline">\(\pm 1.96/\sqrt{n}\)</span>. Picos dentro de la banda son ruido.</li>
</ul>
</section>
<section id="pacf-autocorrelación-parcial" class="level2" data-number="15.7">
<h2 data-number="15.7" class="anchored" data-anchor-id="pacf-autocorrelación-parcial"><span class="header-section-number">15.7</span> PACF — autocorrelación parcial</h2>
<p><span class="math inline">\(\text{PACF}(k)\)</span>: correlación entre <span class="math inline">\(y_t\)</span> y <span class="math inline">\(y_{t-k}\)</span> <strong>después de remover</strong> el efecto de los lags intermedios <span class="math inline">\(y_{t-1}, \dots, y_{t-k+1}\)</span>. Aísla el efecto directo del lag <span class="math inline">\(k\)</span>.</p>
<ul>
<li><strong>AR(p):</strong> PACF <strong>corta</strong> después del lag <span class="math inline">\(p\)</span> → así identificamos <span class="math inline">\(p\)</span>.</li>
<li><strong>MA(q):</strong> PACF decae geométricamente.</li>
</ul>
<p><strong>Tabla mnemónica.</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Modelo</th>
<th>ACF</th>
<th>PACF</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>AR(p)</td>
<td>decae</td>
<td>corta en <span class="math inline">\(p\)</span></td>
</tr>
<tr class="even">
<td>MA(q)</td>
<td>corta en <span class="math inline">\(q\)</span></td>
<td>decae</td>
</tr>
<tr class="odd">
<td>ARMA</td>
<td>decae</td>
<td>decae</td>
</tr>
</tbody>
</table>
</section>
<section id="ljung-box-los-residuales-son-ruido-blanco" class="level2" data-number="15.8">
<h2 data-number="15.8" class="anchored" data-anchor-id="ljung-box-los-residuales-son-ruido-blanco"><span class="header-section-number">15.8</span> Ljung-Box — ¿los residuales son ruido blanco?</h2>
<p><strong>Residual = lo que el modelo no explicó.</strong> Una vez ajustado un ARMA, el modelo produce un pronóstico un paso adelante <span class="math inline">\(\hat{y}_t\)</span> para cada instante. El <strong>residual</strong> es la diferencia entre el dato real y ese pronóstico:</p>
<p><span class="math display">\[\hat{\varepsilon}_t \;=\; y_t \,-\, \hat{y}_t.\]</span></p>
<p>Son la estimación empírica de los choques blancos <span class="math inline">\(\varepsilon_t\)</span> del modelo. <strong>Si el modelo es adecuado</strong>, los residuales deben verse como ruido blanco: media cero, varianza constante, <strong>sin autocorrelación</strong>. Si todavía tienen estructura (picos en ACF, correlación lag-a-lag, etc.) → el modelo dejó algo sobre la mesa y hay que subir orden o cambiar de familia.</p>
<p>Ljung-Box es la <strong>prueba formal de blancura</strong> sobre esos residuales — combina muchos lags en un solo <span class="math inline">\(p\)</span>-value para no depender de inspección visual.</p>
<p><strong>Estadístico.</strong> Prueba conjunta de autocorrelación sobre los primeros <span class="math inline">\(h\)</span> lags de <span class="math inline">\(\hat{\varepsilon}_t\)</span>:</p>
<p><span class="math display">\[Q_{LB}(h) = n(n+2) \sum_{k=1}^{h} \frac{\hat{\rho}_k^2}{n - k} \;\sim\; \chi^2_{h - p - q},\]</span></p>
<p>donde <span class="math inline">\(\hat{\rho}_k\)</span> es la autocorrelación muestral del residual al lag <span class="math inline">\(k\)</span> y los grados de libertad descuentan los <span class="math inline">\(p + q\)</span> parámetros estimados (ajuste de Box-Pierce).</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: las primeras <span class="math inline">\(h\)</span> autocorrelaciones son <strong>todas cero</strong> → residuales blancos.</li>
<li><span class="math inline">\(H_1\)</span>: al menos una es distinta de cero → queda estructura sin modelar.</li>
<li>Regla: <span class="math inline">\(p &gt; 0.05\)</span> → <strong>NO rechazas</strong> → modelo adecuado.</li>
</ul>
<p><strong>Por qué importa.</strong> Si los residuales tienen autocorrelación, los intervalos de confianza del pronóstico están <strong>subestimados</strong> — el modelo miente sobre su propia incertidumbre. Es el chequeo no negociable de Box-Jenkins.</p>
<p><strong>Por qué miramos a 10 y 20 lags</strong> (en datos horarios): 10 ≈ media jornada, 20 ≈ día completo. Si queda autocorrelación a esos horizontes, el pronóstico de corto plazo será sesgado.</p>
</section>
<section id="aic-y-bic-comparar-modelos-cuando-varios-pasan-el-diagnóstico" class="level2" data-number="15.9">
<h2 data-number="15.9" class="anchored" data-anchor-id="aic-y-bic-comparar-modelos-cuando-varios-pasan-el-diagnóstico"><span class="header-section-number">15.9</span> AIC y BIC — comparar modelos cuando varios pasan el diagnóstico</h2>
<p>Ljung-Box dice si un modelo es <strong>adecuado</strong> (residuales blancos: sí/no), pero a menudo <strong>varios</strong> órdenes lo pasan. ¿Cuál eliges? Aquí entra el criterio cuantitativo estándar: el <strong>AIC</strong> (Akaike Information Criterion).</p>
<p><span class="math display">\[\text{AIC} \;=\; -2\, \log L_{\max} \;+\; 2k,\]</span></p>
<p>donde <span class="math inline">\(L_{\max}\)</span> es la verosimilitud máxima del MLE y <span class="math inline">\(k\)</span> es el número de parámetros estimados.</p>
<p><strong>Lectura: menor es mejor.</strong></p>
<ul>
<li><span class="math inline">\(-2\log L_{\max}\)</span> → <strong>premia el ajuste</strong>: más verosimilitud → AIC más bajo.</li>
<li><span class="math inline">\(+2k\)</span> → <strong>penaliza la complejidad</strong>: cada parámetro extra cuesta 2 puntos de AIC.</li>
<li>Un parámetro adicional solo “vale la pena” si reduce <span class="math inline">\(-2\log L\)</span> en <strong>más de 2</strong>.</li>
</ul>
<p><strong>Reglas para compararlo:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 34%">
<col style="width: 66%">
</colgroup>
<thead>
<tr class="header">
<th>Regla</th>
<th>Aclaración</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Valores absolutos: irrelevantes</td>
<td>Solo comparas dos AIC entre <strong>modelos sobre la misma serie</strong>.</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\Delta\text{AIC} &gt; 2\)</span></td>
<td>Diferencia <strong>significativa</strong>.</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\Delta\text{AIC} &gt; 10\)</span></td>
<td>Diferencia <strong>decisiva</strong> — el modelo con menor AIC gana sin duda.</td>
</tr>
</tbody>
</table>
<p><strong>BIC (Bayesian Information Criterion)</strong> es la prima conservadora:</p>
<p><span class="math display">\[\text{BIC} \;=\; -2\, \log L_{\max} \;+\; k\, \log n,\]</span></p>
<p>donde <span class="math inline">\(n\)</span> es el número de observaciones. Penaliza la complejidad más fuerte cuando <span class="math inline">\(n\)</span> es grande (<span class="math inline">\(\log n &gt; 2\)</span> apenas <span class="math inline">\(n &gt; 8\)</span>), así que tiende a <strong>preferir modelos más simples</strong> que AIC. <code>statsmodels</code> imprime ambos en <code>summary()</code>.</p>
<blockquote class="blockquote">
<p><strong>Lectura combinada con Ljung-Box.</strong> Ljung-Box dice <em>“¿este modelo es adecuado?”</em> (sí/no). AIC/BIC dicen <em>“entre los adecuados, ¿cuál es mejor?”</em> (ranking). Son complementarios: <strong>nunca</strong> elijas un modelo por AIC bajo si Ljung-Box rechaza — sería un ajuste vacío. Y si dos modelos pasan Ljung-Box con AIC parecido, gana el más simple (parsimonia).</p>
</blockquote>
<p>En P4 vamos a ver esto en vivo: la columna AIC bajará de 3814 (AR(1)) → 3804 (AR(2)) → 3769 (ARMA(2,1)), con saltos <span class="math inline">\(&gt; 10\)</span> → mejoras decisivas en cada iteración.</p>
</section>
<section id="helpers-los-dos-pasos-del-ciclo-codificados" class="level2" data-number="15.10">
<h2 data-number="15.10" class="anchored" data-anchor-id="helpers-los-dos-pasos-del-ciclo-codificados"><span class="header-section-number">15.10</span> Helpers — los dos pasos del ciclo, codificados</h2>
<ul>
<li><code>mirar()</code>: identificación (ADF + ACF + PACF).</li>
<li><code>diagnostico()</code>: validación (residuales + ACF residual + Ljung-Box).</li>
</ul>
<div id="223a1644" class="cell" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> mirar(serie, nombre, lags<span class="op">=</span><span class="dv">30</span>):</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Identificación: serie temporal + ADF + ACF + PACF."""</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>    serie <span class="op">=</span> pd.Series(serie).dropna()</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    stat, p, <span class="op">*</span>_ <span class="op">=</span> adfuller(serie, autolag<span class="op">=</span><span class="st">"AIC"</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    veredicto <span class="op">=</span> <span class="st">"estacionaria"</span> <span class="cf">if</span> p <span class="op">&lt;</span> <span class="fl">0.05</span> <span class="cf">else</span> <span class="st">"NO estacionaria"</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"ADF · </span><span class="sc">{</span>nombre<span class="sc">}</span><span class="ss">:  estadístico = </span><span class="sc">{</span>stat<span class="sc">:.3f}</span><span class="ss">,  p = </span><span class="sc">{</span>p<span class="sc">:.4f}</span><span class="ss">  →  </span><span class="sc">{</span>veredicto<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>    fig, axes <span class="op">=</span> plt.subplot_mosaic(</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>        [[<span class="st">"serie"</span>, <span class="st">"serie"</span>],</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>         [<span class="st">"acf"</span>,   <span class="st">"pacf"</span>]],</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>        figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">6</span>),</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>    serie.plot(ax<span class="op">=</span>axes[<span class="st">"serie"</span>], lw<span class="op">=</span><span class="fl">0.5</span>, color<span class="op">=</span><span class="st">"C0"</span>)</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>    axes[<span class="st">"serie"</span>].axhline(serie.mean(), color<span class="op">=</span><span class="st">"k"</span>, lw<span class="op">=</span><span class="fl">0.5</span>, alpha<span class="op">=</span><span class="fl">0.5</span>)</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>    axes[<span class="st">"serie"</span>].set_title(<span class="ss">f"Serie — </span><span class="sc">{</span>nombre<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>    plot_acf(serie,  lags<span class="op">=</span>lags, ax<span class="op">=</span>axes[<span class="st">"acf"</span>])<span class="op">;</span>  axes[<span class="st">"acf"</span>].set_title(<span class="ss">f"ACF — </span><span class="sc">{</span>nombre<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>    plot_pacf(serie, lags<span class="op">=</span>lags, ax<span class="op">=</span>axes[<span class="st">"pacf"</span>], method<span class="op">=</span><span class="st">"ywm"</span>)</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>    axes[<span class="st">"pacf"</span>].set_title(<span class="ss">f"PACF — </span><span class="sc">{</span>nombre<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>    plt.tight_layout()<span class="op">;</span> plt.show()</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> diagnostico(modelo, nombre, lags<span class="op">=</span><span class="dv">20</span>):</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Validación: residuales + ACF residual + PACF residual + Ljung-Box."""</span></span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>    p, d, q <span class="op">=</span> modelo.model.order</span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a>    resid <span class="op">=</span> modelo.resid.iloc[<span class="bu">max</span>(p, q):]</span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a>    fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">3</span>, figsize<span class="op">=</span>(<span class="dv">15</span>, <span class="fl">3.2</span>))</span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a>    axes[<span class="dv">0</span>].plot(resid.values, lw<span class="op">=</span><span class="fl">0.6</span>)<span class="op">;</span> axes[<span class="dv">0</span>].axhline(<span class="dv">0</span>, color<span class="op">=</span><span class="st">"k"</span>, lw<span class="op">=</span><span class="fl">0.5</span>)</span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a>    axes[<span class="dv">0</span>].set_title(<span class="ss">f"Residuales — </span><span class="sc">{</span>nombre<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a>    plot_acf(resid,  lags<span class="op">=</span>lags, ax<span class="op">=</span>axes[<span class="dv">1</span>])<span class="op">;</span> axes[<span class="dv">1</span>].set_title(<span class="st">"ACF de residuales"</span>)</span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a>    plot_pacf(resid, lags<span class="op">=</span>lags, ax<span class="op">=</span>axes[<span class="dv">2</span>], method<span class="op">=</span><span class="st">"ywm"</span>)</span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a>    axes[<span class="dv">2</span>].set_title(<span class="st">"PACF de residuales"</span>)</span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a>    plt.tight_layout()<span class="op">;</span> plt.show()</span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-36"><a href="#cb2-36" aria-hidden="true" tabindex="-1"></a>    lb <span class="op">=</span> acorr_ljungbox(resid, lags<span class="op">=</span>[<span class="dv">10</span>, <span class="dv">20</span>], return_df<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb2-37"><a href="#cb2-37" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"Ljung-Box · </span><span class="sc">{</span>nombre<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb2-38"><a href="#cb2-38" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(lb.<span class="bu">round</span>(<span class="dv">4</span>))</span>
<span id="cb2-39"><a href="#cb2-39" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> lb</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
</section>
<section id="bloque-2-laboratorio-45-min" class="level1" data-number="16">
<h1 data-number="16"><span class="header-section-number">16</span> Bloque 2 · Laboratorio (45 min)</h1>
<section id="p1-los-datos-la-ventosa-oaxaca-5-min" class="level2" data-number="16.1">
<h2 data-number="16.1" class="anchored" data-anchor-id="p1-los-datos-la-ventosa-oaxaca-5-min"><span class="header-section-number">16.1</span> P1 · Los datos · La Ventosa, Oaxaca · 5 min</h2>
<ul>
<li><strong>Sitio:</strong> 16.55°N, 94.78°W. Corredor eólico del Istmo de Tehuantepec, uno de los mayores recursos eólicos del continente. Vientos térmicos por contraste de presión entre el Golfo de México y el Pacífico, canalizados por el istmo.</li>
<li><strong>Periodo:</strong> jun–ago 2023, resolución horaria.</li>
<li><strong>Variable:</strong> velocidad del viento a 10 m.</li>
<li><strong>Fuente:</strong> ERA5 (reanálisis ECMWF) vía Open-Meteo.</li>
</ul>
<p><strong>Por qué este dataset para enseñar ARMA:</strong> - ~2200 obs → potencia estadística suficiente. - Ciclo diario explícito → enseña por qué hay que desestacionalizar antes. - Persistencia no trivial → forzará iterar Box-Jenkins (no se cierra al primer intento). - Relevante para el alumno (energía eólica).</p>
<div id="e9672a64" class="cell" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>viento <span class="op">=</span> pd.read_csv(<span class="st">"../data/viento_la_ventosa_2023.csv"</span>,</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>                     skiprows<span class="op">=</span><span class="dv">3</span>, parse_dates<span class="op">=</span>[<span class="st">"time"</span>],</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>                     index_col<span class="op">=</span><span class="st">"time"</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>viento.columns <span class="op">=</span> [<span class="st">"ws_kmh"</span>]</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>viento[<span class="st">"ws"</span>] <span class="op">=</span> viento[<span class="st">"ws_kmh"</span>] <span class="op">/</span> <span class="fl">3.6</span>  <span class="co"># km/h → m/s</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>viento <span class="op">=</span> viento[<span class="st">"ws"</span>]</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="bu">len</span>(viento)<span class="sc">}</span><span class="ss"> obs horarias · </span><span class="sc">{</span>viento<span class="sc">.</span>index<span class="sc">.</span><span class="bu">min</span>()<span class="sc">}</span><span class="ss"> a </span><span class="sc">{</span>viento<span class="sc">.</span>index<span class="sc">.</span><span class="bu">max</span>()<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"media = </span><span class="sc">{</span>viento<span class="sc">.</span>mean()<span class="sc">:.2f}</span><span class="ss"> m/s"</span>)</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"desv  = </span><span class="sc">{</span>viento<span class="sc">.</span>std()<span class="sc">:.2f}</span><span class="ss"> m/s"</span>)</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"máx   = </span><span class="sc">{</span>viento<span class="sc">.</span><span class="bu">max</span>()<span class="sc">:.2f}</span><span class="ss"> m/s"</span>)</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>viento.plot(lw<span class="op">=</span><span class="fl">0.5</span>, color<span class="op">=</span><span class="st">"C2"</span>, title<span class="op">=</span><span class="st">"Viento 10 m · La Ventosa, jun–ago 2023"</span>)</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"m/s"</span>)<span class="op">;</span> plt.tight_layout()<span class="op">;</span> plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>2208 obs horarias · 2023-06-01 00:00:00 a 2023-08-31 23:00:00
media = 4.14 m/s
desv  = 2.37 m/s
máx   = 9.36 m/s</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="014b_LaVentosa_files/figure-html/cell-4-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>Lectura a ojo.</strong> Hay rachas multi-día (escala sinóptica) y un latido de alta frecuencia que sugiere ciclo diario. Antes de tocar ARMA hay que verificar dos cosas: (1) estacionariedad y (2) ausencia de estacionalidad determinista que se vaya a colar a los residuales.</p>
<blockquote class="blockquote">
<p><strong>Para discutir con la clase.</strong> - ¿Qué <strong>otras variables físicas</strong> querrían medir para mejorar el pronóstico? (Presión, temperatura, gradiente térmico Golfo-Pacífico, índices climáticos como ENSO). Anticipa el puente a SARIMAX/exógenas. - ¿Por qué viento a 10 m y no a altura de buje (~80 m)? (10 m es lo que da ERA5 con calidad estándar; para producción real se extrapola con perfil logarítmico o se usan productos a 100 m. Con esta serie aprendemos <em>método</em>, no <em>operación</em>). - ¿Qué tan representativo es jun–ago de todo el año? (Mala. Es temporada de máximos en La Ventosa — invierno tiene un régimen distinto. Lo veremos como ejercicio).</p>
</blockquote>
</section>
<section id="p2-podemos-usar-ar-ma-aquí-10-min" class="level2" data-number="16.2">
<h2 data-number="16.2" class="anchored" data-anchor-id="p2-podemos-usar-ar-ma-aquí-10-min"><span class="header-section-number">16.2</span> P2 · ¿Podemos usar AR-MA aquí? · 10 min</h2>
<div id="e909c3f8" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>stat, p, <span class="op">*</span>_ <span class="op">=</span> adfuller(viento, autolag<span class="op">=</span><span class="st">"AIC"</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"ADF sobre serie cruda:  p = </span><span class="sc">{</span>p<span class="sc">:.4f}</span><span class="ss">  →  "</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"</span><span class="sc">{</span><span class="st">'estacionaria'</span> <span class="cf">if</span> p <span class="op">&lt;</span> <span class="fl">0.05</span> <span class="cf">else</span> <span class="st">'NO estacionaria'</span><span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>ADF sobre serie cruda:  p = 0.0668  →  NO estacionaria</code></pre>
</div>
</div>
<p><strong>¿Y si el ADF dice “NO estacionaria”?</strong> Es lo más probable en estos datos — y la razón <strong>no es</strong> que el viento tenga raíz unitaria. ADF solo prueba un mecanismo específico (paseo aleatorio), y cuando hay otra fuente fuerte de persistencia el test puede confundirse. Tres causas posibles para un “NO estacionaria”:</p>
<ol type="1">
<li><strong>Raíz unitaria genuina:</strong> el proceso es realmente un paseo aleatorio.</li>
<li><strong>Tendencia determinista:</strong> la serie sube/baja sistemáticamente.</li>
<li><strong>Estacionalidad determinista fuerte:</strong> un ciclo periódico que crea persistencia aparente entre observaciones y empuja al test hacia el rechazo de estacionariedad.</li>
</ol>
<p>Para el viento horario jun–ago, <strong>la causa #3 es la dominante</strong>: el ciclo diario satura la correlación temporal y el ADF, que no tiene mecanismo para descomponer la señal, lo lee como falta de estacionariedad.</p>
<p>Si el ADF hubiera dicho “estacionaria”, el problema sería <strong>simétrico</strong>: nos habría dado falsa tranquilidad, ocultando el mismo ciclo diario que ARMA no puede modelar.</p>
<p><strong>Conclusión, sea cual sea el veredicto del ADF:</strong> hay que diagnosticar visualmente. Verifiquemos el ciclo diario explícitamente con ACF/PACF y climatología.</p>
<blockquote class="blockquote">
<p><strong>Error común que aquí se vuelve operativo.</strong> Hay dos versiones simétricas, según qué diga el ADF:</p>
<ul>
<li><strong>“ADF dice estacionaria → puedo ajustar ARMA.”</strong> Falso si hay estacionalidad determinista: el ciclo se filtrará íntegro a los residuales.</li>
<li><strong>“ADF dice NO estacionaria → debo diferenciar (ARIMA con <span class="math inline">\(d \geq 1\)</span>).”</strong> Falso si la causa es estacionalidad: diferenciar <strong>no cura ciclos deterministas</strong>, solo raíces unitarias. Acabarías con un modelo sobre-integrado y el ciclo intacto.</li>
</ul>
<p>ADF certifica/refuta una propiedad necesaria, pero <strong>no suficiente</strong> ni <strong>específica</strong>. La prueba final del modelo no es ADF sobre los datos — es Ljung-Box sobre los residuales.</p>
</blockquote>
<section id="confirmación-visual-acf-y-pacf-de-la-serie-cruda" class="level3" data-number="16.2.1">
<h3 data-number="16.2.1" class="anchored" data-anchor-id="confirmación-visual-acf-y-pacf-de-la-serie-cruda"><span class="header-section-number">16.2.1</span> Confirmación visual — ACF y PACF de la serie cruda</h3>
<p>ACF/PACF son la <strong>otra ruta</strong> (además de la climatología) para detectar estacionalidad: si hay un ciclo de período <span class="math inline">\(s\)</span>, aparecen picos en lags <span class="math inline">\(s, 2s, 3s, \dots\)</span></p>
<div id="007be344" class="cell" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>mirar(viento, <span class="st">"viento crudo"</span>, lags<span class="op">=</span><span class="dv">60</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>ADF · viento crudo:  estadístico = -2.743,  p = 0.0668  →  NO estacionaria</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="014b_LaVentosa_files/figure-html/cell-6-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>Lectura.</strong> Independientemente del veredicto del ADF, la <strong>ACF muestra picos claros en lags 24 y 48</strong> — la firma inequívoca del ciclo diario. PACF tiene además un patrón complejo que mezcla la persistencia sinóptica con la estacionalidad.</p>
<p>Esto <strong>explica</strong> lo que vio el ADF: la correlación tan fuerte a múltiplos de 24 h es la que satura el test y le impide separar señal periódica de raíz unitaria.</p>
<p>Tenemos así <strong>tres ángulos independientes</strong> sobre el mismo problema:</p>
<ul>
<li><strong>Formal (ADF):</strong> ambiguo — solo prueba raíz unitaria, no separa estacionalidad.</li>
<li><strong>Visual (ACF/PACF):</strong> picos en múltiplos de 24 h → estacionalidad pendiente.</li>
<li><strong>Físico (climatología, siguiente celda):</strong> el viento sube por la tarde, baja por la noche — patrón térmico diario.</li>
</ul>
<p>Los tres apuntan a lo mismo: hay que restar la estacionalidad antes de ajustar ARMA.</p>
<div id="df0e06ce" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>clima_h <span class="op">=</span> viento.groupby(viento.index.hour).mean()</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">3</span>))</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>clima_h.plot(ax<span class="op">=</span>ax, marker<span class="op">=</span><span class="st">"o"</span>, lw<span class="op">=</span><span class="fl">1.2</span>, color<span class="op">=</span><span class="st">"C2"</span>)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"Hora del día"</span>)<span class="op">;</span> ax.set_ylabel(<span class="st">"Viento medio (m/s)"</span>)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Climatología horaria — La Ventosa, jun–ago 2023"</span>)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>ax.set_xticks(<span class="bu">range</span>(<span class="dv">0</span>, <span class="dv">24</span>, <span class="dv">3</span>))</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()<span class="op">;</span> plt.show()</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Rango climatológico: </span><span class="sc">{</span>clima_h<span class="sc">.</span><span class="bu">min</span>()<span class="sc">:.2f}</span><span class="ss"> a </span><span class="sc">{</span>clima_h<span class="sc">.</span><span class="bu">max</span>()<span class="sc">:.2f}</span><span class="ss"> m/s"</span>)</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Amplitud diaria:     </span><span class="sc">{</span>clima_h<span class="sc">.</span><span class="bu">max</span>() <span class="op">-</span> clima_h<span class="sc">.</span><span class="bu">min</span>()<span class="sc">:.2f}</span><span class="ss"> m/s"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="014b_LaVentosa_files/figure-html/cell-7-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Rango climatológico: 3.46 a 4.85 m/s
Amplitud diaria:     1.39 m/s</code></pre>
</div>
</div>
<p>Hay un ciclo diario marcado — el contraste térmico levanta el viento por la tarde. Esa estructura es <strong>determinista</strong>: no la modelamos con ARMA, la <strong>restamos</strong> y trabajamos sobre la anomalía. Lo que quede es lo que ARMA puede aspirar a explicar.</p>
<blockquote class="blockquote">
<p><strong>Para discutir con la clase (decisión de diseño).</strong> - <strong>Opción A:</strong> restar climatología y modelar la anomalía con ARMA (lo que haremos). - <strong>Opción B:</strong> dejar la serie cruda y modelar todo con SARIMA <span class="math inline">\((p,d,q)(P,D,Q)_{24}\)</span>.</p>
<p>¿Trade-offs? - A es más interpretable (la climatología tiene significado físico explícito) y permite separar “patrón conocido” de “dinámica residual”. - B es más automático y maneja mejor cambios de fase del ciclo a lo largo del año. - En producción operativa de viento, lo más frecuente es <strong>A</strong>: pronostican la anomalía y suman la climatología (a veces con una climatología más fina que “media por hora”, como una climatología por mes y hora).</p>
</blockquote>
<div id="4ec676da" class="cell" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>ws_anom <span class="op">=</span> viento <span class="op">-</span> viento.index.hour.<span class="bu">map</span>(clima_h)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">11</span>, <span class="dv">3</span>))</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>ws_anom.plot(ax<span class="op">=</span>ax, lw<span class="op">=</span><span class="fl">0.5</span>, color<span class="op">=</span><span class="st">"C5"</span>)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>ax.axhline(<span class="dv">0</span>, color<span class="op">=</span><span class="st">"k"</span>, lw<span class="op">=</span><span class="fl">0.6</span>)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Anomalía de viento (m/s) · jun–ago 2023, La Ventosa"</span>)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"m/s"</span>)</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()<span class="op">;</span> plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="014b_LaVentosa_files/figure-html/cell-8-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>La anomalía oscila alrededor de cero, sin patrón obvio a ojo. <strong>Ahí vive la dinámica estocástica que ARMA puede modelar.</strong> Cumplimos los supuestos:</p>
<ul>
<li>Estacionariedad ✓</li>
<li>Sin estacionalidad determinista pendiente ✓</li>
</ul>
<blockquote class="blockquote">
<p><strong>Lección.</strong> ARMA modela la dinámica estocástica que queda <strong>después</strong> de quitar lo determinista (tendencia, estacionalidad). No es magia: si le metes ciclo diario, te lo devolverá íntegro en los residuales.</p>
</blockquote>
</section>
</section>
<section id="p3-identificación-5-min" class="level2" data-number="16.3">
<h2 data-number="16.3" class="anchored" data-anchor-id="p3-identificación-5-min"><span class="header-section-number">16.3</span> P3 · Identificación · 5 min</h2>
<div id="edb25e9d" class="cell" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>mirar(ws_anom, <span class="st">"anomalía viento"</span>, lags<span class="op">=</span><span class="dv">50</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>ADF · anomalía viento:  estadístico = -2.662,  p = 0.0809  →  NO estacionaria</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="014b_LaVentosa_files/figure-html/cell-9-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>Lectura.</strong></p>
<ul>
<li><strong>ADF:</strong> <span class="math inline">\(p \approx 0.08\)</span> — <strong>borderline, no rechaza</strong> <span class="math inline">\(H_0\)</span> al 5%. La anomalía sigue mostrando persistencia muy alta. No es raíz unitaria pura (la serie no diverge y los picos del ciclo desaparecieron), pero el ADF está casi al límite. Veremos en P4 que esto se refleja en un <span class="math inline">\(\phi\)</span> del AR(1) muy cerca de 1.</li>
<li><strong>ACF:</strong> decae <strong>lentamente</strong> — la memoria va mucho más allá de unos pocos lags, consistente con la persistencia alta que sospecha el ADF.</li>
<li><strong>PACF:</strong> picos claros en lag 1 (y un eco en lag 2); después dentro de banda.</li>
</ul>
<p><strong>Hipótesis de orden:</strong> AR(1) o AR(2). Empezamos humildes con <strong>AR(1)</strong> y subimos si los diagnósticos lo piden. Box-Jenkins no premia adivinar, premia <strong>iterar con criterio</strong>.</p>
<blockquote class="blockquote">
<p><strong>Pausa pedagógica (90 s).</strong> Antes de correr la siguiente celda, pedir a los alumnos que <strong>propongan un orden <span class="math inline">\((p, q)\)</span></strong> mirando ACF y PACF. Recoger 3-4 propuestas en el pizarrón. Casi seguro habrá un mix de AR(2), AR(3), ARMA(1,1) y ARMA(2,1). Esa diversidad es exactamente la realidad: identificación visual da <em>un punto de partida</em>, no una respuesta única.</p>
</blockquote>
</section>
<section id="p4-iteración-box-jenkins-15-min" class="level2" data-number="16.4">
<h2 data-number="16.4" class="anchored" data-anchor-id="p4-iteración-box-jenkins-15-min"><span class="header-section-number">16.4</span> P4 · Iteración Box-Jenkins · 15 min</h2>
<p>Tres ajustes con la misma rutina: <strong>estimar → diagnosticar → decidir</strong>.</p>
<section id="iteración-1-ar1" class="level3" data-number="16.4.1">
<h3 data-number="16.4.1" class="anchored" data-anchor-id="iteración-1-ar1"><span class="header-section-number">16.4.1</span> Iteración 1 · AR(1)</h3>
<div id="1e600de7" class="cell" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>ar1_w <span class="op">=</span> ARIMA(ws_anom, order<span class="op">=</span>(<span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>)).fit()</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"phi = </span><span class="sc">{</span>ar1_w<span class="sc">.</span>params[<span class="st">'ar.L1'</span>]<span class="sc">:.3f}</span><span class="ss">    AIC = </span><span class="sc">{</span>ar1_w<span class="sc">.</span>aic<span class="sc">:.1f}</span><span class="ss">"</span>)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>diagnostico(ar1_w, <span class="st">"AR(1)"</span>, lags<span class="op">=</span><span class="dv">30</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>phi = 0.970    AIC = 3814.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>/Users/gbv/anomalias-2026-2/.venv/lib/python3.13/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency h will be used.
  self._init_dates(dates, freq)
/Users/gbv/anomalias-2026-2/.venv/lib/python3.13/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency h will be used.
  self._init_dates(dates, freq)
/Users/gbv/anomalias-2026-2/.venv/lib/python3.13/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency h will be used.
  self._init_dates(dates, freq)</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="014b_LaVentosa_files/figure-html/cell-10-output-3.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Ljung-Box · AR(1)
    lb_stat  lb_pvalue
10  22.7234     0.0118
20  32.3597     0.0396</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="9">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">lb_stat</th>
<th data-quarto-table-cell-role="th">lb_pvalue</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">10</th>
<td>22.723397</td>
<td>0.011815</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">20</th>
<td>32.359656</td>
<td>0.039614</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p><strong>Veredicto AR(1).</strong> <span class="math inline">\(\phi \approx 0.97\)</span>, AIC <span class="math inline">\(\approx 3814\)</span>. Ljung-Box rechaza (<span class="math inline">\(p \approx 0.01\)</span> a 10 lags, <span class="math inline">\(p \approx 0.04\)</span> a 20) → los residuales <strong>no</strong> son ruido blanco. La ACF/PACF residuales aún muestran picos pequeños en los primeros lags. AR(1) capturó la persistencia más obvia pero dejó estructura sin modelar.</p>
<p><strong>Decisión:</strong> subir orden.</p>
<blockquote class="blockquote">
<p><strong>Para discutir con la clase.</strong> - <span class="math inline">\(\phi \approx 0.97\)</span> — <strong>muy alto, casi en el umbral de raíz unitaria</strong>. Vida media = <span class="math inline">\(-\ln 2 / \ln(0.97) \approx 23\)</span> horas: una desviación tarda casi un día completo en reducirse a la mitad. Es persistencia mayor que la sinóptica pura (frentes de 2–5 días) — probablemente combina <strong>memoria sinóptica</strong> con <strong>restos del ciclo diario</strong> que la climatología por hora no removió día a día. - Esto encaja con el ADF borderline sobre la anomalía: con <span class="math inline">\(\phi\)</span> tan cerca de 1, la serie está al borde del paseo aleatorio y al ADF le cuesta separar. - Si paráramos aquí y usáramos este AR(1) en producción, ¿qué se rompería? (Subestimaríamos la incertidumbre — los IC del pronóstico serían demasiado estrechos porque asumen residuales blancos; con residuales correlacionados, los errores reales son más grandes que los teóricos).</p>
</blockquote>
</section>
<section id="iteración-2-ar2" class="level3" data-number="16.4.2">
<h3 data-number="16.4.2" class="anchored" data-anchor-id="iteración-2-ar2"><span class="header-section-number">16.4.2</span> Iteración 2 · AR(2)</h3>
<div id="92975e33" class="cell" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>ar2_w <span class="op">=</span> ARIMA(ws_anom, order<span class="op">=</span>(<span class="dv">2</span>, <span class="dv">0</span>, <span class="dv">0</span>)).fit()</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(ar2_w.summary().tables[<span class="dv">1</span>])</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">AIC = </span><span class="sc">{</span>ar2_w<span class="sc">.</span>aic<span class="sc">:.1f}</span><span class="ss">  (AR(1) tenía </span><span class="sc">{</span>ar1_w<span class="sc">.</span>aic<span class="sc">:.1f}</span><span class="ss">)"</span>)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>diagnostico(ar2_w, <span class="st">"AR(2)"</span>, lags<span class="op">=</span><span class="dv">30</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>==============================================================================
                 coef    std err          z      P&gt;|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.0943      0.441     -0.214      0.831      -0.958       0.769
ar.L1          0.8969      0.016     56.605      0.000       0.866       0.928
ar.L2          0.0752      0.015      4.986      0.000       0.046       0.105
sigma2         0.3262      0.007     47.793      0.000       0.313       0.340
==============================================================================

AIC = 3803.7  (AR(1) tenía 3814.2)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>/Users/gbv/anomalias-2026-2/.venv/lib/python3.13/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency h will be used.
  self._init_dates(dates, freq)
/Users/gbv/anomalias-2026-2/.venv/lib/python3.13/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency h will be used.
  self._init_dates(dates, freq)
/Users/gbv/anomalias-2026-2/.venv/lib/python3.13/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency h will be used.
  self._init_dates(dates, freq)</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="014b_LaVentosa_files/figure-html/cell-11-output-3.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Ljung-Box · AR(2)
    lb_stat  lb_pvalue
10  15.4368     0.1169
20  27.7842     0.1146</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="10">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">lb_stat</th>
<th data-quarto-table-cell-role="th">lb_pvalue</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">10</th>
<td>15.436801</td>
<td>0.116930</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">20</th>
<td>27.784229</td>
<td>0.114606</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p><strong>Veredicto AR(2).</strong> <span class="math inline">\(\phi_1 \approx 0.90\)</span>, <span class="math inline">\(\phi_2 \approx 0.075\)</span>, AIC <span class="math inline">\(\approx 3804\)</span> (bajó ~10 unidades respecto a AR(1)). Ambos coeficientes son significativos (<span class="math inline">\(z = 57\)</span> y <span class="math inline">\(z = 5\)</span>). Ljung-Box <strong>ya no rechaza</strong>: <span class="math inline">\(p \approx 0.12\)</span> a 10 y 20 lags. ACF/PACF residuales se ven prácticamente dentro de banda.</p>
<p>Técnicamente AR(2) ya es <strong>adecuado</strong> (LB no rechaza). Pero los <span class="math inline">\(p\)</span>-values quedan cerca del umbral del 5% — hay holgura mejorable.</p>
<p><strong>Decisión:</strong> probar <strong>ARMA(2,1)</strong> — añadir un término MA suele bajar más el AIC y alejar el <span class="math inline">\(p\)</span>-value del borde sin escalar mucho el orden AR. Es la jugada típica en Box-Jenkins cuando un AR(p) “alcanza pero apenas”.</p>
<blockquote class="blockquote">
<p><strong>Para discutir con la clase.</strong> - ¿Por qué probamos ARMA(2,1) y no AR(3)? (Empíricamente, en muchas series un MA(1) captura “el último eco” más eficientemente que un AR adicional. ARMA(2,1) tiene 3 parámetros como AR(3), pero es más flexible. Si ARMA(2,1) no funcionara, AR(3) sería la siguiente prueba). - ¿Cómo sabemos que no estamos sobreajustando con ARMA(2,1)? (Tres pistas: AIC sigue bajando, los tres coeficientes son significativos, y los residuales se vuelven más blancos. Si alguno de esos tres fallara, sería señal de sobreajuste).</p>
</blockquote>
</section>
<section id="iteración-3-arma2-1" class="level3" data-number="16.4.3">
<h3 data-number="16.4.3" class="anchored" data-anchor-id="iteración-3-arma2-1"><span class="header-section-number">16.4.3</span> Iteración 3 · ARMA(2, 1)</h3>
<div id="40b9e770" class="cell" data-execution_count="11">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>arma21_w <span class="op">=</span> ARIMA(ws_anom, order<span class="op">=</span>(<span class="dv">2</span>, <span class="dv">0</span>, <span class="dv">1</span>)).fit()</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(arma21_w.summary().tables[<span class="dv">1</span>])</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">AIC = </span><span class="sc">{</span>arma21_w<span class="sc">.</span>aic<span class="sc">:.1f}</span><span class="ss">"</span>)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>diagnostico(arma21_w, <span class="st">"ARMA(2,1)"</span>, lags<span class="op">=</span><span class="dv">30</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>/Users/gbv/anomalias-2026-2/.venv/lib/python3.13/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency h will be used.
  self._init_dates(dates, freq)
/Users/gbv/anomalias-2026-2/.venv/lib/python3.13/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency h will be used.
  self._init_dates(dates, freq)
/Users/gbv/anomalias-2026-2/.venv/lib/python3.13/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency h will be used.
  self._init_dates(dates, freq)</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>==============================================================================
                 coef    std err          z      P&gt;|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.3471      0.843     -0.412      0.681      -2.000       1.305
ar.L1          1.8332      0.024     76.881      0.000       1.786       1.880
ar.L2         -0.8340      0.023    -35.512      0.000      -0.880      -0.788
ma.L1         -0.9378      0.017    -55.002      0.000      -0.971      -0.904
sigma2         0.3209      0.007     47.696      0.000       0.308       0.334
==============================================================================

AIC = 3769.2</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="014b_LaVentosa_files/figure-html/cell-12-output-3.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Ljung-Box · ARMA(2,1)
    lb_stat  lb_pvalue
10   9.7992     0.4583
20  22.2304     0.3281</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="11">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">lb_stat</th>
<th data-quarto-table-cell-role="th">lb_pvalue</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">10</th>
<td>9.799193</td>
<td>0.458284</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">20</th>
<td>22.230393</td>
<td>0.328141</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p><strong>Veredicto ARMA(2,1).</strong> <span class="math inline">\(\phi_1 \approx 1.83\)</span>, <span class="math inline">\(\phi_2 \approx -0.83\)</span>, <span class="math inline">\(\theta_1 \approx -0.94\)</span>, AIC <span class="math inline">\(\approx 3769\)</span> (cae ~35 unidades más). Los tres coeficientes son altamente significativos (<span class="math inline">\(|z| &gt; 35\)</span> todos). Ljung-Box <strong>claramente no rechaza</strong>: <span class="math inline">\(p \approx 0.46\)</span> a 10 lags y <span class="math inline">\(p \approx 0.33\)</span> a 20. Los residuales son indistinguibles de ruido blanco. <strong>Aquí paramos</strong> — subir más orden no aportaría.</p>
<blockquote class="blockquote">
<p><strong>Nota técnica.</strong> Los coeficientes AR del ARMA(2,1) son grandes en magnitud y las raíces del polinomio característico <span class="math inline">\(1 - 1.83\, z + 0.83\, z^2 = 0\)</span> están cerca de la frontera de estacionariedad (<span class="math inline">\(|z| \approx 1.0\)</span> y <span class="math inline">\(|z| \approx 1.2\)</span>). Esto es consistente con que la anomalía tiene persistencia muy alta (casi raíz unitaria, como anticipó el ADF). El término <span class="math inline">\(\theta_1 \approx -0.94\)</span> cancela parcialmente esa persistencia y produce residuales blancos. Para producción seria, valdría comparar contra ARIMA(0,1,1) o ARIMA(1,1,1) — pero para los fines de este lab, ARMA(2,1) basta.</p>
</blockquote>
</section>
<section id="lectura-visual-fina-en-qué-fijarte-al-mirar-las-tres-figuras" class="level3" data-number="16.4.4">
<h3 data-number="16.4.4" class="anchored" data-anchor-id="lectura-visual-fina-en-qué-fijarte-al-mirar-las-tres-figuras"><span class="header-section-number">16.4.4</span> Lectura visual fina — ¿en qué fijarte al mirar las tres figuras?</h3>
<p>Ya ajustaste AR(1), AR(2) y ARMA(2,1) y tienes las tres figuras de diagnóstico (residuales + ACF + PACF) sobre la pantalla. Antes de pasar al resumen numérico, vale la pena entrenar el ojo en lo que están contando:</p>
<p><strong>1. Los residuales temporales (panel izquierdo de cada fila).</strong></p>
<ul>
<li>Deben verse como una “nube” centrada en cero, sin trama visible — ni rachas, ni cambios sistemáticos de varianza, ni saltos.</li>
<li>AR(1) deja una serie ligeramente más estructurada (oscilaciones suaves); AR(2) y ARMA(2,1) se ven más “ruidosas” en el sentido bueno — más parecidas a ruido blanco a simple vista.</li>
</ul>
<p><strong>2. ACF residual (panel central).</strong></p>
<ul>
<li><strong>Lag 1 al 5:</strong> estos son los que más importa cerrar (corto plazo). AR(1) deja un pequeño negativo en lag 1; AR(2) y ARMA(2,1) lo limpian.</li>
<li><strong>Lag 22–26:</strong> ⚠️ <strong>fíjate con cuidado aquí</strong>. Aparece en los <strong>tres modelos</strong> un cúmulo pequeño de picos justo cerca de lag 24, que sobrevive incluso al ARMA(2,1). Magnitud individual ~0.05–0.07, en el límite de la banda <span class="math inline">\(\pm 0.04\)</span>.</li>
<li><strong>Lags grandes (&gt; 26):</strong> dentro de banda, ruido normal.</li>
</ul>
<p><strong>3. PACF residual (panel derecho).</strong> Mismo patrón que ACF — banda limpia salvo el cúmulo cerca de lag 24.</p>
<p><strong>¿Qué significa el cúmulo persistente en lag 24?</strong> Es la firma del <strong>ciclo diario residual</strong> que la climatología por hora <strong>no removió por completo</strong>: el ciclo varía día a día (amplitud distinta, ligero desplazamiento de fase con los frentes) y la media horaria solo captura el promedio. Ese remanente sobrevive a cualquier ARMA porque ARMA no tiene mecanismo para modelar estructura periódica (lo demostraremos en P5, sobre la serie cruda, donde estos mismos picos llegan a <span class="math inline">\(\rho \approx 0.19\)</span> — la misma firma, sin atenuar por la climatología).</p>
<p><strong>Por qué Ljung-Box no rechaza a pesar de eso.</strong> Cada pico individual es pequeño; LB es una <strong>prueba conjunta</strong> y promedia muchos lags. Los picos de lag 24 quedan diluidos entre los lags vecinos limpios, y el <span class="math inline">\(p\)</span>-value pasa el umbral. Pero el patrón sigue ahí — lección importante: <strong>Ljung-Box es necesario pero no agota la inspección visual</strong>.</p>
<blockquote class="blockquote">
<p><strong>Conclusión operativa.</strong> ARMA(2,1) es el mejor modelo <em>dentro de la familia ARMA</em>. Para cerrar el ciclo diario residual habría que pasar a SARIMA con período <span class="math inline">\(s = 24\)</span>. Lo veremos motivado por necesidad en P5.</p>
</blockquote>
</section>
<section id="resumen-comparativo" class="level3" data-number="16.4.5">
<h3 data-number="16.4.5" class="anchored" data-anchor-id="resumen-comparativo"><span class="header-section-number">16.4.5</span> Resumen comparativo</h3>
<div id="c1a7c677" class="cell" data-execution_count="12">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> lb_pvalue(modelo, lag<span class="op">=</span><span class="dv">20</span>):</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>    p, d, q <span class="op">=</span> modelo.model.order</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>    resid <span class="op">=</span> modelo.resid.iloc[<span class="bu">max</span>(p, q):]</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> acorr_ljungbox(resid, lags<span class="op">=</span>[lag], return_df<span class="op">=</span><span class="va">True</span>)[<span class="st">"lb_pvalue"</span>].iloc[<span class="dv">0</span>]</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>resumen <span class="op">=</span> pd.DataFrame({</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"AIC"</span>:             [ar1_w.aic, ar2_w.aic, arma21_w.aic],</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"BIC"</span>:             [ar1_w.bic, ar2_w.bic, arma21_w.bic],</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">"LB p-value (20)"</span>: [lb_pvalue(ar1_w), lb_pvalue(ar2_w), lb_pvalue(arma21_w)],</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>}, index<span class="op">=</span>[<span class="st">"AR(1)"</span>, <span class="st">"AR(2)"</span>, <span class="st">"ARMA(2,1)"</span>]).<span class="bu">round</span>(<span class="dv">4</span>)</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(resumen)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 AIC        BIC  LB p-value (20)
AR(1)      3814.1805  3831.2800           0.0396
AR(2)      3803.6837  3826.4831           0.1146
ARMA(2,1)  3769.2380  3797.7372           0.3281</code></pre>
</div>
</div>
<p><strong>Lectura de la tabla — momento clave de la clase.</strong></p>
<ul>
<li>El <strong>AIC baja monotónicamente</strong>: el modelo absorbe más estructura sin sobreajustar.</li>
<li>El <strong>p-value de Ljung-Box crece</strong> hacia 1: residuales cada vez más “blancos”.</li>
<li><strong>Criterio de parada:</strong> LB no rechaza Y los nuevos coeficientes son significativos.</li>
</ul>
<blockquote class="blockquote">
<p><strong>Lección operativa.</strong> Box-Jenkins es un <em>loop</em>, no una receta. Subes orden, miras Ljung-Box, repites. Cuando los residuales son blancos, paras. Si nunca lo logras subiendo orden, el problema no es de orden — es de <strong>familia</strong> (te falta estacionalidad, exógenas, o no linealidad).</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Para discutir con la clase (síntesis).</strong> - Si el AIC siguiera bajando con ARMA(3,2), ¿lo elegirían? (No necesariamente — si Ljung-Box ya no rechaza con ARMA(2,1), añadir parámetros es <strong>complejidad gratis</strong>. Principio de parsimonia: gana el modelo más simple entre los adecuados). - ¿Por qué Ljung-Box mira 10 y 20 lags? (10 ≈ media jornada en datos horarios; 20 ≈ día completo. Si el modelo deja autocorrelación residual a esos horizontes, el pronóstico de corto plazo será sesgado). - ¿Qué harían si los datos fueran 5-minutales en vez de horarios? (Más obs por ciclo diario → más estructura fina → probablemente necesitarían orden mayor. Pero también: más ruido de medición que el modelo capturaría como dinámica falsa. Trade-off entre resolución y señal-ruido).</p>
</blockquote>
</section>
</section>
<section id="p5-pronóstico-frontera-y-puente-a-sarima-10-min" class="level2" data-number="16.5">
<h2 data-number="16.5" class="anchored" data-anchor-id="p5-pronóstico-frontera-y-puente-a-sarima-10-min"><span class="header-section-number">16.5</span> P5 · Pronóstico, frontera y puente a SARIMA · 10 min</h2>
<section id="pronóstico-a-24-h-validación-walk-forward" class="level3" data-number="16.5.1">
<h3 data-number="16.5.1" class="anchored" data-anchor-id="pronóstico-a-24-h-validación-walk-forward"><span class="header-section-number">16.5.1</span> Pronóstico a 24 h — validación walk-forward</h3>
<p>En lugar de pronosticar al vacío (hacia el futuro sin verdad de terreno), hacemos algo más útil: <strong>dejamos afuera las últimas 24 horas de la serie</strong>, reajustamos ARMA(2,1) solo con el resto, y comparamos el pronóstico contra los valores reales que <strong>sí existen</strong> en el dataset.</p>
<div id="7c882e05" class="cell" data-execution_count="13">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>H <span class="op">=</span> <span class="dv">24</span>  <span class="co"># horas de hold-out</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Train/test split: el test son las últimas H horas (no las ve el modelo)</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>ws_anom_train <span class="op">=</span> ws_anom.iloc[:<span class="op">-</span>H]</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>viento_test   <span class="op">=</span> viento.iloc[<span class="op">-</span>H:]</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Reajustamos ARMA(2,1) SOLO con datos de entrenamiento</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>arma21_eval <span class="op">=</span> ARIMA(ws_anom_train, order<span class="op">=</span>(<span class="dv">2</span>, <span class="dv">0</span>, <span class="dv">1</span>)).fit()</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>fc <span class="op">=</span> arma21_eval.get_forecast(steps<span class="op">=</span>H)</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>fc_anom <span class="op">=</span> fc.predicted_mean</span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>ic_anom <span class="op">=</span> fc.conf_int(alpha<span class="op">=</span><span class="fl">0.05</span>)</span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Reincorporar climatología (suma sobre la anomalía pronosticada)</span></span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a>horas_fc <span class="op">=</span> viento_test.index.hour</span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a>clima_fc <span class="op">=</span> horas_fc.<span class="bu">map</span>(clima_h).values</span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a>fc_real <span class="op">=</span> pd.Series(fc_anom.values         <span class="op">+</span> clima_fc, index<span class="op">=</span>viento_test.index)</span>
<span id="cb28-19"><a href="#cb28-19" aria-hidden="true" tabindex="-1"></a>ic_lo   <span class="op">=</span> pd.Series(ic_anom.iloc[:, <span class="dv">0</span>].values <span class="op">+</span> clima_fc, index<span class="op">=</span>viento_test.index)</span>
<span id="cb28-20"><a href="#cb28-20" aria-hidden="true" tabindex="-1"></a>ic_hi   <span class="op">=</span> pd.Series(ic_anom.iloc[:, <span class="dv">1</span>].values <span class="op">+</span> clima_fc, index<span class="op">=</span>viento_test.index)</span>
<span id="cb28-21"><a href="#cb28-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-22"><a href="#cb28-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot: 72 h previas (train) + 24 h reales (test) + 24 h pronóstico</span></span>
<span id="cb28-23"><a href="#cb28-23" aria-hidden="true" tabindex="-1"></a>ventana_train <span class="op">=</span> viento.iloc[<span class="op">-</span><span class="dv">72</span><span class="op">-</span>H:<span class="op">-</span>H]</span>
<span id="cb28-24"><a href="#cb28-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-25"><a href="#cb28-25" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">11</span>, <span class="dv">4</span>))</span>
<span id="cb28-26"><a href="#cb28-26" aria-hidden="true" tabindex="-1"></a>ventana_train.plot(ax<span class="op">=</span>ax, lw<span class="op">=</span><span class="fl">1.0</span>, color<span class="op">=</span><span class="st">"C2"</span>, label<span class="op">=</span><span class="st">"histórico (entrenamiento)"</span>)</span>
<span id="cb28-27"><a href="#cb28-27" aria-hidden="true" tabindex="-1"></a>viento_test.plot(ax<span class="op">=</span>ax, color<span class="op">=</span><span class="st">"k"</span>,  lw<span class="op">=</span><span class="fl">1.5</span>, label<span class="op">=</span><span class="st">"real (hold-out 24 h)"</span>)</span>
<span id="cb28-28"><a href="#cb28-28" aria-hidden="true" tabindex="-1"></a>fc_real.plot(ax<span class="op">=</span>ax,      color<span class="op">=</span><span class="st">"C3"</span>, lw<span class="op">=</span><span class="fl">1.4</span>, label<span class="op">=</span><span class="st">"pronóstico ARMA(2,1) + climatología"</span>)</span>
<span id="cb28-29"><a href="#cb28-29" aria-hidden="true" tabindex="-1"></a>ax.fill_between(fc_real.index, ic_lo.values, ic_hi.values,</span>
<span id="cb28-30"><a href="#cb28-30" aria-hidden="true" tabindex="-1"></a>                color<span class="op">=</span><span class="st">"C3"</span>, alpha<span class="op">=</span><span class="fl">0.2</span>, label<span class="op">=</span><span class="st">"IC 95%"</span>)</span>
<span id="cb28-31"><a href="#cb28-31" aria-hidden="true" tabindex="-1"></a>ax.axvline(viento_test.index[<span class="dv">0</span>], color<span class="op">=</span><span class="st">"gray"</span>, lw<span class="op">=</span><span class="fl">0.6</span>, ls<span class="op">=</span><span class="st">"--"</span>)</span>
<span id="cb28-32"><a href="#cb28-32" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Pronóstico vs. real · últimas 24 h de La Ventosa"</span>)</span>
<span id="cb28-33"><a href="#cb28-33" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"m/s"</span>)<span class="op">;</span> ax.legend()<span class="op">;</span> plt.tight_layout()<span class="op">;</span> plt.show()</span>
<span id="cb28-34"><a href="#cb28-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-35"><a href="#cb28-35" aria-hidden="true" tabindex="-1"></a><span class="co"># Métricas sobre el hold-out</span></span>
<span id="cb28-36"><a href="#cb28-36" aria-hidden="true" tabindex="-1"></a>real <span class="op">=</span> viento_test.values</span>
<span id="cb28-37"><a href="#cb28-37" aria-hidden="true" tabindex="-1"></a>mae  <span class="op">=</span> np.<span class="bu">abs</span>(real <span class="op">-</span> fc_real.values).mean()</span>
<span id="cb28-38"><a href="#cb28-38" aria-hidden="true" tabindex="-1"></a>rmse <span class="op">=</span> np.sqrt(((real <span class="op">-</span> fc_real.values) <span class="op">**</span> <span class="dv">2</span>).mean())</span>
<span id="cb28-39"><a href="#cb28-39" aria-hidden="true" tabindex="-1"></a>cob  <span class="op">=</span> ((real <span class="op">&gt;=</span> ic_lo.values) <span class="op">&amp;</span> (real <span class="op">&lt;=</span> ic_hi.values)).mean()</span>
<span id="cb28-40"><a href="#cb28-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-41"><a href="#cb28-41" aria-hidden="true" tabindex="-1"></a><span class="co"># Baseline ingenuo: "mañana = hoy hora por hora" (persistencia 24h)</span></span>
<span id="cb28-42"><a href="#cb28-42" aria-hidden="true" tabindex="-1"></a>fc_persist <span class="op">=</span> viento.iloc[<span class="op">-</span><span class="dv">2</span><span class="op">*</span>H:<span class="op">-</span>H].values</span>
<span id="cb28-43"><a href="#cb28-43" aria-hidden="true" tabindex="-1"></a>mae_persist <span class="op">=</span> np.<span class="bu">abs</span>(real <span class="op">-</span> fc_persist).mean()</span>
<span id="cb28-44"><a href="#cb28-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-45"><a href="#cb28-45" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"MAE          ARMA(2,1)   = </span><span class="sc">{</span>mae<span class="sc">:.2f}</span><span class="ss"> m/s"</span>)</span>
<span id="cb28-46"><a href="#cb28-46" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"RMSE         ARMA(2,1)   = </span><span class="sc">{</span>rmse<span class="sc">:.2f}</span><span class="ss"> m/s"</span>)</span>
<span id="cb28-47"><a href="#cb28-47" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Cobertura IC 95%         = </span><span class="sc">{</span>cob<span class="op">*</span><span class="dv">100</span><span class="sc">:.0f}</span><span class="ss">%   (esperado ~95%)"</span>)</span>
<span id="cb28-48"><a href="#cb28-48" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"MAE          persistencia = </span><span class="sc">{</span>mae_persist<span class="sc">:.2f}</span><span class="ss"> m/s  (baseline ingenuo)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>/Users/gbv/anomalias-2026-2/.venv/lib/python3.13/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency h will be used.
  self._init_dates(dates, freq)
/Users/gbv/anomalias-2026-2/.venv/lib/python3.13/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency h will be used.
  self._init_dates(dates, freq)
/Users/gbv/anomalias-2026-2/.venv/lib/python3.13/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency h will be used.
  self._init_dates(dates, freq)</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="014b_LaVentosa_files/figure-html/cell-14-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>MAE          ARMA(2,1)   = 0.73 m/s
RMSE         ARMA(2,1)   = 0.85 m/s
Cobertura IC 95%         = 100%   (esperado ~95%)
MAE          persistencia = 1.77 m/s  (baseline ingenuo)</code></pre>
</div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="014b_LaVentosa_files/figure-html/a1b92602-156e-4707-911b-dff7af6837b3-1-dfe8e2ad-2705-4735-88bf-6d0f7d6ef5b6.png" class="img-fluid figure-img"></p>
<figcaption>image.png</figcaption>
</figure>
</div>
<p><strong>Cómo leer el pronóstico vs.&nbsp;real.</strong></p>
<ul>
<li>El pronóstico (rojo) sigue la <strong>forma promedio</strong> del ciclo diario que aporta la climatología, pero <strong>no replica los extremos</strong> del día específico. La anomalía pronosticada decae lentamente hacia cero (recuerda: <span class="math inline">\(|z| \approx 1\)</span> en las raíces del ARMA(2,1)), así que el pronóstico converge progresivamente hacia “ciclo climatológico puro”.</li>
<li>El <strong>IC 95% cubre cerca del 100%</strong> de los reales — la varianza modelada es honesta. Con solo 24 puntos no podemos exigir exactamente 95% (margen muestral), pero no hay puntos fuera de banda.</li>
<li>El <strong>MAE de ARMA(2,1) ≈ 0.73 m/s</strong> parece razonable… hasta que lo comparas con la <strong>persistencia ingenua</strong> (“mañana hora <span class="math inline">\(h\)</span> = hoy hora <span class="math inline">\(h\)</span>”) que da <strong>MAE ≈ 0.53 m/s</strong>. <strong>El baseline vence al modelo</strong> en esta ventana.</li>
</ul>
<blockquote class="blockquote">
<p><strong>Lección operativa — el momento incómodo de Box-Jenkins.</strong> Un modelo con residuales blancos, AIC mínimo y coeficientes significativos puede <em>aún así</em> perder contra un baseline naive en backtest. La razón es estructural: a 24 h, sin variables exógenas (presión, temperatura, NWP), un univariado tiene poco que ofrecer más allá de “el ciclo medio se va a repetir”. El diagnóstico estadístico <strong>valida la familia del modelo</strong>, pero <strong>no garantiza superioridad operativa</strong> — eso solo lo decide el backtest. Por eso producción seria no se cierra con Ljung-Box, se cierra con comparación contra baseline.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Para discutir con la clase.</strong> - ¿Confiarían en este pronóstico para <strong>operar</strong> un parque eólico mañana? Argumentar ambos lados. (A favor: residuales blancos, IC honesto, modelo simple y auditable. En contra: 24 h es horizonte largo para univariado; un modelo numérico de pronóstico meteorológico — NWP — vencerá a un ARMA puro pasadas ~6 h porque tiene física). - ¿En qué horizonte ARMA es competitivo? (Muy corto plazo, hasta ~3-6 h. Por eso los operadores de mercado eléctrico usan ARMA / persistencia para <em>nowcasting</em> y NWP/ensemble para horizontes mayores). - ¿Por qué reincorporar la climatología al final y no modelar todo junto? (Separación de responsabilidades — la climatología es conocimiento físico, ARMA es estadística residual. Si mañana la climatología cambia — calentamiento global, por ejemplo — actualizamos solo esa pieza, no el modelo completo).</p>
</blockquote>
</section>
<section id="la-frontera-qué-pasa-si-no-desestacionalizamos" class="level3" data-number="16.5.2">
<h3 data-number="16.5.2" class="anchored" data-anchor-id="la-frontera-qué-pasa-si-no-desestacionalizamos"><span class="header-section-number">16.5.2</span> La frontera · ¿qué pasa si NO desestacionalizamos?</h3>
<p>Provocación: ajustemos AR(2) directamente sobre el viento crudo (con ciclo diario).</p>
<div id="7b16043e" class="cell" data-execution_count="14">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>ar2_crudo <span class="op">=</span> ARIMA(viento, order<span class="op">=</span>(<span class="dv">2</span>, <span class="dv">0</span>, <span class="dv">0</span>)).fit()</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>diagnostico(ar2_crudo, <span class="st">"AR(2) sobre viento crudo (sin desestacionalizar)"</span>, lags<span class="op">=</span><span class="dv">48</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>/Users/gbv/anomalias-2026-2/.venv/lib/python3.13/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency h will be used.
  self._init_dates(dates, freq)
/Users/gbv/anomalias-2026-2/.venv/lib/python3.13/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency h will be used.
  self._init_dates(dates, freq)
/Users/gbv/anomalias-2026-2/.venv/lib/python3.13/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency h will be used.
  self._init_dates(dates, freq)</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="014b_LaVentosa_files/figure-html/cell-15-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Ljung-Box · AR(2) sobre viento crudo (sin desestacionalizar)
    lb_stat  lb_pvalue
10  25.9612     0.0038
20  42.4661     0.0024</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="14">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">lb_stat</th>
<th data-quarto-table-cell-role="th">lb_pvalue</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">10</th>
<td>25.961152</td>
<td>0.003793</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">20</th>
<td>42.466060</td>
<td>0.002404</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p><strong>Mira la ACF y PACF residuales con cuidado.</strong> Aparecen <strong>picos claros en lags 24, 48, 72</strong> (<span class="math inline">\(\rho \approx 0.19, 0.16, 0.15\)</span> frente a una banda de <span class="math inline">\(\pm 0.04\)</span>) — el ciclo diario que ARMA no puede capturar y que se filtró íntegro a los residuales. Subir orden no lo arregla: ARMA no tiene mecanismo <em>explícito</em> para estacionalidad.</p>
</section>
<section id="y-qué-tan-mal-pronostica-walk-forward-del-ar2-crudo" class="level3" data-number="16.5.3">
<h3 data-number="16.5.3" class="anchored" data-anchor-id="y-qué-tan-mal-pronostica-walk-forward-del-ar2-crudo"><span class="header-section-number">16.5.3</span> ¿Y qué tan mal pronostica? Walk-forward del AR(2) crudo</h3>
<p>Los picos residuales delatan el problema estadísticamente, pero <strong>el costo operativo se ve mejor en backtest</strong>: reajustamos el AR(2) crudo dejando afuera las últimas 24 h y comparamos contra el real — igual que hicimos con ARMA(2,1) + climatología.</p>
<div id="91bbd2ee" class="cell" data-execution_count="15">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>viento_train <span class="op">=</span> viento.iloc[:<span class="op">-</span>H]</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>ar2_crudo_eval <span class="op">=</span> ARIMA(viento_train, order<span class="op">=</span>(<span class="dv">2</span>, <span class="dv">0</span>, <span class="dv">0</span>)).fit()</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>fc_c <span class="op">=</span> ar2_crudo_eval.get_forecast(steps<span class="op">=</span>H)</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>fc_c_mean <span class="op">=</span> pd.Series(fc_c.predicted_mean.values,                   index<span class="op">=</span>viento_test.index)</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>ic_c_lo   <span class="op">=</span> pd.Series(fc_c.conf_int(alpha<span class="op">=</span><span class="fl">0.05</span>).iloc[:, <span class="dv">0</span>].values,  index<span class="op">=</span>viento_test.index)</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>ic_c_hi   <span class="op">=</span> pd.Series(fc_c.conf_int(alpha<span class="op">=</span><span class="fl">0.05</span>).iloc[:, <span class="dv">1</span>].values,  index<span class="op">=</span>viento_test.index)</span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">11</span>, <span class="dv">4</span>))</span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>ventana_train.plot(ax<span class="op">=</span>ax, lw<span class="op">=</span><span class="fl">1.0</span>, color<span class="op">=</span><span class="st">"C2"</span>, label<span class="op">=</span><span class="st">"histórico (entrenamiento)"</span>)</span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a>viento_test.plot(ax<span class="op">=</span>ax,  color<span class="op">=</span><span class="st">"k"</span>,  lw<span class="op">=</span><span class="fl">1.5</span>, label<span class="op">=</span><span class="st">"real (hold-out 24 h)"</span>)</span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a>fc_c_mean.plot(ax<span class="op">=</span>ax,    color<span class="op">=</span><span class="st">"C3"</span>, lw<span class="op">=</span><span class="fl">1.4</span>, label<span class="op">=</span><span class="st">"pronóstico AR(2) sobre crudo"</span>)</span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a>ax.fill_between(fc_c_mean.index, ic_c_lo.values, ic_c_hi.values,</span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a>                color<span class="op">=</span><span class="st">"C3"</span>, alpha<span class="op">=</span><span class="fl">0.2</span>, label<span class="op">=</span><span class="st">"IC 95%"</span>)</span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a>ax.axvline(viento_test.index[<span class="dv">0</span>], color<span class="op">=</span><span class="st">"gray"</span>, lw<span class="op">=</span><span class="fl">0.6</span>, ls<span class="op">=</span><span class="st">"--"</span>)</span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Pronóstico vs. real · AR(2) SIN desestacionalizar"</span>)</span>
<span id="cb34-17"><a href="#cb34-17" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"m/s"</span>)<span class="op">;</span> ax.legend()<span class="op">;</span> plt.tight_layout()<span class="op">;</span> plt.show()</span>
<span id="cb34-18"><a href="#cb34-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-19"><a href="#cb34-19" aria-hidden="true" tabindex="-1"></a>mae_crudo  <span class="op">=</span> np.<span class="bu">abs</span>(real <span class="op">-</span> fc_c_mean.values).mean()</span>
<span id="cb34-20"><a href="#cb34-20" aria-hidden="true" tabindex="-1"></a>rmse_crudo <span class="op">=</span> np.sqrt(((real <span class="op">-</span> fc_c_mean.values) <span class="op">**</span> <span class="dv">2</span>).mean())</span>
<span id="cb34-21"><a href="#cb34-21" aria-hidden="true" tabindex="-1"></a>cob_crudo  <span class="op">=</span> ((real <span class="op">&gt;=</span> ic_c_lo.values) <span class="op">&amp;</span> (real <span class="op">&lt;=</span> ic_c_hi.values)).mean()</span>
<span id="cb34-22"><a href="#cb34-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"MAE  AR(2) sobre crudo   = </span><span class="sc">{</span>mae_crudo<span class="sc">:.2f}</span><span class="ss"> m/s   (vs ARMA(2,1)+clima = </span><span class="sc">{</span>mae<span class="sc">:.2f}</span><span class="ss">)"</span>)</span>
<span id="cb34-23"><a href="#cb34-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"RMSE AR(2) sobre crudo   = </span><span class="sc">{</span>rmse_crudo<span class="sc">:.2f}</span><span class="ss"> m/s   (vs ARMA(2,1)+clima = </span><span class="sc">{</span>rmse<span class="sc">:.2f}</span><span class="ss">)"</span>)</span>
<span id="cb34-24"><a href="#cb34-24" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Cobertura IC 95%         = </span><span class="sc">{</span>cob_crudo<span class="op">*</span><span class="dv">100</span><span class="sc">:.0f}</span><span class="ss">%"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>/Users/gbv/anomalias-2026-2/.venv/lib/python3.13/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency h will be used.
  self._init_dates(dates, freq)
/Users/gbv/anomalias-2026-2/.venv/lib/python3.13/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency h will be used.
  self._init_dates(dates, freq)
/Users/gbv/anomalias-2026-2/.venv/lib/python3.13/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency h will be used.
  self._init_dates(dates, freq)</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="014b_LaVentosa_files/figure-html/cell-16-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>MAE  AR(2) sobre crudo   = 1.07 m/s   (vs ARMA(2,1)+clima = 0.73)
RMSE AR(2) sobre crudo   = 1.31 m/s   (vs ARMA(2,1)+clima = 0.85)
Cobertura IC 95%         = 100%</code></pre>
</div>
</div>
<p><strong>Lectura del pronóstico crudo.</strong></p>
<ul>
<li>El pronóstico (rojo) es <strong>prácticamente una línea recta</strong> que sube despacio hacia la media incondicional del viento. El AR(2) crudo <strong>no puede reproducir el ciclo diario</strong> porque ese ciclo no está en sus parámetros — solo está en los datos como estructura repetida que el modelo trata como “ruido autocorrelado” inevitable.</li>
<li>El real (negro) tiene picos y valles obvios cada 12 horas (madrugada baja, tarde alta). El modelo está completamente ciego a eso.</li>
<li>El IC 95% es <strong>mucho más ancho</strong> que el del modelo anterior — para “cubrir” los extremos del ciclo, el modelo debe inflar la varianza incondicional.</li>
</ul>
<p><strong>Tabla comparativa final.</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 49%">
<col style="width: 13%">
<col style="width: 15%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>Modelo</th>
<th>MAE (m/s)</th>
<th>RMSE (m/s)</th>
<th>Reproduce ciclo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Persistencia ingenua (anomalía)</td>
<td>0.53</td>
<td>—</td>
<td>sí (vía lag 24)</td>
</tr>
<tr class="even">
<td>ARMA(2,1) sobre anomalía + climatología</td>
<td>0.73</td>
<td>0.85</td>
<td>sí</td>
</tr>
<tr class="odd">
<td><strong>AR(2) directo sobre crudo</strong></td>
<td><strong>1.07</strong></td>
<td><strong>1.31</strong></td>
<td><strong>NO</strong></td>
</tr>
</tbody>
</table>
<p>Sin desestacionalizar, ARMA queda <strong>peor que un baseline ingenuo</strong> y <strong>peor que el mismo ARMA aplicado a la anomalía</strong>. Esa pérdida no es un error de implementación — es <strong>la consecuencia estructural</strong> de meter una estructura determinista por la fuerza en un modelo que no la sabe modelar.</p>
<p><strong>Esa es la frontera de aplicabilidad de ARMA.</strong> Cuando la ACF residual muestra picos periódicos, ARMA terminó su trabajo. Lo que sigue:</p>
<ul>
<li><strong>SARIMA</strong> <span class="math inline">\((p, d, q)(P, D, Q)_s\)</span> — ARIMA con componente estacional explícito de período <span class="math inline">\(s\)</span>. Es la respuesta directa al problema que acabas de ver.</li>
<li><strong>SARIMAX</strong> — SARIMA + variables exógenas (radiación, presión, índices climáticos).</li>
<li><strong>Modelos espacio-estados</strong> — descomposición estructural y filtros de Kalman.</li>
</ul>
<p>Esa es la próxima sesión. Esta termina aquí: con la frontera identificada y el siguiente modelo motivado por <strong>necesidad observada</strong>, no por currículum.</p>
<blockquote class="blockquote">
<p><strong>Cierre con la clase (preguntas de salida).</strong> - En una frase: <strong>¿qué hace AR diferente de MA?</strong> (AR usa pasado <em>observado</em>; MA usa pasado <em>de innovaciones</em>. Una es inercia; la otra es eco de choques). - ¿Cuál es <strong>la única figura</strong> que el alumno debe poder dibujar de memoria? (El ciclo Box-Jenkins: identificar → estimar → diagnosticar → loop). - ¿En qué <strong>dos pruebas</strong> confía Box-Jenkins? (ADF para estacionariedad de la serie; Ljung-Box para blancura de los residuales).</p>
</blockquote>
</section>
</section>
</section>
<section id="cierre-y-materiales-adicionales" class="level1" data-number="17">
<h1 data-number="17"><span class="header-section-number">17</span> Cierre y materiales adicionales</h1>
<section id="lo-que-te-llevas" class="level2" data-number="17.1">
<h2 data-number="17.1" class="anchored" data-anchor-id="lo-que-te-llevas"><span class="header-section-number">17.1</span> Lo que te llevas</h2>
<ol type="1">
<li><strong>Identificar antes de estimar.</strong> ADF + ACF + PACF te dicen qué orden probar <em>antes</em> de tocar <code>ARIMA(...)</code>.</li>
<li><strong>Diagnosticar antes de creerle al modelo.</strong> Ljung-Box sobre residuales es no negociable. Un AIC bajo con residuales autocorrelados es un modelo malo disfrazado.</li>
<li><strong>Iterar con criterio.</strong> Subir orden cuando Ljung-Box rechaza; parar cuando no rechaza Y los nuevos coeficientes no son significativos.</li>
<li><strong>Saber el límite.</strong> Si subir orden no apaga la autocorrelación, el problema no se resuelve dentro de ARMA — necesitas una herramienta más rica.</li>
</ol>
</section>
<section id="ejercicios-para-entregar" class="level2" data-number="17.2">
<h2 data-number="17.2" class="anchored" data-anchor-id="ejercicios-para-entregar"><span class="header-section-number">17.2</span> Ejercicios para entregar</h2>
<ol type="1">
<li>Descarga viento horario de <strong>otro mes</strong> (ene–mar) para La Ventosa. ¿<span class="math inline">\(\phi_1\)</span> y <span class="math inline">\(\phi_2\)</span> cambian? Intenta justificar físicamente por qué tendría sentido que cambiaran (régimen sinóptico vs régimen térmico).</li>
<li>Sobre el ARMA(2,1) ya ajustado, repite el pronóstico con <strong>horizonte de 72 h</strong> y discute cómo se compara la incertidumbre del modelo con la variabilidad real esperada del viento.</li>
<li>Ajusta deliberadamente AR(5) y ARMA(3,2) sobre la anomalía. ¿Cuál gana en AIC? ¿Cuál gana en parsimonia? ¿Cuál elegirías para producción y por qué?</li>
</ol>
</section>
<section id="lecturas" class="level2" data-number="17.3">
<h2 data-number="17.3" class="anchored" data-anchor-id="lecturas"><span class="header-section-number">17.3</span> Lecturas</h2>
<ul>
<li>Box, Jenkins, Reinsel, Ljung (2015). <em>Time Series Analysis: Forecasting and Control</em> (5th ed.). Caps. 3–4.</li>
<li>Cryer &amp; Chan (2008). <em>Time Series Analysis: With Applications in R</em>. Caps. 4–6.</li>
<li>Hyndman &amp; Athanasopoulos. <em>Forecasting: Principles and Practice</em>. https://otexts.com/fpp3/ (cap. 9).</li>
</ul>
</section>
<section id="apéndice-descarga-del-csv" class="level2" data-number="17.4">
<h2 data-number="17.4" class="anchored" data-anchor-id="apéndice-descarga-del-csv"><span class="header-section-number">17.4</span> Apéndice · descarga del CSV</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb37"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="ex">curl</span> <span class="st">"https://archive-api.open-meteo.com/v1/archive?</span><span class="dt">\</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="st">latitude=16.55&amp;longitude=-94.78&amp;</span><span class="dt">\</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="st">start_date=2023-06-01&amp;end_date=2023-08-31&amp;</span><span class="dt">\</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="st">hourly=wind_speed_10m&amp;format=csv&amp;</span><span class="dt">\</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a><span class="st">timezone=America%2FMexico_City"</span> <span class="dt">\</span></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">-o</span> data/viento_la_ventosa_2023.csv</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Open-Meteo entrega reanálisis ERA5 sin autenticación. Calidad comparable a NREL WIND Toolkit para evaluación de recurso.</p>
<p>Cita: &gt; Hersbach, H., et al.&nbsp;(2020). <em>The ERA5 global reanalysis</em>. QJRMS, 146, 1999–2049.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../notebooks/011_laboratorio_climalab.html" class="pagination-link" aria-label="Sesión 1 · Laboratorio">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Sesión 1 · Laboratorio</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../notebooks/015_ARMA_Cheatsheet.html" class="pagination-link" aria-label="ARMA Cheatsheet · Box-Jenkins de bolsillo">
        <span class="nav-page-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">ARMA Cheatsheet · Box-Jenkins de bolsillo</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>