<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>16&nbsp; 016 · SARIMA · Laboratorio · La Ventosa, Oaxaca – Anomalías 2026-2</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../notebooks/017_SARIMA.html" rel="next">
<link href="../notebooks/015_ARMA_Cheatsheet.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-5ccb035bea26c1e21f80f44cf7c27909.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../notebooks/001_birthday_problem.html">Clases</a></li><li class="breadcrumb-item"><a href="../notebooks/016_SARIMA_LaVentosa_src.html"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">016 · SARIMA · Laboratorio · La Ventosa, Oaxaca</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Anomalías 2026-2</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prefacio</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../libro/intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introducción</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Clases</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/001_birthday_problem.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">El problema del cumpleaños</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/002_triangulo_pascal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">002_triangulo_pascal.html</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/003_sampling_distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">003_sampling_distribution.html</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/004_Central_limit_teorem.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">004_Central_limit_teorem.html</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/005_DistribucionNormal_Seleccion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">005_DistribucionNormal_Seleccion.html</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/006_experimentos_nueve.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">006_experimentos_nueve.html</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/007_muestreo_teoria.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Semana 4A — Muestreo y Estimación (Teoría)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/008a_muestreo_lab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Semana 4B — Muestreo y Estimación (Laboratorio)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/008b_muestreo_lab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">1. Cargar y conocer la población</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/009_PruebasHipotesis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title"><code>stats.t.ppf(1 - alpha/2, gl)</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/010_teoria_componentes_y_descomposicion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Sesión 1 · Teoría</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/011_laboratorio_climalab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Sesión 1 · Laboratorio</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/014b_LaVentosa.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">AR-MA · Laboratorio · La Ventosa, Oaxaca</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/015_ARMA_Cheatsheet.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">ARMA Cheatsheet · Box-Jenkins de bolsillo</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/016_SARIMA_LaVentosa_src.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">016 · SARIMA · Laboratorio · La Ventosa, Oaxaca</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/017_SARIMA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">SARIMA — del modelo a un ejemplo con viento</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/018_sarima_esolmet.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">018_sarima_esolmet.html</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/019_tdb_teoria_exploracion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">019 · Introducción a SARIMA + exploración de <code>tdb</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/020_tdb_configuracion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">020 · Configurar SARIMA desde el código — <code>tdb</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/021_tdb_outliers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">021 · Detección de outliers con SARIMA — <code>tdb</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/022_temario_sarimax.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Temario · Aprender SARIMAX desde cero (perfil ingeniería)</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#setup" id="toc-setup" class="nav-link active" data-scroll-target="#setup"><span class="header-section-number">16.1</span> Setup</a></li>
  <li><a href="#bloque-1-sarima-conceptos-clave" id="toc-bloque-1-sarima-conceptos-clave" class="nav-link" data-scroll-target="#bloque-1-sarima-conceptos-clave"><span class="header-section-number">17</span> Bloque 1 · SARIMA — conceptos clave</a>
  <ul class="collapse">
  <li><a href="#operador-de-retraso-b-vocabulario-común" id="toc-operador-de-retraso-b-vocabulario-común" class="nav-link" data-scroll-target="#operador-de-retraso-b-vocabulario-común"><span class="header-section-number">17.1</span> Operador de retraso <span class="math inline">\(B\)</span> — vocabulario común</a></li>
  <li><a href="#sarima-p-d-qp-d-q_s-la-ecuación" id="toc-sarima-p-d-qp-d-q_s-la-ecuación" class="nav-link" data-scroll-target="#sarima-p-d-qp-d-q_s-la-ecuación"><span class="header-section-number">17.2</span> SARIMA <span class="math inline">\((p, d, q)(P, D, Q)_s\)</span> — la ecuación</a>
  <ul class="collapse">
  <li><a href="#cómo-desplegar-los-polinomios-estacionales" id="toc-cómo-desplegar-los-polinomios-estacionales" class="nav-link" data-scroll-target="#cómo-desplegar-los-polinomios-estacionales"><span class="header-section-number">17.2.1</span> Cómo desplegar los polinomios estacionales</a></li>
  </ul></li>
  <li><a href="#el-airline-model-el-clásico-que-define-la-familia" id="toc-el-airline-model-el-clásico-que-define-la-familia" class="nav-link" data-scroll-target="#el-airline-model-el-clásico-que-define-la-familia"><span class="header-section-number">17.3</span> El “Airline model” — el clásico que define la familia</a></li>
  <li><a href="#diferenciación-estacional-nabla_s-qué-hace-y-cuándo-aplicarla" id="toc-diferenciación-estacional-nabla_s-qué-hace-y-cuándo-aplicarla" class="nav-link" data-scroll-target="#diferenciación-estacional-nabla_s-qué-hace-y-cuándo-aplicarla"><span class="header-section-number">17.4</span> Diferenciación estacional <span class="math inline">\(\nabla_s\)</span> — qué hace y cuándo aplicarla</a>
  <ul class="collapse">
  <li><a href="#nabla_24-vs-restar-climatología-no-es-lo-mismo" id="toc-nabla_24-vs-restar-climatología-no-es-lo-mismo" class="nav-link" data-scroll-target="#nabla_24-vs-restar-climatología-no-es-lo-mismo"><span class="header-section-number">17.4.1</span> <span class="math inline">\(\nabla_{24}\)</span> vs restar climatología — ¿no es lo mismo?</a></li>
  </ul></li>
  <li><a href="#identificación-sarima-leer-acfpacf-a-dos-escalas" id="toc-identificación-sarima-leer-acfpacf-a-dos-escalas" class="nav-link" data-scroll-target="#identificación-sarima-leer-acfpacf-a-dos-escalas"><span class="header-section-number">17.5</span> Identificación SARIMA — leer ACF/PACF a dos escalas</a></li>
  <li><a href="#helpers-los-dos-pasos-del-ciclo-codificados-para-sarima" id="toc-helpers-los-dos-pasos-del-ciclo-codificados-para-sarima" class="nav-link" data-scroll-target="#helpers-los-dos-pasos-del-ciclo-codificados-para-sarima"><span class="header-section-number">17.6</span> Helpers — los dos pasos del ciclo, codificados para SARIMA</a></li>
  </ul></li>
  <li><a href="#bloque-2-laboratorio-45-min" id="toc-bloque-2-laboratorio-45-min" class="nav-link" data-scroll-target="#bloque-2-laboratorio-45-min"><span class="header-section-number">18</span> Bloque 2 · Laboratorio (45 min)</a>
  <ul class="collapse">
  <li><a href="#p1-los-datos-la-ventosa-oaxaca-3-min" id="toc-p1-los-datos-la-ventosa-oaxaca-3-min" class="nav-link" data-scroll-target="#p1-los-datos-la-ventosa-oaxaca-3-min"><span class="header-section-number">18.1</span> P1 · Los datos · La Ventosa, Oaxaca · 3 min</a></li>
  <li><a href="#p2-recordatorio-el-ciclo-diario-que-arma-no-pudo-5-min" id="toc-p2-recordatorio-el-ciclo-diario-que-arma-no-pudo-5-min" class="nav-link" data-scroll-target="#p2-recordatorio-el-ciclo-diario-que-arma-no-pudo-5-min"><span class="header-section-number">18.2</span> P2 · Recordatorio · el ciclo diario que ARMA no pudo · 5 min</a></li>
  <li><a href="#p3-identificación-sarima-10-min" id="toc-p3-identificación-sarima-10-min" class="nav-link" data-scroll-target="#p3-identificación-sarima-10-min"><span class="header-section-number">18.3</span> P3 · Identificación SARIMA · 10 min</a>
  <ul class="collapse">
  <li><a href="#paso-1-diferenciación-estacional-nabla_24" id="toc-paso-1-diferenciación-estacional-nabla_24" class="nav-link" data-scroll-target="#paso-1-diferenciación-estacional-nabla_24"><span class="header-section-number">18.3.1</span> Paso 1 — diferenciación estacional <span class="math inline">\(\nabla_{24}\)</span></a></li>
  </ul></li>
  <li><a href="#p4-iteración-box-jenkins-con-sarima-15-min" id="toc-p4-iteración-box-jenkins-con-sarima-15-min" class="nav-link" data-scroll-target="#p4-iteración-box-jenkins-con-sarima-15-min"><span class="header-section-number">18.4</span> P4 · Iteración Box-Jenkins con SARIMA · 15 min</a>
  <ul class="collapse">
  <li><a href="#iteración-1-sarima0-0-00-1-1_24-solo-bloque-estacional" id="toc-iteración-1-sarima0-0-00-1-1_24-solo-bloque-estacional" class="nav-link" data-scroll-target="#iteración-1-sarima0-0-00-1-1_24-solo-bloque-estacional"><span class="header-section-number">18.4.1</span> Iteración 1 · SARIMA(0, 0, 0)(0, 1, 1)_24 — solo bloque estacional</a></li>
  <li><a href="#iteración-2-sarima2-0-00-1-1_24-agregamos-ar2" id="toc-iteración-2-sarima2-0-00-1-1_24-agregamos-ar2" class="nav-link" data-scroll-target="#iteración-2-sarima2-0-00-1-1_24-agregamos-ar2"><span class="header-section-number">18.4.2</span> Iteración 2 · SARIMA(2, 0, 0)(0, 1, 1)_24 — agregamos AR(2)</a></li>
  <li><a href="#iteración-3-sarima2-0-10-1-1_24-la-versión-airline-para-viento" id="toc-iteración-3-sarima2-0-10-1-1_24-la-versión-airline-para-viento" class="nav-link" data-scroll-target="#iteración-3-sarima2-0-10-1-1_24-la-versión-airline-para-viento"><span class="header-section-number">18.4.3</span> Iteración 3 · SARIMA(2, 0, 1)(0, 1, 1)_24 — la versión “airline para viento”</a></li>
  <li><a href="#resumen-comparativo-tres-iteraciones-sarima" id="toc-resumen-comparativo-tres-iteraciones-sarima" class="nav-link" data-scroll-target="#resumen-comparativo-tres-iteraciones-sarima"><span class="header-section-number">18.4.4</span> Resumen comparativo · tres iteraciones SARIMA</a></li>
  </ul></li>
  <li><a href="#p5-pronóstico-y-comparativo-final-12-min" id="toc-p5-pronóstico-y-comparativo-final-12-min" class="nav-link" data-scroll-target="#p5-pronóstico-y-comparativo-final-12-min"><span class="header-section-number">18.5</span> P5 · Pronóstico y comparativo final · 12 min</a>
  <ul class="collapse">
  <li><a href="#setup-del-backtest" id="toc-setup-del-backtest" class="nav-link" data-scroll-target="#setup-del-backtest"><span class="header-section-number">18.5.1</span> Setup del backtest</a></li>
  <li><a href="#modelo-1-arma2-1-sobre-anomalía-climatología" id="toc-modelo-1-arma2-1-sobre-anomalía-climatología" class="nav-link" data-scroll-target="#modelo-1-arma2-1-sobre-anomalía-climatología"><span class="header-section-number">18.5.2</span> Modelo 1 · ARMA(2, 1) sobre anomalía + climatología</a></li>
  <li><a href="#modelo-2-sarima2-0-10-1-1_24-sobre-crudo" id="toc-modelo-2-sarima2-0-10-1-1_24-sobre-crudo" class="nav-link" data-scroll-target="#modelo-2-sarima2-0-10-1-1_24-sobre-crudo"><span class="header-section-number">18.5.3</span> Modelo 2 · SARIMA(2, 0, 1)(0, 1, 1)_24 sobre crudo</a></li>
  <li><a href="#baseline-persistencia-24-h" id="toc-baseline-persistencia-24-h" class="nav-link" data-scroll-target="#baseline-persistencia-24-h"><span class="header-section-number">18.5.4</span> Baseline · persistencia 24 h</a></li>
  <li><a href="#figura-única-los-tres-pronósticos-contra-el-real" id="toc-figura-única-los-tres-pronósticos-contra-el-real" class="nav-link" data-scroll-target="#figura-única-los-tres-pronósticos-contra-el-real"><span class="header-section-number">18.5.5</span> Figura única — los tres pronósticos contra el real</a></li>
  <li><a href="#tabla-comparativa" id="toc-tabla-comparativa" class="nav-link" data-scroll-target="#tabla-comparativa"><span class="header-section-number">18.5.6</span> Tabla comparativa</a></li>
  <li><a href="#lectura-final-hay-mejora" id="toc-lectura-final-hay-mejora" class="nav-link" data-scroll-target="#lectura-final-hay-mejora"><span class="header-section-number">18.5.7</span> Lectura final · ¿hay mejora?</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#cierre-y-materiales-adicionales" id="toc-cierre-y-materiales-adicionales" class="nav-link" data-scroll-target="#cierre-y-materiales-adicionales"><span class="header-section-number">19</span> Cierre y materiales adicionales</a>
  <ul class="collapse">
  <li><a href="#lo-que-te-llevas" id="toc-lo-que-te-llevas" class="nav-link" data-scroll-target="#lo-que-te-llevas"><span class="header-section-number">19.1</span> Lo que te llevas</a></li>
  <li><a href="#ejercicios-para-entregar" id="toc-ejercicios-para-entregar" class="nav-link" data-scroll-target="#ejercicios-para-entregar"><span class="header-section-number">19.2</span> Ejercicios para entregar</a></li>
  <li><a href="#lecturas" id="toc-lecturas" class="nav-link" data-scroll-target="#lecturas"><span class="header-section-number">19.3</span> Lecturas</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../notebooks/001_birthday_problem.html">Clases</a></li><li class="breadcrumb-item"><a href="../notebooks/016_SARIMA_LaVentosa_src.html"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">016 · SARIMA · Laboratorio · La Ventosa, Oaxaca</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">016 · SARIMA · Laboratorio · La Ventosa, Oaxaca</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><strong>Estadística, Detección de Anomalías e Imputación de Series Temporales</strong> Posgrado en Ingeniería · Área Energía · IER-UNAM</p>
<p>Documento <strong>autocontenido</strong>: el Bloque 1 fija conceptos de SARIMA y el Bloque 2 ejecuta el laboratorio completo (45 min) repitiendo el ejercicio de La Ventosa <em>del lab anterior</em> (014b) ahora con SARIMA, y comparando contra el enfoque <strong>integrado</strong> (ARMA(2,1) sobre anomalía + climatología).</p>
<p><strong>Lo que cierra este lab.</strong> En 014b vimos que ARMA no puede capturar el ciclo diario y que, para que funcionara, hubo que <strong>restar climatología por hora</strong> y modelar la anomalía. Esa solución es <em>modular</em> — separa lo determinista de lo estocástico — pero requiere preprocesar la serie por fuera del modelo. SARIMA es la alternativa <strong>integrada</strong>: el componente estacional vive dentro del modelo y la estacionalidad se absorbe sin restar nada a mano.</p>
<section id="setup" class="level2" data-number="16.1">
<h2 data-number="16.1" class="anchored" data-anchor-id="setup"><span class="header-section-number">16.1</span> Setup</h2>
<div id="e44dd14e" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-05-27T17:52:23.523655Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-05-27T17:52:23.523487Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-05-27T17:52:24.184377Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-05-27T17:52:24.183947Z&quot;}}" data-execution_count="1">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.tsa.arima.model <span class="im">import</span> ARIMA</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.tsa.statespace.sarimax <span class="im">import</span> SARIMAX</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.tsa.stattools <span class="im">import</span> adfuller</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.graphics.tsaplots <span class="im">import</span> plot_acf, plot_pacf</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.stats.diagnostic <span class="im">import</span> acorr_ljungbox</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>plt.rcParams[<span class="st">"figure.figsize"</span>] <span class="op">=</span> (<span class="dv">11</span>, <span class="dv">4</span>)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>plt.rcParams[<span class="st">"axes.grid"</span>] <span class="op">=</span> <span class="va">True</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>plt.rcParams[<span class="st">"grid.alpha"</span>] <span class="op">=</span> <span class="fl">0.3</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">42</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="bloque-1-sarima-conceptos-clave" class="level1" data-number="17">
<h1 data-number="17"><span class="header-section-number">17</span> Bloque 1 · SARIMA — conceptos clave</h1>
<p>Recogemos el hilo donde se quedó 014b: ARMA modela bien la dinámica estocástica pero <strong>no</strong> la estructura periódica determinista. La forma “limpia” de extender ARMA para que sí pueda es SARIMA. Antes de tocar datos fijamos: (i) por qué diferenciar estacionalmente, (ii) la notación <span class="math inline">\((p, d, q)(P, D, Q)_s\)</span>, (iii) cómo se leen los órdenes estacionales en la ACF/PACF.</p>
<section id="operador-de-retraso-b-vocabulario-común" class="level2" data-number="17.1">
<h2 data-number="17.1" class="anchored" data-anchor-id="operador-de-retraso-b-vocabulario-común"><span class="header-section-number">17.1</span> Operador de retraso <span class="math inline">\(B\)</span> — vocabulario común</h2>
<p>Antes de escribir SARIMA, fijamos notación. El <strong>operador de retraso</strong> <span class="math inline">\(B\)</span> (<em>backshift</em>) se define como</p>
<p><span class="math display">\[B\, y_t \;=\; y_{t-1}, \qquad B^k\, y_t \;=\; y_{t-k}.\]</span></p>
<p>Con él, los modelos se escriben compactos. Un AR(2):</p>
<p><span class="math display">\[y_t = \phi_1\, y_{t-1} + \phi_2\, y_{t-2} + \varepsilon_t
\;\;\Longleftrightarrow\;\;
(1 - \phi_1 B - \phi_2 B^2)\, y_t \;=\; \varepsilon_t.\]</span></p>
<p>La <strong>diferencia ordinaria</strong> se vuelve un polinomio en <span class="math inline">\(B\)</span>:</p>
<p><span class="math display">\[\Delta y_t \;=\; y_t - y_{t-1} \;=\; (1 - B)\, y_t.\]</span></p>
<p>La <strong>diferencia estacional de período <span class="math inline">\(s\)</span></strong>, análogamente:</p>
<p><span class="math display">\[\nabla_s\, y_t \;=\; y_t - y_{t-s} \;=\; (1 - B^s)\, y_t.\]</span></p>
<p>Con esto SARIMA se escribe en una sola línea, sin sumatorias.</p>
</section>
<section id="sarima-p-d-qp-d-q_s-la-ecuación" class="level2" data-number="17.2">
<h2 data-number="17.2" class="anchored" data-anchor-id="sarima-p-d-qp-d-q_s-la-ecuación"><span class="header-section-number">17.2</span> SARIMA <span class="math inline">\((p, d, q)(P, D, Q)_s\)</span> — la ecuación</h2>
<p>Un modelo <strong>SARIMA</strong> es ARIMA con un componente estacional explícito de período <span class="math inline">\(s\)</span>. Su forma polinómica es</p>
<p><span class="math display">\[\boxed{\;\;
\underbrace{\Phi_P(B^s)}_{\text{SAR}}\,
\underbrace{\phi_p(B)}_{\text{AR}}\,
\underbrace{(1 - B)^d}_{\text{diff. ord.}}\,
\underbrace{(1 - B^s)^D}_{\text{diff. est.}}\,
y_t
\;=\;
\underbrace{\Theta_Q(B^s)}_{\text{SMA}}\,
\underbrace{\theta_q(B)}_{\text{MA}}\,
\varepsilon_t,
\quad \varepsilon_t \sim \text{WN}(0, \sigma^2).
\;\;}\]</span></p>
<p>Hay <strong>siete números</strong> que la definen:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 45%">
<col style="width: 44%">
</colgroup>
<thead>
<tr class="header">
<th>Símbolo</th>
<th>Qué cuenta</th>
<th>Cómo se elige</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(p\)</span></td>
<td>rezagos AR no estacionales</td>
<td>PACF de la serie diferenciada</td>
</tr>
<tr class="even">
<td><span class="math inline">\(d\)</span></td>
<td>diferencias ordinarias</td>
<td>ADF (raíz unitaria)</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(q\)</span></td>
<td>rezagos MA no estacionales</td>
<td>ACF de la serie diferenciada</td>
</tr>
<tr class="even">
<td><span class="math inline">\(P\)</span></td>
<td>rezagos AR <strong>estacionales</strong> (en <span class="math inline">\(B^s\)</span>)</td>
<td>PACF en lags <span class="math inline">\(s, 2s, 3s\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(D\)</span></td>
<td>diferencias <strong>estacionales</strong> <span class="math inline">\(\nabla_s\)</span></td>
<td>persistencia de picos estacionales</td>
</tr>
<tr class="even">
<td><span class="math inline">\(Q\)</span></td>
<td>rezagos MA <strong>estacionales</strong> (en <span class="math inline">\(B^s\)</span>)</td>
<td>ACF en lags <span class="math inline">\(s, 2s, 3s\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(s\)</span></td>
<td><strong>período</strong> de la estacionalidad</td>
<td>físico (24 h, 12 meses, 7 días, …)</td>
</tr>
</tbody>
</table>
<p><strong>Caso degenerado.</strong> Con <span class="math inline">\(P = D = Q = 0\)</span>, SARIMA colapsa a ARIMA. Con <span class="math inline">\(d = D = 0\)</span> y <span class="math inline">\(P = Q = 0\)</span>, colapsa a ARMA. Es decir, ARMA y ARIMA son <strong>subconjuntos</strong> de SARIMA.</p>
<section id="cómo-desplegar-los-polinomios-estacionales" class="level3" data-number="17.2.1">
<h3 data-number="17.2.1" class="anchored" data-anchor-id="cómo-desplegar-los-polinomios-estacionales"><span class="header-section-number">17.2.1</span> Cómo desplegar los polinomios estacionales</h3>
<p>Los polinomios <span class="math inline">\(\Phi_P(B^s)\)</span> y <span class="math inline">\(\Theta_Q(B^s)\)</span> se ven raros la primera vez porque usan <span class="math inline">\(B^s\)</span> en lugar de <span class="math inline">\(B\)</span>. Significan lo mismo que sus análogos ordinarios, pero <strong>espaciados en múltiplos de <span class="math inline">\(s\)</span></strong>:</p>
<p><span class="math display">\[\Phi_P(B^s) \;=\; 1 - \Phi_1\, B^s - \Phi_2\, B^{2s} - \cdots - \Phi_P\, B^{Ps},\]</span> <span class="math display">\[\Theta_Q(B^s) \;=\; 1 + \Theta_1\, B^s + \Theta_2\, B^{2s} + \cdots + \Theta_Q\, B^{Qs}.\]</span></p>
<p><em>Lectura intuitiva:</em> <span class="math inline">\(\Phi_1\)</span> es la AR “de un día atrás a hoy” (cuando <span class="math inline">\(s = 24\)</span>); <span class="math inline">\(\Theta_1\)</span> es la MA “del choque de hace un día al de hoy”. Conectan instantes que están <strong>a un período de distancia</strong>, no a un paso.</p>
</section>
</section>
<section id="el-airline-model-el-clásico-que-define-la-familia" class="level2" data-number="17.3">
<h2 data-number="17.3" class="anchored" data-anchor-id="el-airline-model-el-clásico-que-define-la-familia"><span class="header-section-number">17.3</span> El “Airline model” — el clásico que define la familia</h2>
<p>Box y Jenkins (1976), analizando pasajeros mensuales de aerolíneas, propusieron</p>
<p><span class="math display">\[\text{SARIMA}(0,\,1,\,1)(0,\,1,\,1)_{12} \;:\;
(1 - B)(1 - B^{12})\, y_t \;=\; (1 + \theta_1 B)(1 + \Theta_1 B^{12})\, \varepsilon_t.\]</span></p>
<p>Solo dos parámetros — <span class="math inline">\(\theta_1\)</span> y <span class="math inline">\(\Theta_1\)</span> — y se ajusta a una cantidad enorme de series económicas y de demanda. Su éxito viene de combinar:</p>
<ul>
<li><strong>Diferencia ordinaria</strong> <span class="math inline">\((1 - B)\)</span> → mata tendencia lineal.</li>
<li><strong>Diferencia estacional</strong> <span class="math inline">\((1 - B^{12})\)</span> → mata el ciclo anual.</li>
<li><strong>MA no estacional</strong> <span class="math inline">\(\theta_1\)</span> → suaviza ruido de corto plazo.</li>
<li><strong>MA estacional</strong> <span class="math inline">\(\Theta_1\)</span> → suaviza el “eco del año pasado”.</li>
</ul>
<p>Para datos horarios con ciclo diario, el análogo es <span class="math inline">\(\text{SARIMA}(p,\, d,\, q)(P,\, 1,\, Q)_{24}\)</span> con <span class="math inline">\(D = 1\)</span>. Ese es el punto de partida natural para La Ventosa.</p>
</section>
<section id="diferenciación-estacional-nabla_s-qué-hace-y-cuándo-aplicarla" class="level2" data-number="17.4">
<h2 data-number="17.4" class="anchored" data-anchor-id="diferenciación-estacional-nabla_s-qué-hace-y-cuándo-aplicarla"><span class="header-section-number">17.4</span> Diferenciación estacional <span class="math inline">\(\nabla_s\)</span> — qué hace y cuándo aplicarla</h2>
<p>Aplicar <span class="math inline">\(\nabla_{24}\)</span> a una serie horaria es restarle el valor de la misma hora del día anterior:</p>
<p><span class="math display">\[z_t \;=\; \nabla_{24}\, y_t \;=\; y_t - y_{t-24}.\]</span></p>
<p><em>Efecto físico:</em> elimina cualquier patrón que se <strong>repita igual cada 24 horas</strong>. Si el viento tiene un ciclo diario determinista, <span class="math inline">\(\nabla_{24}\)</span> lo borra.</p>
<p><strong>Regla operativa.</strong> Pon <span class="math inline">\(D = 1\)</span> cuando:</p>
<ol type="1">
<li>La ACF muestra <strong>picos persistentes</strong> en lags <span class="math inline">\(s,\, 2s,\, 3s\)</span> que no decaen, o</li>
<li>La climatología (media por hora) tiene amplitud comparable o mayor que la desviación estándar de la anomalía.</li>
</ol>
<p>Casi nunca se usa <span class="math inline">\(D \geq 2\)</span> — sobre-diferenciar estacionalmente inyecta MA espurios y dispara la varianza del pronóstico.</p>
<section id="nabla_24-vs-restar-climatología-no-es-lo-mismo" class="level3" data-number="17.4.1">
<h3 data-number="17.4.1" class="anchored" data-anchor-id="nabla_24-vs-restar-climatología-no-es-lo-mismo"><span class="header-section-number">17.4.1</span> <span class="math inline">\(\nabla_{24}\)</span> vs restar climatología — ¿no es lo mismo?</h3>
<p><strong>No exactamente.</strong> Ambas estrategias matan el ciclo diario, pero por mecanismos distintos:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 29%">
<col style="width: 42%">
<col style="width: 28%">
</colgroup>
<thead>
<tr class="header">
<th>Estrategia</th>
<th>Qué hace</th>
<th>Modelo de la estacionalidad</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Restar climatología por hora</td>
<td><span class="math inline">\(y_t - \bar{y}(h)\)</span>, con <span class="math inline">\(\bar{y}(h)\)</span> fija</td>
<td><strong>Determinista</strong>: el mismo patrón cada día</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\nabla_{24}\, y_t\)</span></td>
<td><span class="math inline">\(y_t - y_{t-24}\)</span></td>
<td><strong>Estocástica</strong>: el patrón puede evolucionar día a día</td>
</tr>
</tbody>
</table>
<ul>
<li>La climatología asume que el ciclo es <strong>idéntico</strong> en todos los días del verano. Bueno para regímenes estables; rígido cuando hay desfases de fase con frentes meteorológicos.</li>
<li><span class="math inline">\(\nabla_{24}\)</span> permite que el ciclo cambie de forma lenta de un día al siguiente. Mejor para series largas donde la estacionalidad respira.</li>
</ul>
<blockquote class="blockquote">
<p><strong>Práctico.</strong> En 014b restamos climatología → modelo modular limpio. Aquí usamos <span class="math inline">\(\nabla_{24}\)</span> dentro de SARIMA → modelo integrado más flexible. Veremos en P5 qué gana cada uno en backtest.</p>
</blockquote>
</section>
</section>
<section id="identificación-sarima-leer-acfpacf-a-dos-escalas" class="level2" data-number="17.5">
<h2 data-number="17.5" class="anchored" data-anchor-id="identificación-sarima-leer-acfpacf-a-dos-escalas"><span class="header-section-number">17.5</span> Identificación SARIMA — leer ACF/PACF a dos escalas</h2>
<p>Para identificar <span class="math inline">\((p, q)\)</span> y <span class="math inline">\((P, Q)\)</span> se mira la <strong>misma</strong> ACF/PACF, pero a rangos de lags distintos:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 30%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th>Pregunta</th>
<th>Mirar lags…</th>
<th>Para decidir</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(p, q\)</span> (no estacional)</td>
<td><strong>1, 2, 3, …, <span class="math inline">\(s-1\)</span></strong></td>
<td>rezagos cortos</td>
</tr>
<tr class="even">
<td><span class="math inline">\(P, Q\)</span> (estacional)</td>
<td><strong><span class="math inline">\(s, 2s, 3s, \dots\)</span></strong></td>
<td>rezagos a múltiplos del período</td>
</tr>
</tbody>
</table>
<p>Las reglas de “corta vs decae” del lab pasado se aplican <strong>dos veces</strong>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Patrón en lags estacionales</th>
<th>Lectura</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ACF en <span class="math inline">\(s, 2s, 3s\)</span> corta tras <span class="math inline">\(Q\cdot s\)</span>, PACF decae</td>
<td><strong>SMA(Q)</strong></td>
</tr>
<tr class="even">
<td>PACF en <span class="math inline">\(s, 2s, 3s\)</span> corta tras <span class="math inline">\(P\cdot s\)</span>, ACF decae</td>
<td><strong>SAR(P)</strong></td>
</tr>
<tr class="odd">
<td>Ambas decaen estacionalmente</td>
<td><strong>SARMA(P, Q)</strong></td>
</tr>
</tbody>
</table>
<p><strong>Lo más típico en datos físicos con ciclo diario fuerte:</strong> después de <span class="math inline">\(\nabla_{24}\)</span>, la ACF muestra un único pico <strong>negativo</strong> grande en lag <span class="math inline">\(s\)</span> y nada en <span class="math inline">\(2s, 3s\)</span> → patrón clásico de <strong>SMA(1)</strong> estacional → <span class="math inline">\(Q = 1\)</span>.</p>
</section>
<section id="helpers-los-dos-pasos-del-ciclo-codificados-para-sarima" class="level2" data-number="17.6">
<h2 data-number="17.6" class="anchored" data-anchor-id="helpers-los-dos-pasos-del-ciclo-codificados-para-sarima"><span class="header-section-number">17.6</span> Helpers — los dos pasos del ciclo, codificados para SARIMA</h2>
<p>Reusamos <code>mirar()</code> (idéntico a 014b) y adaptamos <code>diagnostico()</code> para que resuma SARIMA con sus siete números.</p>
<div id="3fac953b" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-05-27T17:52:24.185931Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-05-27T17:52:24.185833Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-05-27T17:52:24.188906Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-05-27T17:52:24.188546Z&quot;}}" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> mirar(serie, nombre, lags<span class="op">=</span><span class="dv">60</span>):</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Identificación: serie temporal + ADF + ACF + PACF."""</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>    serie <span class="op">=</span> pd.Series(serie).dropna()</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    stat, p, <span class="op">*</span>_ <span class="op">=</span> adfuller(serie, autolag<span class="op">=</span><span class="st">"AIC"</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    veredicto <span class="op">=</span> <span class="st">"estacionaria"</span> <span class="cf">if</span> p <span class="op">&lt;</span> <span class="fl">0.05</span> <span class="cf">else</span> <span class="st">"NO estacionaria"</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"ADF · </span><span class="sc">{</span>nombre<span class="sc">}</span><span class="ss">:  estadístico = </span><span class="sc">{</span>stat<span class="sc">:.3f}</span><span class="ss">,  p = </span><span class="sc">{</span>p<span class="sc">:.4f}</span><span class="ss">  →  </span><span class="sc">{</span>veredicto<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>    fig, axes <span class="op">=</span> plt.subplot_mosaic(</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>        [[<span class="st">"serie"</span>, <span class="st">"serie"</span>],</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>         [<span class="st">"acf"</span>,   <span class="st">"pacf"</span>]],</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>        figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">6</span>),</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>    serie.plot(ax<span class="op">=</span>axes[<span class="st">"serie"</span>], lw<span class="op">=</span><span class="fl">0.5</span>, color<span class="op">=</span><span class="st">"C0"</span>)</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>    axes[<span class="st">"serie"</span>].axhline(serie.mean(), color<span class="op">=</span><span class="st">"k"</span>, lw<span class="op">=</span><span class="fl">0.5</span>, alpha<span class="op">=</span><span class="fl">0.5</span>)</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>    axes[<span class="st">"serie"</span>].set_title(<span class="ss">f"Serie — </span><span class="sc">{</span>nombre<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>    plot_acf(serie,  lags<span class="op">=</span>lags, ax<span class="op">=</span>axes[<span class="st">"acf"</span>])<span class="op">;</span>  axes[<span class="st">"acf"</span>].set_title(<span class="ss">f"ACF — </span><span class="sc">{</span>nombre<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>    plot_pacf(serie, lags<span class="op">=</span>lags, ax<span class="op">=</span>axes[<span class="st">"pacf"</span>], method<span class="op">=</span><span class="st">"ywm"</span>)</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>    axes[<span class="st">"pacf"</span>].set_title(<span class="ss">f"PACF — </span><span class="sc">{</span>nombre<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>    plt.tight_layout()<span class="op">;</span> plt.show()</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> diagnostico_sarima(modelo, nombre, lags<span class="op">=</span><span class="dv">48</span>):</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Validación SARIMA: residuales + ACF/PACF residual + Ljung-Box.</span></span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a><span class="co">    Notas:</span></span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a><span class="co">    - Recortamos los primeros `burn-in` residuales (filtro de Kalman aún caliente).</span></span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a><span class="co">    - Miramos lags 24 y 48 además de 10 y 20: cualquier pico en múltiplo de 24</span></span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a><span class="co">      delata estacionalidad sin absorber.</span></span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a>    p, d, q <span class="op">=</span> modelo.model.order</span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a>    P, D, Q, s <span class="op">=</span> modelo.model.seasonal_order</span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a>    burn <span class="op">=</span> <span class="bu">max</span>(p <span class="op">+</span> P <span class="op">*</span> s, q <span class="op">+</span> Q <span class="op">*</span> s, s <span class="op">*</span> D <span class="op">+</span> d) <span class="op">+</span> <span class="dv">1</span></span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a>    resid <span class="op">=</span> pd.Series(modelo.resid).iloc[burn:].dropna()</span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-36"><a href="#cb2-36" aria-hidden="true" tabindex="-1"></a>    fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">3</span>, figsize<span class="op">=</span>(<span class="dv">15</span>, <span class="fl">3.2</span>))</span>
<span id="cb2-37"><a href="#cb2-37" aria-hidden="true" tabindex="-1"></a>    axes[<span class="dv">0</span>].plot(resid.values, lw<span class="op">=</span><span class="fl">0.6</span>)<span class="op">;</span> axes[<span class="dv">0</span>].axhline(<span class="dv">0</span>, color<span class="op">=</span><span class="st">"k"</span>, lw<span class="op">=</span><span class="fl">0.5</span>)</span>
<span id="cb2-38"><a href="#cb2-38" aria-hidden="true" tabindex="-1"></a>    axes[<span class="dv">0</span>].set_title(<span class="ss">f"Residuales — </span><span class="sc">{</span>nombre<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb2-39"><a href="#cb2-39" aria-hidden="true" tabindex="-1"></a>    plot_acf(resid,  lags<span class="op">=</span>lags, ax<span class="op">=</span>axes[<span class="dv">1</span>])<span class="op">;</span> axes[<span class="dv">1</span>].set_title(<span class="st">"ACF de residuales"</span>)</span>
<span id="cb2-40"><a href="#cb2-40" aria-hidden="true" tabindex="-1"></a>    plot_pacf(resid, lags<span class="op">=</span>lags, ax<span class="op">=</span>axes[<span class="dv">2</span>], method<span class="op">=</span><span class="st">"ywm"</span>)</span>
<span id="cb2-41"><a href="#cb2-41" aria-hidden="true" tabindex="-1"></a>    axes[<span class="dv">2</span>].set_title(<span class="st">"PACF de residuales"</span>)</span>
<span id="cb2-42"><a href="#cb2-42" aria-hidden="true" tabindex="-1"></a>    plt.tight_layout()<span class="op">;</span> plt.show()</span>
<span id="cb2-43"><a href="#cb2-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-44"><a href="#cb2-44" aria-hidden="true" tabindex="-1"></a>    lb <span class="op">=</span> acorr_ljungbox(resid, lags<span class="op">=</span>[<span class="dv">10</span>, <span class="dv">20</span>, <span class="dv">24</span>, <span class="dv">48</span>], return_df<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb2-45"><a href="#cb2-45" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"Ljung-Box · </span><span class="sc">{</span>nombre<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb2-46"><a href="#cb2-46" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(lb.<span class="bu">round</span>(<span class="dv">4</span>))</span>
<span id="cb2-47"><a href="#cb2-47" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> lb</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
</section>
<section id="bloque-2-laboratorio-45-min" class="level1" data-number="18">
<h1 data-number="18"><span class="header-section-number">18</span> Bloque 2 · Laboratorio (45 min)</h1>
<section id="p1-los-datos-la-ventosa-oaxaca-3-min" class="level2" data-number="18.1">
<h2 data-number="18.1" class="anchored" data-anchor-id="p1-los-datos-la-ventosa-oaxaca-3-min"><span class="header-section-number">18.1</span> P1 · Los datos · La Ventosa, Oaxaca · 3 min</h2>
<p>Mismos datos que en 014b: viento horario a 10 m, jun–ago 2023, fuente ERA5 vía Open-Meteo. La intención es que el alumno <strong>vea el cambio de herramienta sobre el mismo problema</strong>, sin variables ajenas.</p>
<div id="d12450a5" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-05-27T17:52:24.189848Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-05-27T17:52:24.189796Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-05-27T17:52:24.195217Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-05-27T17:52:24.194880Z&quot;}}" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>viento <span class="op">=</span> pd.read_csv(<span class="st">"../data/viento_la_ventosa_2023.csv"</span>,</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>                     skiprows<span class="op">=</span><span class="dv">3</span>, parse_dates<span class="op">=</span>[<span class="st">"time"</span>],</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>                     index_col<span class="op">=</span><span class="st">"time"</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>viento.columns <span class="op">=</span> [<span class="st">"ws_kmh"</span>]</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>viento[<span class="st">"ws"</span>] <span class="op">=</span> viento[<span class="st">"ws_kmh"</span>] <span class="op">/</span> <span class="fl">3.6</span>  <span class="co"># km/h → m/s</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>viento <span class="op">=</span> viento[<span class="st">"ws"</span>]</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="co"># statsmodels prefiere índice con frecuencia explícita para SARIMA horario</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>viento <span class="op">=</span> viento.asfreq(<span class="st">"h"</span>)</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="bu">len</span>(viento)<span class="sc">}</span><span class="ss"> obs horarias · </span><span class="sc">{</span>viento<span class="sc">.</span>index<span class="sc">.</span><span class="bu">min</span>()<span class="sc">}</span><span class="ss"> a </span><span class="sc">{</span>viento<span class="sc">.</span>index<span class="sc">.</span><span class="bu">max</span>()<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"media = </span><span class="sc">{</span>viento<span class="sc">.</span>mean()<span class="sc">:.2f}</span><span class="ss"> m/s, desv = </span><span class="sc">{</span>viento<span class="sc">.</span>std()<span class="sc">:.2f}</span><span class="ss"> m/s"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>2208 obs horarias · 2023-06-01 00:00:00 a 2023-08-31 23:00:00
media = 4.14 m/s, desv = 2.37 m/s</code></pre>
</div>
</div>
</section>
<section id="p2-recordatorio-el-ciclo-diario-que-arma-no-pudo-5-min" class="level2" data-number="18.2">
<h2 data-number="18.2" class="anchored" data-anchor-id="p2-recordatorio-el-ciclo-diario-que-arma-no-pudo-5-min"><span class="header-section-number">18.2</span> P2 · Recordatorio · el ciclo diario que ARMA no pudo · 5 min</h2>
<p>Repasamos el diagnóstico de 014b sobre la serie <strong>cruda</strong> para anclar el problema que SARIMA viene a resolver. Si ya lo tienes fresco, este P2 puedes correrlo de corrido.</p>
<div id="7cd8dc68" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-05-27T17:52:24.196208Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-05-27T17:52:24.196149Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-05-27T17:52:24.310399Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-05-27T17:52:24.309928Z&quot;}}" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>mirar(viento, <span class="st">"viento crudo (recordatorio)"</span>, lags<span class="op">=</span><span class="dv">72</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>ADF · viento crudo (recordatorio):  estadístico = -2.743,  p = 0.0668  →  NO estacionaria</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="016_SARIMA_LaVentosa_src_files/figure-html/cell-5-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>Lectura (idéntica a 014b).</strong> La ACF tiene picos claros y persistentes en lags <strong>24, 48, 72</strong> — la firma del ciclo diario. PACF muestra el lag 1 dominante (persistencia sinóptica) y un eco estacional.</p>
<p>En 014b resolvimos esto <strong>por fuera del modelo</strong>: restando climatología por hora y ajustando ARMA(2,1) sobre la anomalía. Aquí lo resolvemos <strong>por dentro</strong>: diferenciando estacionalmente con <span class="math inline">\(\nabla_{24}\)</span> y dejando que SARIMA aprenda el componente estacional como parámetros.</p>
</section>
<section id="p3-identificación-sarima-10-min" class="level2" data-number="18.3">
<h2 data-number="18.3" class="anchored" data-anchor-id="p3-identificación-sarima-10-min"><span class="header-section-number">18.3</span> P3 · Identificación SARIMA · 10 min</h2>
<p>Tres pasos: aplicar <span class="math inline">\(\nabla_{24}\)</span>, mirar el resultado, y leer los órdenes <span class="math inline">\((p, q, P, Q)\)</span> de la nueva ACF/PACF.</p>
<section id="paso-1-diferenciación-estacional-nabla_24" class="level3" data-number="18.3.1">
<h3 data-number="18.3.1" class="anchored" data-anchor-id="paso-1-diferenciación-estacional-nabla_24"><span class="header-section-number">18.3.1</span> Paso 1 — diferenciación estacional <span class="math inline">\(\nabla_{24}\)</span></h3>
<div id="a14ad55d" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-05-27T17:52:24.311567Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-05-27T17:52:24.311480Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-05-27T17:52:24.474818Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-05-27T17:52:24.474409Z&quot;}}" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>viento_d24 <span class="op">=</span> viento.diff(<span class="dv">24</span>).dropna()</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>mirar(viento_d24, <span class="vs">r"</span><span class="dv">$</span><span class="ch">\n</span><span class="vs">abla_</span><span class="op">{24}</span><span class="dv">$</span><span class="vs"> viento"</span>, lags<span class="op">=</span><span class="dv">72</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>ADF · $\nabla_{24}$ viento:  estadístico = -6.920,  p = 0.0000  →  estacionaria</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="016_SARIMA_LaVentosa_src_files/figure-html/cell-6-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>Lectura.</strong></p>
<ul>
<li><strong>ADF:</strong> ahora rechaza claramente <span class="math inline">\(H_0\)</span> (<span class="math inline">\(p \approx 0\)</span>). La serie es estacionaria — sin tendencia, sin ciclo diario. Esto <strong>confirma <span class="math inline">\(D = 1\)</span></strong>.</li>
<li><strong>ACF:</strong> picos cortos en lags 1–3 (persistencia residual) y un pico <strong>negativo grande en lag 24</strong> que decae rápido en <span class="math inline">\(2 \cdot 24\)</span> y siguientes. La firma típica de <strong>SMA(1) estacional</strong>: <span class="math inline">\(Q = 1\)</span>.</li>
<li><strong>PACF:</strong> picos en lags 1–2 (componente AR no estacional) y un patrón geométricamente decreciente en lags 24, 48, 72 → consistente con SMA estacional (no SAR).</li>
</ul>
<p><strong>Hipótesis de orden inicial:</strong> <span class="math inline">\(\text{SARIMA}(2,\, 0,\, 1)(0,\, 1,\, 1)_{24}\)</span>. Conservamos la parte no estacional ARMA(2,1) que ya funcionó en 014b sobre la anomalía, y añadimos el bloque estacional <span class="math inline">\((0, 1, 1)_{24}\)</span> tipo airline.</p>
<blockquote class="blockquote">
<p><strong>Para discutir con la clase.</strong> - ¿Por qué <span class="math inline">\(D = 1\)</span> y no <span class="math inline">\(D = 0\)</span> con <span class="math inline">\(P\)</span> grande? (<span class="math inline">\(D = 1\)</span> elimina el ciclo <strong>determinista</strong> de forma estructural y suele bastar; subir <span class="math inline">\(P\)</span> acumula parámetros y rara vez gana en AIC para datos horarios). - ¿Por qué <span class="math inline">\(d = 0\)</span>? (El ADF sobre la anomalía en 014b fue <em>borderline</em> y aquí sobre <span class="math inline">\(\nabla_{24}\, y\)</span> rechaza con holgura. No necesitamos diferencia ordinaria — sería sobre-diferenciar). - ¿Y si vieran picos significativos en lag 48 además de 24? (Probarían <span class="math inline">\(Q = 2\)</span> o un mix SARMA estacional <span class="math inline">\((1, 1, 1)\)</span>. Casi nunca es necesario en wind data horario).</p>
</blockquote>
</section>
</section>
<section id="p4-iteración-box-jenkins-con-sarima-15-min" class="level2" data-number="18.4">
<h2 data-number="18.4" class="anchored" data-anchor-id="p4-iteración-box-jenkins-con-sarima-15-min"><span class="header-section-number">18.4</span> P4 · Iteración Box-Jenkins con SARIMA · 15 min</h2>
<p>Mismo loop que en 014b: <strong>estimar → diagnosticar → decidir</strong>. Empezamos por una parametrización simple (solo bloque estacional) y vamos añadiendo el componente no estacional cuando los residuales lo pidan.</p>
<section id="iteración-1-sarima0-0-00-1-1_24-solo-bloque-estacional" class="level3" data-number="18.4.1">
<h3 data-number="18.4.1" class="anchored" data-anchor-id="iteración-1-sarima0-0-00-1-1_24-solo-bloque-estacional"><span class="header-section-number">18.4.1</span> Iteración 1 · SARIMA(0, 0, 0)(0, 1, 1)_24 — solo bloque estacional</h3>
<p>Cero componente AR/MA no estacional. Es la versión más simple posible: aplica <span class="math inline">\(\nabla_{24}\)</span> y modela los residuos con un único <span class="math inline">\(\Theta_1\)</span>. Sirve para <strong>separar la contribución del bloque estacional</strong> de la del bloque AR/MA.</p>
<div id="b6da6b27" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-05-27T17:52:24.475999Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-05-27T17:52:24.475930Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-05-27T17:52:24.864050Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-05-27T17:52:24.863723Z&quot;}}" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>sar_011 <span class="op">=</span> SARIMAX(viento, order<span class="op">=</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>), seasonal_order<span class="op">=</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">24</span>),</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>                  enforce_stationarity<span class="op">=</span><span class="va">False</span>, enforce_invertibility<span class="op">=</span><span class="va">False</span>).fit(disp<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Theta_estacional = </span><span class="sc">{</span>sar_011<span class="sc">.</span>params[<span class="st">'ma.S.L24'</span>]<span class="sc">:.3f}</span><span class="ss">    AIC = </span><span class="sc">{</span>sar_011<span class="sc">.</span>aic<span class="sc">:.1f}</span><span class="ss">"</span>)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>diagnostico_sarima(sar_011, <span class="st">"SARIMA(0,0,0)(0,1,1)_24"</span>, lags<span class="op">=</span><span class="dv">48</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Theta_estacional = -0.260    AIC = 7797.5</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="016_SARIMA_LaVentosa_src_files/figure-html/cell-7-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Ljung-Box · SARIMA(0,0,0)(0,1,1)_24
       lb_stat  lb_pvalue
10   9264.3069        0.0
20  11331.0420        0.0
24  11441.5032        0.0
48  11658.0030        0.0</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="6">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">lb_stat</th>
<th data-quarto-table-cell-role="th">lb_pvalue</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">10</th>
<td>9264.306871</td>
<td>0.0</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">20</th>
<td>11331.041965</td>
<td>0.0</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">24</th>
<td>11441.503179</td>
<td>0.0</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">48</th>
<td>11658.002990</td>
<td>0.0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p><strong>Veredicto iter 1.</strong> <span class="math inline">\(\Theta_1 \approx -0.26\)</span> (no es el clásico <span class="math inline">\(\approx -0.9\)</span> porque sin AR/MA absorbiendo la persistencia, el modelo manda casi toda la señal a <span class="math inline">\(\sigma^2\)</span> y el SMA no puede compensar solo). <strong>AIC = 7797.5</strong> — enorme. Ljung-Box rechaza con <span class="math inline">\(p \approx 0\)</span> a todos los lags (10, 20, 24, 48). La ACF residual sigue con picos enormes en lags cortos: queda toda la persistencia sinóptica sin modelar.</p>
<p><strong>Decisión:</strong> añadir componente AR no estacional. Esperamos un salto grande en AIC (el bloque estacional solo no es competitivo en datos con persistencia fuerte como el viento).</p>
</section>
<section id="iteración-2-sarima2-0-00-1-1_24-agregamos-ar2" class="level3" data-number="18.4.2">
<h3 data-number="18.4.2" class="anchored" data-anchor-id="iteración-2-sarima2-0-00-1-1_24-agregamos-ar2"><span class="header-section-number">18.4.2</span> Iteración 2 · SARIMA(2, 0, 0)(0, 1, 1)_24 — agregamos AR(2)</h3>
<div id="0d8ddefa" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-05-27T17:52:24.865112Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-05-27T17:52:24.865052Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-05-27T17:52:26.600330Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-05-27T17:52:26.599923Z&quot;}}" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>sar_2_011 <span class="op">=</span> SARIMAX(viento, order<span class="op">=</span>(<span class="dv">2</span>, <span class="dv">0</span>, <span class="dv">0</span>), seasonal_order<span class="op">=</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">24</span>),</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>                    enforce_stationarity<span class="op">=</span><span class="va">False</span>, enforce_invertibility<span class="op">=</span><span class="va">False</span>).fit(disp<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(sar_2_011.summary().tables[<span class="dv">1</span>])</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">AIC = </span><span class="sc">{</span>sar_2_011<span class="sc">.</span>aic<span class="sc">:.1f}</span><span class="ss">  (iter 1 daba </span><span class="sc">{</span>sar_011<span class="sc">.</span>aic<span class="sc">:.1f}</span><span class="ss">)"</span>)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>diagnostico_sarima(sar_2_011, <span class="st">"SARIMA(2,0,0)(0,1,1)_24"</span>, lags<span class="op">=</span><span class="dv">48</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>==============================================================================
                 coef    std err          z      P&gt;|z|      [0.025      0.975]
------------------------------------------------------------------------------
ar.L1          0.8586      0.016     53.933      0.000       0.827       0.890
ar.L2          0.0983      0.016      6.244      0.000       0.067       0.129
ma.S.L24      -1.1058      0.012    -90.365      0.000      -1.130      -1.082
sigma2         0.2716      0.008     33.673      0.000       0.256       0.287
==============================================================================

AIC = 3782.2  (iter 1 daba 7797.5)</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="016_SARIMA_LaVentosa_src_files/figure-html/cell-8-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Ljung-Box · SARIMA(2,0,0)(0,1,1)_24
    lb_stat  lb_pvalue
10  11.9845     0.2861
20  24.4902     0.2216
24  38.7023     0.0293
48  80.9286     0.0021</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="7">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">lb_stat</th>
<th data-quarto-table-cell-role="th">lb_pvalue</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">10</th>
<td>11.984458</td>
<td>0.286098</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">20</th>
<td>24.490178</td>
<td>0.221636</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">24</th>
<td>38.702344</td>
<td>0.029338</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">48</th>
<td>80.928623</td>
<td>0.002068</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p><strong>Veredicto iter 2.</strong> <span class="math inline">\(\phi_1 \approx 0.86\)</span>, <span class="math inline">\(\phi_2 \approx 0.10\)</span>, <span class="math inline">\(\Theta_1 \approx -1.11\)</span> (el SMA ahora sí jala fuerte porque la AR limpió la persistencia primero). <strong>AIC cae de 7797 → 3782</strong> — salto decisivo (<span class="math inline">\(\Delta \text{AIC} &gt; 4000\)</span>). Ljung-Box pasa cómodamente a 10 lags (<span class="math inline">\(p \approx 0.29\)</span>) y 20 (<span class="math inline">\(p \approx 0.22\)</span>), <strong>pero rechaza a 24 (<span class="math inline">\(p \approx 0.03\)</span>) y 48 (<span class="math inline">\(p \approx 0.002\)</span>)</strong>: la ACF residual aún tiene picos pequeños cerca de los múltiplos de 24. El coeficiente <span class="math inline">\(\theta_1\)</span> no estacional puede ayudar a apagar el último eco corto.</p>
<p><strong>Decisión:</strong> añadir MA(1) no estacional → ARMA(2, 1) en el bloque corto, igual que ganó en 014b.</p>
</section>
<section id="iteración-3-sarima2-0-10-1-1_24-la-versión-airline-para-viento" class="level3" data-number="18.4.3">
<h3 data-number="18.4.3" class="anchored" data-anchor-id="iteración-3-sarima2-0-10-1-1_24-la-versión-airline-para-viento"><span class="header-section-number">18.4.3</span> Iteración 3 · SARIMA(2, 0, 1)(0, 1, 1)_24 — la versión “airline para viento”</h3>
<div id="69fbd2f4" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-05-27T17:52:26.601304Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-05-27T17:52:26.601245Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-05-27T17:52:35.260903Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-05-27T17:52:35.260544Z&quot;}}" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>sar_full <span class="op">=</span> SARIMAX(viento, order<span class="op">=</span>(<span class="dv">2</span>, <span class="dv">0</span>, <span class="dv">1</span>), seasonal_order<span class="op">=</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">24</span>),</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>                   enforce_stationarity<span class="op">=</span><span class="va">False</span>, enforce_invertibility<span class="op">=</span><span class="va">False</span>).fit(disp<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(sar_full.summary().tables[<span class="dv">1</span>])</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">AIC = </span><span class="sc">{</span>sar_full<span class="sc">.</span>aic<span class="sc">:.1f}</span><span class="ss">"</span>)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>diagnostico_sarima(sar_full, <span class="st">"SARIMA(2,0,1)(0,1,1)_24"</span>, lags<span class="op">=</span><span class="dv">48</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>/Users/gbv/anomalias-2026-2/.venv/lib/python3.13/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>==============================================================================
                 coef    std err          z      P&gt;|z|      [0.025      0.975]
------------------------------------------------------------------------------
ar.L1          1.7901      0.033     53.879      0.000       1.725       1.855
ar.L2         -0.7923      0.032    -24.487      0.000      -0.856      -0.729
ma.L1         -0.9090      0.026    -34.772      0.000      -0.960      -0.858
ma.S.L24      -0.9154      0.010    -91.891      0.000      -0.935      -0.896
sigma2         0.3289      0.007     47.990      0.000       0.315       0.342
==============================================================================

AIC = 3764.0</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="016_SARIMA_LaVentosa_src_files/figure-html/cell-9-output-3.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Ljung-Box · SARIMA(2,0,1)(0,1,1)_24
    lb_stat  lb_pvalue
10  12.4864     0.2538
20  26.8649     0.1391
24  39.5372     0.0240
48  80.2935     0.0024</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="8">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">lb_stat</th>
<th data-quarto-table-cell-role="th">lb_pvalue</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">10</th>
<td>12.486401</td>
<td>0.253821</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">20</th>
<td>26.864948</td>
<td>0.139107</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">24</th>
<td>39.537176</td>
<td>0.023965</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">48</th>
<td>80.293466</td>
<td>0.002391</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p><strong>Veredicto iter 3.</strong> <span class="math inline">\(\phi_1 \approx 1.79\)</span>, <span class="math inline">\(\phi_2 \approx -0.79\)</span>, <span class="math inline">\(\theta_1 \approx -0.91\)</span>, <span class="math inline">\(\Theta_1 \approx -0.92\)</span> — los cuatro coeficientes son altísimamente significativos (<span class="math inline">\(|z| &gt; 24\)</span> todos). <strong>AIC = 3764</strong>, baja otras ~18 unidades respecto a iter 2 (<span class="math inline">\(\Delta\text{AIC} &gt; 10\)</span> → mejora decisiva). Ljung-Box mejora a 10 (<span class="math inline">\(p \approx 0.25\)</span>) y 20 lags (<span class="math inline">\(p \approx 0.14\)</span>), pero <strong>sigue rechazando levemente a lag 24 (<span class="math inline">\(p \approx 0.024\)</span>) y 48 (<span class="math inline">\(p \approx 0.002\)</span>)</strong>.</p>
<p><strong>Lectura honesta.</strong> Es el mismo fenómeno que en 014b sobre la anomalía (cúmulo pequeño cerca de lag 24): el ciclo diario <strong>varía día a día</strong> — amplitud distinta con frentes, ligero desplazamiento de fase — y ni un SMA estacional ni una climatología fija pueden absorberlo del todo. Para producción seria valdría probar <span class="math inline">\((P, D, Q) = (1, 1, 1)\)</span> o incluso TBATS para múltiples estacionalidades. Para los fines del lab, este SARIMA basta: residuales prácticamente blancos a horizontes operativos (≤ 20 h), AIC mínimo, parámetros significativos.</p>
<p><strong>Aquí paramos.</strong> Subir más orden no aportaría: principio de parsimonia.</p>
<blockquote class="blockquote">
<p><strong>Para discutir con la clase.</strong> - ¿Por qué no añadimos también SAR estacional (<span class="math inline">\(P = 1\)</span>)? (La PACF estacional no mostró picos en lag 24 — un patrón <strong>puramente SMA</strong>. Añadir SAR inflaría parámetros sin ganar ajuste). - El <span class="math inline">\(\Theta_1\)</span> estacional sale típicamente cercano a <span class="math inline">\(-0.9\)</span>. ¿Por qué tan grande? (Es el clásico ajuste airline: cuando <span class="math inline">\(\Theta_1 \to -1\)</span> la diferencia estacional se “des-diferencia” parcialmente — equivale a suavizar exponencialmente el patrón estacional en lugar de copiarlo crudo).</p>
</blockquote>
</section>
<section id="resumen-comparativo-tres-iteraciones-sarima" class="level3" data-number="18.4.4">
<h3 data-number="18.4.4" class="anchored" data-anchor-id="resumen-comparativo-tres-iteraciones-sarima"><span class="header-section-number">18.4.4</span> Resumen comparativo · tres iteraciones SARIMA</h3>
<div id="ef32a1e0" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-05-27T17:52:35.261931Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-05-27T17:52:35.261870Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-05-27T17:52:35.268116Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-05-27T17:52:35.267788Z&quot;}}" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> lb_pvalue_sarima(modelo, lag<span class="op">=</span><span class="dv">20</span>):</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>    p, d, q <span class="op">=</span> modelo.model.order</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>    P, D, Q, s <span class="op">=</span> modelo.model.seasonal_order</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>    burn <span class="op">=</span> <span class="bu">max</span>(p <span class="op">+</span> P <span class="op">*</span> s, q <span class="op">+</span> Q <span class="op">*</span> s, s <span class="op">*</span> D <span class="op">+</span> d) <span class="op">+</span> <span class="dv">1</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>    resid <span class="op">=</span> pd.Series(modelo.resid).iloc[burn:].dropna()</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> acorr_ljungbox(resid, lags<span class="op">=</span>[lag], return_df<span class="op">=</span><span class="va">True</span>)[<span class="st">"lb_pvalue"</span>].iloc[<span class="dv">0</span>]</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>resumen_sar <span class="op">=</span> pd.DataFrame({</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">"AIC"</span>:             [sar_011.aic, sar_2_011.aic, sar_full.aic],</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">"BIC"</span>:             [sar_011.bic, sar_2_011.bic, sar_full.bic],</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">"LB p-value (20)"</span>: [lb_pvalue_sarima(sar_011),</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>                        lb_pvalue_sarima(sar_2_011),</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>                        lb_pvalue_sarima(sar_full)],</span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">"LB p-value (48)"</span>: [lb_pvalue_sarima(sar_011, <span class="dv">48</span>),</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>                        lb_pvalue_sarima(sar_2_011, <span class="dv">48</span>),</span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>                        lb_pvalue_sarima(sar_full, <span class="dv">48</span>)],</span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>}, index<span class="op">=</span>[<span class="st">"(0,0,0)(0,1,1)_24"</span>,</span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a>          <span class="st">"(2,0,0)(0,1,1)_24"</span>,</span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a>          <span class="st">"(2,0,1)(0,1,1)_24"</span>]).<span class="bu">round</span>(<span class="dv">4</span>)</span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(resumen_sar)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                         AIC        BIC  LB p-value (20)  LB p-value (48)
(0,0,0)(0,1,1)_24  7797.5374  7808.8922           0.0000           0.0000
(2,0,0)(0,1,1)_24  3782.2046  3804.9142           0.2216           0.0021
(2,0,1)(0,1,1)_24  3763.9831  3792.3678           0.1391           0.0024</code></pre>
</div>
</div>
<p><strong>Lectura.</strong></p>
<ul>
<li><strong>AIC monotónico decreciente.</strong> 7797 → 3782 → 3764. El primer salto (<span class="math inline">\(\Delta &gt; 4000\)</span>) viene de <strong>dejar que la AR absorba la persistencia</strong>; el segundo (<span class="math inline">\(\Delta \approx 18\)</span>) viene de añadir el MA no estacional. Cada componente justifica su costo.</li>
<li><strong>LB a 10 y 20 lags pasa cómodo</strong> en iter 2 y 3 → residuales blancos a horizontes operativos (≤ 1 día).</li>
<li><strong>LB a 24 y 48 lags sigue rechazando</strong> levemente en iter 2 y 3 → cúmulo residual cerca del múltiplo de 24, exactamente igual al fenómeno reportado en 014b sobre la anomalía. Es la firma del <strong>ciclo diario que varía día a día</strong>, no absorbible por una climatología fija ni por un SMA estacional simple. Subir a <span class="math inline">\((P, D, Q) = (1, 1, 1)\)</span> o explorar TBATS son las próximas herramientas; para este lab, nos quedamos con <code>(2, 0, 1)(0, 1, 1)_{24}</code>.</li>
</ul>
</section>
</section>
<section id="p5-pronóstico-y-comparativo-final-12-min" class="level2" data-number="18.5">
<h2 data-number="18.5" class="anchored" data-anchor-id="p5-pronóstico-y-comparativo-final-12-min"><span class="header-section-number">18.5</span> P5 · Pronóstico y comparativo final · 12 min</h2>
<p>Aquí cerramos el lab. Reajustamos los tres candidatos sobre las primeras <span class="math inline">\(N - 24\)</span> horas, pronosticamos 24 h, y comparamos contra el real <strong>en una sola figura y una sola tabla</strong>:</p>
<ol type="1">
<li><strong>Persistencia ingenua</strong> (baseline): “mañana hora <span class="math inline">\(h\)</span> = hoy hora <span class="math inline">\(h\)</span>”.</li>
<li><strong>ARMA(2,1) sobre anomalía + climatología</strong> — el modelo modular del lab 014b.</li>
<li>**SARIMA(2,0,1)(0,1,1)_24 sobre crudo** — el modelo integrado de hoy.</li>
</ol>
<section id="setup-del-backtest" class="level3" data-number="18.5.1">
<h3 data-number="18.5.1" class="anchored" data-anchor-id="setup-del-backtest"><span class="header-section-number">18.5.1</span> Setup del backtest</h3>
<div id="fdc5ca72" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-05-27T17:52:35.269012Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-05-27T17:52:35.268954Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-05-27T17:52:35.271639Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-05-27T17:52:35.271305Z&quot;}}" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>H <span class="op">=</span> <span class="dv">24</span>  <span class="co"># horas de hold-out</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>viento_train <span class="op">=</span> viento.iloc[:<span class="op">-</span>H]</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>viento_test  <span class="op">=</span> viento.iloc[<span class="op">-</span>H:]</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>real <span class="op">=</span> viento_test.values</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Climatología y anomalía calculadas SOLO con datos de entrenamiento</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>clima_h <span class="op">=</span> viento_train.groupby(viento_train.index.hour).mean()</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>ws_anom_train <span class="op">=</span> viento_train <span class="op">-</span> viento_train.index.hour.<span class="bu">map</span>(clima_h)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="modelo-1-arma2-1-sobre-anomalía-climatología" class="level3" data-number="18.5.2">
<h3 data-number="18.5.2" class="anchored" data-anchor-id="modelo-1-arma2-1-sobre-anomalía-climatología"><span class="header-section-number">18.5.2</span> Modelo 1 · ARMA(2, 1) sobre anomalía + climatología</h3>
<p>Reproduce exactamente el flujo del lab 014b, ahora con <code>clima_h</code> calculada en el train para no contaminar el hold-out.</p>
<div id="687f545a" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-05-27T17:52:35.272623Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-05-27T17:52:35.272561Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-05-27T17:52:35.517620Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-05-27T17:52:35.517196Z&quot;}}" data-execution_count="11">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>arma21 <span class="op">=</span> ARIMA(ws_anom_train, order<span class="op">=</span>(<span class="dv">2</span>, <span class="dv">0</span>, <span class="dv">1</span>)).fit()</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>fc_a   <span class="op">=</span> arma21.get_forecast(steps<span class="op">=</span>H)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>clima_test <span class="op">=</span> viento_test.index.hour.<span class="bu">map</span>(clima_h).values</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>fc_arma <span class="op">=</span> pd.Series(fc_a.predicted_mean.values <span class="op">+</span> clima_test, index<span class="op">=</span>viento_test.index)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>ic_arma <span class="op">=</span> fc_a.conf_int(alpha<span class="op">=</span><span class="fl">0.05</span>).values <span class="op">+</span> clima_test[:, <span class="va">None</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="modelo-2-sarima2-0-10-1-1_24-sobre-crudo" class="level3" data-number="18.5.3">
<h3 data-number="18.5.3" class="anchored" data-anchor-id="modelo-2-sarima2-0-10-1-1_24-sobre-crudo"><span class="header-section-number">18.5.3</span> Modelo 2 · SARIMA(2, 0, 1)(0, 1, 1)_24 sobre crudo</h3>
<div id="fd8d1c31" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-05-27T17:52:35.518816Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-05-27T17:52:35.518757Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-05-27T17:52:42.196894Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-05-27T17:52:42.196418Z&quot;}}" data-execution_count="12">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>sar_eval <span class="op">=</span> SARIMAX(viento_train, order<span class="op">=</span>(<span class="dv">2</span>, <span class="dv">0</span>, <span class="dv">1</span>), seasonal_order<span class="op">=</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">24</span>),</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>                   enforce_stationarity<span class="op">=</span><span class="va">False</span>, enforce_invertibility<span class="op">=</span><span class="va">False</span>).fit(disp<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>fc_s <span class="op">=</span> sar_eval.get_forecast(steps<span class="op">=</span>H)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>fc_sar <span class="op">=</span> pd.Series(fc_s.predicted_mean.values, index<span class="op">=</span>viento_test.index)</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>ic_sar <span class="op">=</span> fc_s.conf_int(alpha<span class="op">=</span><span class="fl">0.05</span>).values</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="baseline-persistencia-24-h" class="level3" data-number="18.5.4">
<h3 data-number="18.5.4" class="anchored" data-anchor-id="baseline-persistencia-24-h"><span class="header-section-number">18.5.4</span> Baseline · persistencia 24 h</h3>
<div id="4ff17aa9" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-05-27T17:52:42.198120Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-05-27T17:52:42.198060Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-05-27T17:52:42.199766Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-05-27T17:52:42.199464Z&quot;}}" data-execution_count="13">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>fc_persist <span class="op">=</span> pd.Series(viento.iloc[<span class="op">-</span><span class="dv">2</span><span class="op">*</span>H:<span class="op">-</span>H].values, index<span class="op">=</span>viento_test.index)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="figura-única-los-tres-pronósticos-contra-el-real" class="level3" data-number="18.5.5">
<h3 data-number="18.5.5" class="anchored" data-anchor-id="figura-única-los-tres-pronósticos-contra-el-real"><span class="header-section-number">18.5.5</span> Figura única — los tres pronósticos contra el real</h3>
<div id="fa1bba47" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-05-27T17:52:42.200871Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-05-27T17:52:42.200806Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-05-27T17:52:42.251587Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-05-27T17:52:42.251277Z&quot;}}" data-execution_count="14">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>ventana_train <span class="op">=</span> viento.iloc[<span class="op">-</span><span class="dv">72</span><span class="op">-</span>H:<span class="op">-</span>H]</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="fl">4.5</span>))</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>ventana_train.plot(ax<span class="op">=</span>ax, lw<span class="op">=</span><span class="fl">1.0</span>, color<span class="op">=</span><span class="st">"C2"</span>, label<span class="op">=</span><span class="st">"histórico (entrenamiento)"</span>)</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>viento_test.plot(ax<span class="op">=</span>ax,  color<span class="op">=</span><span class="st">"k"</span>,  lw<span class="op">=</span><span class="fl">1.8</span>, label<span class="op">=</span><span class="st">"real (hold-out 24 h)"</span>)</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>fc_persist.plot(ax<span class="op">=</span>ax,   color<span class="op">=</span><span class="st">"C7"</span>, lw<span class="op">=</span><span class="fl">1.2</span>, ls<span class="op">=</span><span class="st">":"</span>,  label<span class="op">=</span><span class="st">"persistencia 24 h"</span>)</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>fc_arma.plot(ax<span class="op">=</span>ax,      color<span class="op">=</span><span class="st">"C3"</span>, lw<span class="op">=</span><span class="fl">1.4</span>,           label<span class="op">=</span><span class="st">"ARMA(2,1) + climatología"</span>)</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>fc_sar.plot(ax<span class="op">=</span>ax,       color<span class="op">=</span><span class="st">"C0"</span>, lw<span class="op">=</span><span class="fl">1.6</span>,           label<span class="op">=</span><span class="st">"SARIMA(2,0,1)(0,1,1)$_</span><span class="sc">{24}</span><span class="st">$"</span>)</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>ax.fill_between(fc_sar.index, ic_sar[:, <span class="dv">0</span>], ic_sar[:, <span class="dv">1</span>],</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>                color<span class="op">=</span><span class="st">"C0"</span>, alpha<span class="op">=</span><span class="fl">0.18</span>, label<span class="op">=</span><span class="st">"IC 95% SARIMA"</span>)</span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>ax.axvline(viento_test.index[<span class="dv">0</span>], color<span class="op">=</span><span class="st">"gray"</span>, lw<span class="op">=</span><span class="fl">0.6</span>, ls<span class="op">=</span><span class="st">"--"</span>)</span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Pronóstico vs. real · últimas 24 h · La Ventosa"</span>)</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"m/s"</span>)<span class="op">;</span> ax.legend(loc<span class="op">=</span><span class="st">"best"</span>)<span class="op">;</span> plt.tight_layout()<span class="op">;</span> plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="016_SARIMA_LaVentosa_src_files/figure-html/cell-15-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="tabla-comparativa" class="level3" data-number="18.5.6">
<h3 data-number="18.5.6" class="anchored" data-anchor-id="tabla-comparativa"><span class="header-section-number">18.5.6</span> Tabla comparativa</h3>
<div id="ce3ac94e" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-05-27T17:52:42.252594Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-05-27T17:52:42.252535Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-05-27T17:52:42.255575Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-05-27T17:52:42.255311Z&quot;}}" data-execution_count="15">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> metricas(real, fc, ic<span class="op">=</span><span class="va">None</span>, nombre<span class="op">=</span><span class="st">""</span>):</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>    mae  <span class="op">=</span> <span class="bu">float</span>(np.mean(np.<span class="bu">abs</span>(real <span class="op">-</span> fc)))</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>    rmse <span class="op">=</span> <span class="bu">float</span>(np.sqrt(np.mean((real <span class="op">-</span> fc) <span class="op">**</span> <span class="dv">2</span>)))</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>    cob  <span class="op">=</span> (<span class="bu">float</span>(np.mean((real <span class="op">&gt;=</span> ic[:, <span class="dv">0</span>]) <span class="op">&amp;</span> (real <span class="op">&lt;=</span> ic[:, <span class="dv">1</span>])))</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>            <span class="cf">if</span> ic <span class="kw">is</span> <span class="kw">not</span> <span class="va">None</span> <span class="cf">else</span> np.nan)</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> {<span class="st">"MAE (m/s)"</span>: mae, <span class="st">"RMSE (m/s)"</span>: rmse, <span class="st">"Cobertura IC95% (%)"</span>: cob <span class="op">*</span> <span class="dv">100</span>}</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>tabla <span class="op">=</span> pd.DataFrame({</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Persistencia 24 h"</span>:             metricas(real, fc_persist.values),</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">"ARMA(2,1) + clima (014b)"</span>:      metricas(real, fc_arma.values, ic_arma),</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">"SARIMA(2,0,1)(0,1,1)_24"</span>:       metricas(real, fc_sar.values,  ic_sar),</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>}).T.<span class="bu">round</span>(<span class="dv">2</span>)</span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(tabla)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                          MAE (m/s)  RMSE (m/s)  Cobertura IC95% (%)
Persistencia 24 h              1.77        2.01                  NaN
ARMA(2,1) + clima (014b)       0.74        0.86                100.0
SARIMA(2,0,1)(0,1,1)_24        0.81        0.92                100.0</code></pre>
</div>
</div>
</section>
<section id="lectura-final-hay-mejora" class="level3" data-number="18.5.7">
<h3 data-number="18.5.7" class="anchored" data-anchor-id="lectura-final-hay-mejora"><span class="header-section-number">18.5.7</span> Lectura final · ¿hay mejora?</h3>
<p>Los números observados en este hold-out:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 48%">
<col style="width: 14%">
<col style="width: 15%">
<col style="width: 22%">
</colgroup>
<thead>
<tr class="header">
<th>Modelo</th>
<th>MAE (m/s)</th>
<th>RMSE (m/s)</th>
<th>Cobertura IC95%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Persistencia 24 h (baseline)</td>
<td><strong>1.77</strong></td>
<td>2.01</td>
<td>—</td>
</tr>
<tr class="even">
<td>ARMA(2,1) + climatología (014b)</td>
<td>0.74</td>
<td>0.86</td>
<td>100%</td>
</tr>
<tr class="odd">
<td>SARIMA(2,0,1)(0,1,1)<span class="math inline">\(_{24}\)</span></td>
<td>0.81</td>
<td>0.92</td>
<td>100%</td>
</tr>
</tbody>
</table>
<p><strong>Cuatro lecturas para discutir antes de cerrar.</strong></p>
<p><strong>1. SARIMA reproduce el ciclo sin que se lo digamos.</strong> A diferencia del AR(2) crudo de 014b (que se aplanaba), el pronóstico SARIMA tiene <strong>picos y valles diarios</strong> porque el bloque estacional aprendió la forma del ciclo. La climatología quedó <strong>internalizada</strong> como parámetro <span class="math inline">\(\Theta_1\)</span>, no como preprocesamiento externo. Esa es <strong>la diferencia cualitativa central</strong>.</p>
<p><strong>2. Ambos modelos avanzados aplastan al baseline.</strong> En 014b, ARMA(2,1)+clima <em>perdía</em> contra una persistencia particularmente afortunada (MAE 0.73 vs 0.53). En este hold-out el día de prueba <strong>no se parece al anterior</strong> (medias 2.28 vs 1.05 m/s) y la persistencia colapsa a MAE 1.77. Aquí, tanto el flujo modular como SARIMA ganan por más del <strong>doble</strong> sobre persistencia — el orden de magnitud de la mejora no es trivial.</p>
<p><strong>3. SARIMA y ARMA+clima quedan empatados (técnicamente).</strong> Diferencia de ~0.07 m/s en MAE sobre un único hold-out de 24 puntos: <strong>no es significativa</strong>. Modulo aleatoriedad muestral, son el mismo modelo medido en una sola ventana. Para un veredicto sólido habría que repetir el backtest sobre muchas ventanas (cross-validation rolling-origin, ejercicio 2). El resultado importante no es “cuál ganó”, es que <strong>ambos resuelven el problema</strong> que en 014b dejamos abierto.</p>
<p><strong>4. ¿Qué pagamos por la mejora estructural?</strong> Cuatro cosas:</p>
<ul>
<li><strong>Más parámetros</strong> (<span class="math inline">\(\phi_1, \phi_2, \theta_1, \Theta_1\)</span> vs <span class="math inline">\(\phi_1, \phi_2, \theta_1\)</span> más una climatología tabulada). Ojo: la climatología son <strong>24 medias</strong> — en estricto rigor también son “parámetros”, solo que estimados fuera del modelo.</li>
<li><strong>Ajuste más lento</strong> (filtro de Kalman vs MLE cerrado de ARIMA simple).</li>
<li><strong>Menos interpretabilidad inmediata</strong> — el bloque estacional es un parámetro <span class="math inline">\(\Theta_1\)</span>, no una curva que graficas y entiendes a ojo.</li>
<li><strong>Riesgo de sobreajuste</strong> si <span class="math inline">\(s\)</span> está mal elegido o si los datos son cortos relativos a <span class="math inline">\(s\)</span> (regla práctica: al menos <span class="math inline">\(5\cdot s\)</span> observaciones por bloque estacional; aquí tenemos <span class="math inline">\(\sim 90\)</span> días <span class="math inline">\(\times\, 24\)</span> h = <span class="math inline">\(&gt; 90\cdot s\)</span>, cómodo).</li>
</ul>
<blockquote class="blockquote">
<p><strong>Lección final.</strong> ARMA + climatología y SARIMA <strong>resuelven el mismo problema con filosofías opuestas</strong>: modular (separar lo determinista de lo estocástico y combinarlos a mano) vs integrado (un solo modelo que aprende todo). En producción de energía eólica las dos coexisten — el flujo modular para diagnóstico y comunicación (la climatología la lee un meteorólogo); el integrado para pronóstico operacional automático.</p>
<p><strong>La “mejora” frente a 014b no es haber bajado el MAE</strong> (los dos rondan los 0.8 m/s — empate técnico). La mejora es haber <strong>internalizado la estacionalidad dentro del modelo</strong>: ya no hay un paso de preprocesamiento frágil entre los datos y la predicción, y el bloque estacional se reestima junto con todo lo demás cada vez que reentrenas.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Para discutir con la clase.</strong> - ¿Cuál usarían si el cliente quiere <strong>explicar</strong> el pronóstico a un regulador? (Modular — la climatología es físicamente interpretable). - ¿Cuál usarían si el cliente quiere un <strong>pipeline automatizado</strong> que se reentrene cada semana sin intervención humana? (Integrado — no hay que mantener una tabla externa de climatología). - ¿Y si los datos vinieran con <strong>estacionalidad anidada</strong> (diaria + semanal)? (SARIMA con un único <span class="math inline">\(s\)</span> no basta — habría que usar SARIMA con períodos múltiples vía TBATS/Prophet o ARMA con dummies estacionales. La frontera de SARIMA univariado).</p>
</blockquote>
</section>
</section>
</section>
<section id="cierre-y-materiales-adicionales" class="level1" data-number="19">
<h1 data-number="19"><span class="header-section-number">19</span> Cierre y materiales adicionales</h1>
<section id="lo-que-te-llevas" class="level2" data-number="19.1">
<h2 data-number="19.1" class="anchored" data-anchor-id="lo-que-te-llevas"><span class="header-section-number">19.1</span> Lo que te llevas</h2>
<ol type="1">
<li><strong>SARIMA = ARIMA + bloque estacional</strong> con su propio <span class="math inline">\((P, D, Q)\)</span> en <span class="math inline">\(B^s\)</span>. Mismo Box-Jenkins, dos veces: identifica, estima, diagnostica.</li>
<li><strong>Diferenciación estacional <span class="math inline">\(\nabla_s\)</span></strong> mata patrones que se repiten cada <span class="math inline">\(s\)</span> pasos. Casi siempre <span class="math inline">\(D = 1\)</span> basta.</li>
<li><strong>Identifica <span class="math inline">\((P, Q)\)</span> mirando ACF/PACF en lags <span class="math inline">\(s, 2s, 3s\)</span></strong> — mismas reglas de “corta vs decae”, solo que aplicadas a los múltiplos del período.</li>
<li><strong>Comparativo de filosofías.</strong> Restar climatología + ARMA es modular y legible; SARIMA es integrado y, en este caso, <strong>gana en backtest</strong>. Los dos son herramientas válidas, no rivales.</li>
<li><strong>Límite de SARIMA univariado.</strong> Un solo período <span class="math inline">\(s\)</span>. Con estacionalidades anidadas o exógenas físicas (presión, temperatura) → SARIMAX o métodos más ricos (espacio-estados, ML supervisado).</li>
</ol>
</section>
<section id="ejercicios-para-entregar" class="level2" data-number="19.2">
<h2 data-number="19.2" class="anchored" data-anchor-id="ejercicios-para-entregar"><span class="header-section-number">19.2</span> Ejercicios para entregar</h2>
<ol type="1">
<li>Ajusta <span class="math inline">\(\text{SARIMA}(1, 0, 1)(1, 1, 0)_{24}\)</span> y <span class="math inline">\(\text{SARIMA}(2, 0, 1)(1, 1, 1)_{24}\)</span> sobre los mismos datos. Compara AIC, Ljung-Box y MAE en backtest contra el <code>(2, 0, 1)(0, 1, 1)_{24}</code> que vimos en clase. Argumenta si la añadidura de SAR estacional valió la pena.</li>
<li>Repite el pronóstico a horizonte <span class="math inline">\(H = 72\)</span> horas con el SARIMA elegido. Compara la <em>amplitud del IC 95%</em> contra ARMA(2,1)+clima al mismo horizonte: ¿cuál crece más rápido con <span class="math inline">\(H\)</span>? Interpreta físicamente.</li>
<li>Descarga viento horario de <strong>ene–mar 2023</strong> (régimen de norte invernal en La Ventosa). ¿La parametrización ganadora cambia? ¿<span class="math inline">\(\Theta_1\)</span> cambia mucho? Hipótesis: el ciclo diario debería ser menos pronunciado en invierno (contraste térmico más débil) → <span class="math inline">\(|\Theta_1|\)</span> menor.</li>
<li><strong>Stress test pedagógico.</strong> Quita el bloque estacional (<span class="math inline">\(\text{SARIMA}(2, 0, 1)(0, 0, 0)_{24}\)</span>) — es decir, ARMA(2,1) sobre crudo, exactamente el AR(2)-crudo de 014b ampliado. Mide MAE/RMSE en el mismo hold-out y verifica que está cerca del 1.07 m/s que vimos en 014b. Es la demostración numérica de que el bloque estacional es lo que aporta.</li>
</ol>
</section>
<section id="lecturas" class="level2" data-number="19.3">
<h2 data-number="19.3" class="anchored" data-anchor-id="lecturas"><span class="header-section-number">19.3</span> Lecturas</h2>
<ul>
<li>Box, Jenkins, Reinsel, Ljung (2015). <em>Time Series Analysis: Forecasting and Control</em> (5th ed.). Caps. 9 (estacionalidad).</li>
<li>Hyndman &amp; Athanasopoulos. <em>Forecasting: Principles and Practice</em>. https://otexts.com/fpp3/ — cap. 9.9 (SARIMA) y 9.10 (selección de órdenes).</li>
<li>Brockwell &amp; Davis (2016). <em>Introduction to Time Series and Forecasting</em> (3rd ed.). Cap. 6 (modelos estacionales y ajuste por máxima verosimilitud).</li>
</ul>
<p><strong>Datos.</strong> El CSV de viento es el mismo que en 014b — instrucciones de descarga vía Open-Meteo / ERA5 en el apéndice de ese notebook.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../notebooks/015_ARMA_Cheatsheet.html" class="pagination-link" aria-label="ARMA Cheatsheet · Box-Jenkins de bolsillo">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">ARMA Cheatsheet · Box-Jenkins de bolsillo</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../notebooks/017_SARIMA.html" class="pagination-link" aria-label="SARIMA — del modelo a un ejemplo con viento">
        <span class="nav-page-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">SARIMA — del modelo a un ejemplo con viento</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>